/* I bivi di carriera: restare o cambiare, specializzarsi o allargare,
   gestire persone o restare tecnici, citta' grande o provincia. Nessuna
   risposta e' quella giusta; ognuna sposta qualcosa che si vede. */
import { e, o } from './schema.js';

export default [
  e('specializzati', 'bivio', 'Specializzarsi o allargare',
    'Puoi diventare quello che sa fare una cosa meglio di tutti, o quello che capisce tutto un po’.',
    [
      o('verticale', 'Ti specializzi', { competenze: { settore: +3, tecnologia: +2 }, noia: +5 }),
      o('largo', 'Allarghi', { competenze: { gestione_progetti: +2, comunicazione: +1, finanza: +1, analisi_dati: +1 } }, { audace: true }),
    ], { predefinita: 'verticale', quando: { lavoro: 'vero', livelloMin: 1, settimanaMin: 50 }, peso: 1 }),
  e('gestire_o_no', 'bivio', 'Gestire persone o restare tecnico',
    'Il bivio classico. Chi gestisce sale; chi resta tecnico sa fare le cose.',
    [
      o('gestisci', 'Gestisci', { competenze: { leadership: +3, empatia: +1, negoziazione: +1 }, stress: +2, visibilita: +3 }, { audace: true }),
      o('tecnico', 'Resti tecnico', { competenze: { tecnologia: +3, settore: +2 }, felicita: +2, visibilita: -1 }),
    ], { predefinita: 'tecnico', quando: { lavoro: 'vero', livelloMin: 2, livelloMax: 3 }, peso: 1,
      lezione: 'Più sali, meno conta quanto sei bravo a fare le cose e più conta quanto sei bravo con le persone. Un direttore non fa il lavoro: decide, convince, tiene insieme.' }),
  e('citta_o_provincia', 'bivio', 'Città grande o provincia',
    'In città ci sono le aziende strutturate e gli affitti grandi. In provincia la vita costa meno, e le porte sono meno.',
    [
      o('citta', 'Città', { soldi: -1500, rete: +8, stress: +2, ritardo: { settimane: 4, effetti: { soldi: -250 }, testo: 'L’affitto di città.' } }, { audace: true }),
      o('provincia', 'Provincia', { soldi: +500, felicita: +2, rete: -4, relazioni: +3 }),
    ], { predefinita: 'provincia', quando: { settimanaMin: 40, livelloMax: 2 }, peso: 0.8 }),
  e('restare_o_cambiare', 'bivio', 'Restare o cambiare',
    'Sei qui da tre anni. Conosci tutti, sai tutto, e non succede più niente.',
    [
      o('resti', 'Resti', { noia: +8, felicita: -1, visibilita: +1 }),
      o('cerchi', 'Cominci a guardare fuori', { ricerca: +3, noia: -5 }, { audace: true }),
    ], { predefinita: 'resti', quando: { lavoro: 'vero', settimanaMin: 150, noiaMin: 20 }, peso: 1 }),
  e('master_serale', 'bivio', 'Un master serale',
    'Due anni, la sera. Costa quattromila euro e tutte le sere.',
    [
      o('fai', 'Lo fai', { soldi: -4000, tempo: -12, stress: +2, competenze: { finanza: +3, gestione_progetti: +2, diritto: +1 }, ritardo: { settimane: 100, effetti: { titolo: 'universita', reputazione: +3 }, testo: 'Il master è finito.' } }, { audace: true, richiede: { soldiMin: 4000 } }),
      o('no', 'No', {}),
    ], { quando: { lavoro: 'vero', titolo: false, settimanaMin: 80 }, peso: 0.8, background: { nessuna: 0.4 }, predefinita: 'no' }),
  e('contro_offerta', 'bivio', 'La controfferta',
    'Hai detto che te ne vai; il capo ti offre un aumento per restare.',
    [
      o('resti', 'Resti con l’aumento', { soldi: +1500, noia: +5, visibilita: +2, ritardo: { settimane: 26, effetti: { visibilita: -6 }, testo: 'Sei mesi dopo la controfferta: si ricordano che volevi andartene.' } }),
      o('vai', 'Vai comunque', { stress: -1, felicita: +1, ricerca: +2 }, { audace: true }),
    ], { predefinita: 'resti', quando: { lavoro: 'vero', offerte: true }, peso: 1.2, unaVolta: false,
      lezione: 'Le controfferte si accettano poco, nella vita reale: chi resta dopo aver detto «me ne vado» resta con un’etichetta addosso.' }),
  e('progetto_etico', 'bivio', 'Un progetto che non ti piace',
    'Il cliente vende una cosa che fa male alla gente. Il progetto è tuo.',
    [
      o('fai', 'Lo fai', { performance: +2, integrita: -3, felicita: -2 }),
      o('rifiuti', 'Ti rifiuti', { integrita: +3, visibilita: -3, reputazione: +1, stress: +1 }, { audace: true }),
      o('cambi', 'Chiedi di cambiare progetto', { competenze: { negoziazione: +2 }, visibilita: -1 }),
    ], { predefinita: 'fai', quando: { lavoro: 'vero', livelloMin: 1 }, peso: 0.8 }),
  e('part_time', 'bivio', 'Part-time',
    'Puoi chiedere un part-time: meno soldi, più vita.',
    [
      o('si', 'Sì', { soldi: -600, stress: -6, felicita: +4, relazioni: +3, visibilita: -3, tempo: +15 }),
      o('no', 'No', {}),
    ], { quando: { lavoro: 'vero', stressMin: 55, settimanaMin: 40 }, peso: 0.7 }),
  e('esposizione', 'bivio', 'Prendere posizione',
    'In riunione, il capo dice una cosa sbagliata. Tutti tacciono.',
    [
      o('parli', 'Parli', { visibilita: +3, reputazione: +2, stress: +2, sponsorFiducia: -3, competenze: { pensiero_critico: +1, comunicazione: +1 } }, { audace: true }),
      o('taci', 'Taci', { integrita: -1, stress: +1 }),
      o('dopo', 'Glielo dici dopo, in privato', { competenze: { intelligenza_politica: +2 }, reputazione: +1 }),
    ], { predefinita: 'taci', quando: { lavoro: 'vero' }, peso: 1, unaVolta: false }),
  e('mentore_o_lavoro', 'bivio', 'Il tempo del mentore',
    'Il tuo mentore ti propone di vedervi ogni settimana. È tempo tolto al lavoro.',
    [
      o('si', 'Sì', { tempo: -4, competenze: { leadership: +2, pensiero_critico: +2, intelligenza_politica: +1 } }),
      o('no', 'Non adesso', {}),
    ], { quando: { mentore: true }, peso: 1 }),
  e('bonus_o_tempo', 'bivio', 'Soldi o tempo',
    'L’azienda ti offre: un aumento, o una settimana in più di ferie.',
    [
      o('soldi', 'Soldi', { soldi: +1200 }),
      o('tempo', 'Tempo', { stress: -5, felicita: +3, salute: +2 }),
    ], { quando: { lavoro: 'vero', performanceMin: 70, settimanaMin: 60 }, peso: 0.8 }),
  e('rischio_cambio', 'bivio', 'Un salto nel vuoto',
    'Un’azienda piccola ti offre un ruolo più alto. Se cresce, cresci; se chiude, ricominci.',
    [
      o('salti', 'Salti', { offerta: 'bytefarm', ricerca: +1 }, { audace: true }),
      o('resti', 'Resti', {}),
    ], { predefinita: 'resti', quando: { lavoro: 'vero', livelloMin: 1, livelloMax: 3 }, peso: 0.7 }),
  e('alleato_promosso', 'bivio', 'Il tuo alleato è stato promosso',
    'Adesso sta sopra di te. Ti chiede di lavorare nel suo team.',
    [
      o('vai', 'Vai con lui', { visibilita: +4, sponsorFiducia: +5, performance: -2, competenze: { lavoro_di_squadra: +1 } }, { audace: true }),
      o('resti', 'Resti dove sei', {}),
    ], { predefinita: 'resti', quando: { lavoro: 'vero', alleato: true }, peso: 1 }),
  e('capo_tossico_bivio', 'bivio', 'Il capo tossico ti offre un aumento',
    'Dopo mesi di urla, un aumento. «Sei prezioso.» È il momento in cui molti restano.',
    [
      o('resti', 'Resti', { soldi: +1000, stress: +3, felicita: -2, integrita: 0 }),
      o('vai', 'Rifiuti e cerchi altro', { ricerca: +3, felicita: +2 }, { audace: true }),
    ], { predefinita: 'resti', quando: { capo: 'tossico', settimanaMin: 20 }, peso: 1.2,
      lezione: 'L’aumento dopo i maltrattamenti è il modo in cui un ambiente tossico ti tiene: si chiama «golden handcuffs», e funziona.' }),
  e('capo_eccellente_va', 'bivio', 'Il capo eccellente se ne va',
    'Ti chiede se vuoi seguirlo nella nuova azienda.',
    [
      o('segui', 'Lo segui', { offerta: 'kaleido', felicita: +2 }, { audace: true }),
      o('resti', 'Resti', { felicita: -2, visibilita: -3 }),
    ], { predefinita: 'resti', quando: { capo: 'capo_eccellente', settimanaMin: 60 }, peso: 0.8 }),
  e('formazione_o_ferie', 'bivio', 'Le ferie o il corso',
    'Hai dieci giorni. Un corso che ti servirebbe, o il mare.',
    [
      o('corso', 'Il corso', { competenze: { analisi_dati: +2, tecnologia: +2 }, stress: +1 }),
      o('mare', 'Il mare', { stress: -6, felicita: +4, salute: +1 }),
    ], { quando: { lavoro: true, settimanaMin: 30 }, peso: 0.8, unaVolta: false }),
  e('cambio_percorso', 'bivio', 'Lasciare gli studi',
    'Il lavoro ti prende tutto. L’università va avanti a rilento. Mollare, o resistere?',
    [
      o('molli', 'Molli', { stress: -4, felicita: +1, tempo: +10 }),
      o('resisti', 'Resisti', { stress: +3, sonno: +2, competenze: { resilienza: +2 } }, { audace: true }),
    ], { predefinita: 'molli', quando: { studia: true, lavoro: true, stressMin: 55 }, peso: 1 }),
  e('progetto_tuo', 'bivio', 'Un progetto tuo',
    'Hai un’idea. Tre mesi di sere per farla esistere.',
    [
      o('fai', 'La fai', { tempo: -10, portfolio: +4, felicita: +3, stress: +1, competenze: { creativita: +2, tecnologia: +1 } }, { audace: true }),
      o('no', 'Non adesso', { felicita: -1 }),
    ], { predefinita: 'no', quando: { settimanaMin: 20 }, peso: 0.8 }),
  e('sindacato_o_no', 'bivio', 'Il sindacato',
    'Ti chiedono di fare il rappresentante. Tuteli gli altri; l’azienda se lo segna.',
    [
      o('si', 'Sì', { integrita: +2, reputazione: +2, visibilita: -3, competenze: { negoziazione: +3, leadership: +2 }, tempo: -4 }, { audace: true }),
      o('no', 'No', {}),
    ], { predefinita: 'no', quando: { lavoro: 'vero', settimanaMin: 60, culturaMax: 6 }, peso: 0.6 }),
  e('trasferta_lunga', 'bivio', 'Sei mesi in trasferta',
    'Un progetto lontano. Diaria buona, vita sospesa.',
    [
      o('vai', 'Vai', { soldi: +4000, relazioni: -8, felicita: -2, visibilita: +5, competenze: { resilienza: +1, negoziazione: +1 } }, { audace: true }),
      o('no', 'No', { visibilita: -2 }),
    ], { predefinita: 'no', quando: { lavoro: 'vero', livelloMin: 2 }, peso: 0.7 }),
  e('lavoro_o_famiglia', 'bivio', 'La recita di tuo figlio',
    'È alle quattro. La riunione con il cliente pure.',
    [
      o('recita', 'La recita', { relazioni: +4, felicita: +3, visibilita: -2, performance: -1 }),
      o('riunione', 'La riunione', { relazioni: -5, felicita: -3, visibilita: +2 }),
    ], { quando: { settimanaMin: 200, relazioniMin: 50, lavoro: 'vero' }, peso: 0.8 }),
  e('delega', 'bivio', 'Delegare',
    'Hai tre persone. Potresti fare tutto tu, meglio, la notte.',
    [
      o('deleghi', 'Deleghi', { competenze: { leadership: +2, empatia: +1 }, performance: -1, stress: -2 }, { audace: true }),
      o('fai_tu', 'Fai tu', { performance: +2, stress: +4, sonno: +2, competenze: { leadership: -1 } }),
    ], { predefinita: 'fai_tu', quando: { lavoro: 'vero', livelloMin: 3 }, peso: 1 }),
  e('promozione_o_sanita', 'bivio', 'Il medico dice di rallentare',
    'La pressione, il sonno. E la promozione è a un passo.',
    [
      o('rallenti', 'Rallenti', { salute: +4, stress: -5, visibilita: -3, performance: -2 }),
      o('spingi', 'Spingi ancora tre mesi', { salute: -4, stress: +4, visibilita: +4 }),
    ], { quando: { lavoro: 'vero', saluteMax: 75, stressMin: 55 }, peso: 1.2 }),
  e('fondare', 'bivio', 'Mettersi in proprio davvero',
    'Lasciare tutto e fondare la tua. Chi ha una rete di sicurezza può fallire e ripartire; chi non ce l’ha, affonda.',
    [
      o('fondi', 'Fondi', { lavoro: 'perdi', soldi: -10000, stress: +4, competenze: { vendita: +3, finanza: +2, leadership: +2, negoziazione: +2 }, ritardo: { settimane: 78, effetti: { soldi: +30000, reputazione: +8, rete: +10, impresa: true }, testo: 'L’azienda ha retto: adesso vale qualcosa, e qualcuno l’ha notata.' } }, { audace: true, richiede: { soldiMin: 12000 } }),
      o('no', 'No', {}),
    ], { quando: { livelloMin: 4, settimanaMin: 200, reteMin: 40 }, peso: 0.3, background: { erede: 2, nessuna: 0.2 }, predefinita: 'no' }),
  e('achivia_compra', 'bivio', 'ACHIVIA vuole comprare la tua azienda',
    'Un’offerta che non si rifiuta, o forse sì. Vendere è la fine di una strada e l’inizio di un’altra.',
    [
      o('vendi', 'Vendi', { soldi: +250000, fine: 'impresa' }, { audace: true }),
      o('tieni', 'Tieni la tua azienda', { reputazione: +5, felicita: +3, stress: +2 }),
    ], { quando: { impresa: true }, peso: 1, predefinita: 'tieni',
      lezione: 'Fondare la propria azienda è la scorciatoia più rapida verso l’alto — quando riesce. Riesce di rado, e riesce molto più spesso a chi aveva un capitale con cui partire.' }),
  e('rientro', 'bivio', 'Tornare a casa',
    'Un’offerta nella tua città. Meno soldi, la famiglia a dieci minuti.',
    [
      o('torni', 'Torni', { soldi: -800, relazioni: +8, felicita: +4, rete: -3, ritardo: { settimane: 4, effetti: { soldi: -200 }, testo: 'Lo stipendio più basso.' } }),
      o('resti', 'Resti', { relazioni: -2 }),
    ], { quando: { settimanaMin: 150, relazioniMax: 85 }, peso: 0.6 }),
  e('visibilita_o_squadra', 'bivio', 'Il merito della squadra',
    'Il progetto è andato bene. Il capo chiede chi l’ha fatto. Puoi dire «io», o «noi».',
    [
      o('io', '«Io»', { visibilita: +4, integrita: -2, relazioni: -1, sospetto: +2 }),
      o('noi', '«Noi»', { visibilita: +1, integrita: +1, reputazione: +2, competenze: { leadership: +1 } }),
    ], { quando: { lavoro: 'vero', performanceMin: 65 }, peso: 1, unaVolta: false }),
  e('ferie_non_date', 'bivio', 'Le ferie negate',
    '«Non è il momento.» Erano prenotate da tre mesi.',
    [
      o('accetti', 'Accetti', { stress: +3, felicita: -3, relazioni: -2 }),
      o('insisti', 'Insisti, con il contratto in mano', { stress: +2, reputazione: -1, competenze: { negoziazione: +2 }, ritardo: { settimane: 2, effetti: { stress: -6, felicita: +3 }, testo: 'Le ferie, alla fine.' } }, { audace: true }),
    ], { predefinita: 'accetti', quando: { capo: 'tossico' }, peso: 1.2 }),
  e('secondo_figlio', 'bivio', 'Un altro',
    'Un altro figlio. Lo sai già cosa costa.',
    [
      o('si', 'Sì', { felicita: +6, relazioni: +4, tempo: -15, sonno: +3, soldi: -300, ritardo: { settimane: 4, effetti: { soldi: -300 }, testo: 'Il secondo bambino.' } }),
      o('no', 'No', { relazioni: -1 }),
    ], { quando: { settimanaMin: 300, relazioniMin: 60 }, peso: 0.5 }),
  e('pensione_genitori', 'bivio', 'I tuoi vanno in pensione',
    'Vogliono vederti di più. Hanno ragione.',
    [
      o('tempo', 'Fai spazio', { tempo: -4, relazioni: +4, felicita: +2 }),
      o('no', 'Non riesci', { relazioni: -3 }),
    ], { quando: { settimanaMin: 350 }, peso: 0.7 }),
  e('scelta_scuola', 'bivio', 'Che strada, davvero',
    'Sei anni dopo: la strada che hai preso ti ha portato qui. Puoi cambiarla ancora.',
    [
      o('resti', 'Vai avanti', { competenze: { resilienza: +1 } }),
      o('cambi', 'Cambi', { noia: -10, stress: +2, ricerca: +2 }, { audace: true }),
    ], { predefinita: 'resti', quando: { settimanaMin: 312 }, peso: 0.6 }),
];
