/**
 * English. Stessa forma delle altre lingue: alfabeto, gruppi, voci curate.
 *
 * Gli accenti non ci sono e non servono: le poche parole prese in prestito
 * che li portano (café, naïve) si giocano senza, ed e' quello che fa la
 * normalizzazione.
 */
export const en = {
  id: 'en', nome: 'English', locale: 'en-GB',
  tieniAccenti: false, digrammi: [], sostituzioni: {},
  alfabeto: [
    { lettera: 'E', peso: 127, valore: 1 }, { lettera: 'T', peso: 91, valore: 1 },
    { lettera: 'A', peso: 82, valore: 1 },  { lettera: 'O', peso: 75, valore: 1 },
    { lettera: 'I', peso: 70, valore: 1 },  { lettera: 'N', peso: 67, valore: 1 },
    { lettera: 'S', peso: 63, valore: 1 },  { lettera: 'H', peso: 61, valore: 2 },
    { lettera: 'R', peso: 60, valore: 1 },  { lettera: 'D', peso: 43, valore: 2 },
    { lettera: 'L', peso: 40, valore: 1 },  { lettera: 'C', peso: 28, valore: 2 },
    { lettera: 'U', peso: 28, valore: 1 },  { lettera: 'M', peso: 24, valore: 2 },
    { lettera: 'W', peso: 24, valore: 3 },  { lettera: 'F', peso: 22, valore: 3 },
    { lettera: 'G', peso: 20, valore: 3 },  { lettera: 'Y', peso: 20, valore: 3 },
    { lettera: 'P', peso: 19, valore: 2 },  { lettera: 'B', peso: 15, valore: 3 },
    { lettera: 'V', peso: 10, valore: 4 },  { lettera: 'K', peso: 8, valore: 4 },
    { lettera: 'J', peso: 4, valore: 7 },   { lettera: 'X', peso: 4, valore: 7 },
    { lettera: 'Q', peso: 3, valore: 8 },   { lettera: 'Z', peso: 3, valore: 8 },
  ],
  /**
   * Da una parola, le forme da cui potrebbe derivare: serve a tenere i
   * plurali fuori dalle parole segrete. DOGS viene da DOG, CITIES da CITY,
   * WOLVES da WOLF. La stessa regola prende anche le terze persone dei
   * verbi (RUNS da RUN), che di una parola segreta hanno lo stesso
   * difetto: non sono la parola, ne sono una forma.
   */
  formeBase: (p, categoria) => {
    const f = [];
    /* I comparativi solo fra gli aggettivi: RARER viene da RARE e non e'
       una parola da indovinare, ma WORKER viene da WORK ed e' un mestiere.
       Senza guardare la categoria la stessa regola butterebbe via anche
       quello, e sarebbe una parola buona persa per niente. */
    if (categoria === 'qualities') {
      if (p.endsWith('EST')) f.push(p.slice(0, -3), p.slice(0, -2));
      if (p.endsWith('ER')) f.push(p.slice(0, -2), p.slice(0, -1));
      /* WETTER viene da WET: la consonante raddoppiata prima della
         desinenza va tolta anche lei, se no la base non si trova. */
      const senza = p.replace(/(?:ER|EST)$/, '');
      if (senza.length > 2 && senza.at(-1) === senza.at(-2)) f.push(senza.slice(0, -1));
    }
    if (p.endsWith('IES')) f.push(p.slice(0, -3) + 'Y');
    if (p.endsWith('VES')) f.push(p.slice(0, -3) + 'F', p.slice(0, -3) + 'FE');
    if (p.endsWith('ES')) f.push(p.slice(0, -2));
    if (p.endsWith('S')) f.push(p.slice(0, -1));
    if (p.endsWith('ED')) f.push(p.slice(0, -2), p.slice(0, -1));
    if (p.endsWith('ING')) f.push(p.slice(0, -3), p.slice(0, -3) + 'E');
    return f;
  },

  categorie: {
    animals: 'Animals', food: 'Food', home: 'Home', nature: 'Nature', body: 'Body',
    work: 'Work', time: 'Time', colours: 'Colours', objects: 'Objects', actions: 'Actions',
    qualities: 'Qualities', places: 'Places', art: 'Art', materials: 'Materials',
    common: 'Common words', general: 'General',
  },
  gruppi: {
    animals: ['dog', 'dogs', 'cat', 'cats', 'mouse', 'mice', 'horse', 'horses', 'cow', 'cows',
      'sheep', 'goat', 'goats', 'pig', 'pigs', 'hen', 'hens', 'duck', 'ducks', 'fish',
      'bird', 'birds', 'eagle', 'eagles', 'owl', 'owls', 'crow', 'crows', 'wolf', 'wolves',
      'fox', 'foxes', 'bear', 'bears', 'deer', 'lion', 'lions', 'tiger', 'tigers', 'zebra',
      'zebras', 'whale', 'whales', 'shark', 'sharks', 'crab', 'crabs', 'snail', 'snails', 'spider',
      'spiders', 'ant', 'ants', 'bee', 'bees', 'moth', 'moths', 'frog', 'frogs', 'snake',
      'snakes', 'turtle', 'turtles', 'rabbit', 'rabbits', 'squirrel', 'badger', 'otter', 'otters', 'seal',
      'seals', 'swan', 'swans', 'hawk', 'hawks', 'puppy', 'kitten', 'lamb', 'lambs', 'calf',
      'foal', 'chick', 'chicks', 'donkey', 'mule', 'camel', 'camels', 'monkey', 'monkeys', 'ape',
      'apes', 'gorilla', 'elephant', 'giraffe', 'hippo', 'rhino', 'leopard', 'panther', 'cheetah', 'lynx',
      'moose', 'elk', 'bison', 'buffalo', 'goose', 'geese', 'turkey', 'pigeon', 'dove', 'doves',
      'sparrow', 'robin', 'raven', 'parrot', 'penguin', 'seagull', 'stork', 'heron', 'falcon', 'vulture',
      'bat', 'bats', 'rat', 'rats', 'hare', 'hares', 'mole', 'moles', 'hedgehog', 'beaver',
      'weasel', 'ferret', 'skunk', 'raccoon', 'possum', 'lizard', 'gecko', 'toad', 'toads', 'newt',
      'worm', 'worms', 'slug', 'slugs', 'beetle', 'beetles', 'wasp', 'wasps', 'fly', 'flies',
      'gnat', 'flea', 'fleas', 'tick', 'ticks', 'louse', 'cricket', 'locust', 'mantis', 'dragonfly',
      'butterfly', 'ladybug', 'octopus', 'squid', 'jellyfish', 'starfish', 'lobster', 'shrimp', 'prawn', 'oyster',
      'clam', 'clams', 'mussel', 'salmon', 'trout', 'tuna', 'eel', 'eels', 'cod', 'herring',
      'dolphin', 'seahorse', 'walrus', 'coral', 'sponge', 'nest', 'nests', 'egg', 'eggs', 'wing',
      'wings', 'tail', 'tails', 'paw', 'paws', 'claw', 'claws', 'fur', 'horn', 'horns',
      'hoof', 'beak', 'feather', 'fin', 'fins', 'scale', 'scales', 'shell', 'shells', 'herd',
      'flock', 'swarm', 'pack', 'pet', 'pets', 'cattle', 'poultry', 'creature', 'animal', 'animals'],
    food: ['bread', 'breads', 'rice', 'pasta', 'milk', 'butter', 'cheese', 'meat', 'salt', 'pepper',
      'sugar', 'honey', 'apple', 'apples', 'pear', 'pears', 'plum', 'plums', 'grape', 'grapes',
      'lemon', 'lemons', 'orange', 'oranges', 'peach', 'peaches', 'berry', 'berries', 'melon', 'melons',
      'potato', 'carrot', 'carrots', 'onion', 'onions', 'garlic', 'bean', 'beans', 'pea', 'peas',
      'salad', 'salads', 'soup', 'soups', 'cake', 'cakes', 'pie', 'pies', 'biscuit', 'jam',
      'sauce', 'sauces', 'oil', 'oils', 'flour', 'water', 'wine', 'wines', 'juice', 'beer',
      'coffee', 'tea', 'cream', 'yogurt', 'toast', 'sandwich', 'pizza', 'burger', 'chips', 'fries',
      'noodle', 'noodles', 'cereal', 'oats', 'wheat', 'barley', 'corn', 'bacon', 'ham', 'sausage',
      'steak', 'chicken', 'beef', 'pork', 'seafood', 'stew', 'roast', 'gravy', 'spice', 'spices',
      'herb', 'herbs', 'basil', 'mint', 'ginger', 'cinnamon', 'vanilla', 'nutmeg', 'chili', 'curry',
      'vinegar', 'mustard', 'ketchup', 'pickle', 'olive', 'olives', 'nut', 'nuts', 'almond', 'walnut',
      'peanut', 'cashew', 'raisin', 'date', 'dates', 'fig', 'figs', 'cherry', 'banana', 'mango',
      'papaya', 'coconut', 'pumpkin', 'squash', 'cabbage', 'lettuce', 'spinach', 'celery', 'radish', 'turnip',
      'beet', 'leek', 'leeks', 'tomato', 'cucumber', 'mushroom', 'breakfast', 'lunch', 'dinner', 'supper',
      'snack', 'snacks', 'meal', 'meals', 'dish', 'dishes', 'recipe', 'recipes', 'flavour', 'flavor',
      'taste', 'tastes', 'smell', 'hunger', 'thirst', 'feast', 'dessert', 'pudding', 'candy', 'sweets',
      'chocolate', 'biscuits', 'pastry', 'muffin', 'donut', 'pancake', 'waffle', 'syrup', 'jelly', 'custard',
      'sorbet', 'crust', 'crumb', 'crumbs', 'dough', 'yeast'],
    home: ['house', 'houses', 'door', 'doors', 'wall', 'walls', 'roof', 'roofs', 'floor', 'floors',
      'room', 'rooms', 'kitchen', 'bath', 'bed', 'beds', 'chair', 'chairs', 'table', 'tables',
      'sofa', 'sofas', 'lamp', 'lamps', 'window', 'windows', 'key', 'keys', 'carpet', 'carpets',
      'mirror', 'mirrors', 'shelf', 'shelves', 'drawer', 'drawers', 'curtain', 'curtains', 'pillow', 'pillows',
      'blanket', 'plate', 'plates', 'glass', 'glasses', 'fork', 'forks', 'knife', 'knives', 'spoon',
      'spoons', 'pot', 'pots', 'oven', 'ovens', 'sink', 'sinks', 'ceiling', 'stairs', 'attic',
      'cellar', 'garage', 'garden', 'gardens', 'balcony', 'porch', 'hall', 'halls', 'closet', 'cupboard',
      'wardrobe', 'bedroom', 'bathroom', 'basement', 'fireplace', 'chimney', 'stove', 'fridge', 'freezer', 'kettle',
      'toaster', 'blender', 'cup', 'cups', 'mug', 'mugs', 'bowl', 'bowls', 'tray', 'trays',
      'jug', 'jugs', 'bottle', 'bottles', 'jar', 'jars', 'lid', 'lids', 'towel', 'towels',
      'soap', 'broom', 'brooms', 'bucket', 'buckets', 'mop', 'mops', 'brush', 'brushes', 'comb',
      'combs', 'razor', 'mattress', 'sheet', 'sheets', 'quilt', 'duvet', 'rug', 'rugs', 'clock',
      'clocks', 'vase', 'vases', 'frame', 'frames', 'picture', 'candle', 'candles', 'switch', 'socket',
      'plug', 'plugs', 'wire', 'wires', 'pipe', 'pipes', 'tap', 'taps', 'faucet', 'handle',
      'handles', 'lock', 'locks', 'hinge', 'hinges', 'step', 'steps', 'gate', 'gates'],
    nature: ['tree', 'trees', 'leaf', 'leaves', 'flower', 'flowers', 'root', 'roots', 'branch', 'branches',
      'grass', 'field', 'fields', 'wood', 'woods', 'hill', 'hills', 'valley', 'valleys', 'river',
      'rivers', 'lake', 'lakes', 'sea', 'seas', 'wave', 'waves', 'sand', 'rock', 'rocks',
      'stone', 'stones', 'earth', 'sky', 'skies', 'sun', 'moon', 'moons', 'star', 'stars',
      'cloud', 'clouds', 'rain', 'snow', 'wind', 'winds', 'fog', 'thunder', 'ice', 'island',
      'islands', 'desert', 'deserts', 'cave', 'caves', 'plain', 'plains', 'spring', 'springs', 'fall',
      'seed', 'seeds', 'fruit', 'fruits', 'thorn', 'thorns', 'trunk', 'bark', 'bud', 'buds',
      'petal', 'petals', 'pollen', 'rose', 'roses', 'lily', 'lilies', 'tulip', 'daisy', 'poppy',
      'orchid', 'fern', 'ferns', 'moss', 'reed', 'reeds', 'bush', 'bushes', 'hedge', 'shrub',
      'oak', 'oaks', 'pine', 'pines', 'fir', 'birch', 'willow', 'maple', 'elm', 'beech',
      'palm', 'palms', 'cedar', 'vine', 'vines', 'mud', 'dust', 'ash', 'ashes', 'smoke',
      'flame', 'flames', 'fire', 'fires', 'ember', 'spark', 'sparks', 'dew', 'frost', 'hail',
      'storm', 'storms', 'gale', 'breeze', 'flood', 'floods', 'drought', 'tide', 'tides', 'current',
      'shore', 'shores', 'beach', 'cliff', 'cliffs', 'reef', 'bay', 'bays', 'gulf', 'strait',
      'channel', 'stream', 'brook', 'pond', 'ponds', 'marsh', 'swamp', 'oasis', 'dune', 'glacier',
      'summit', 'peak', 'peaks', 'ridge', 'slope', 'canyon', 'gorge', 'path', 'paths'],
    body: ['head', 'heads', 'eye', 'eyes', 'nose', 'noses', 'mouth', 'mouths', 'ear', 'ears',
      'hand', 'hands', 'finger', 'fingers', 'arm', 'arms', 'leg', 'legs', 'foot', 'feet',
      'heart', 'hearts', 'blood', 'bone', 'bones', 'skin', 'hair', 'tooth', 'teeth', 'tongue',
      'shoulder', 'back', 'knee', 'knees', 'elbow', 'elbows', 'lip', 'lips', 'nail', 'nails',
      'wrist', 'wrists', 'neck', 'necks', 'face', 'faces', 'chin', 'chins', 'chest', 'nerve',
      'nerves', 'muscle', 'muscles', 'vein', 'veins', 'lung', 'lungs', 'liver', 'stomach', 'kidney',
      'brain', 'brains', 'skull', 'cheek', 'cheeks', 'brow', 'lash', 'lashes', 'eyelid', 'pupil',
      'throat', 'hip', 'hips', 'thigh', 'thighs', 'ankle', 'ankles', 'heel', 'heels', 'toe',
      'toes', 'thumb', 'thumbs', 'knuckle', 'rib', 'ribs', 'spine', 'waist', 'sweat', 'tear',
      'tears', 'breath', 'pulse', 'voice', 'voices', 'gaze', 'smile', 'smiles'],
    actions: ['make', 'makes', 'made', 'making', 'say', 'says', 'said', 'goes', 'went', 'gone',
      'come', 'comes', 'came', 'stay', 'stays', 'stayed', 'give', 'gives', 'gave', 'given',
      'see', 'sees', 'saw', 'seen', 'know', 'knows', 'knew', 'known', 'want', 'wants',
      'wanted', 'can', 'could', 'must', 'shall', 'should', 'would', 'speak', 'speaks', 'spoke',
      'spoken', 'hear', 'hears', 'heard', 'look', 'looks', 'looked', 'think', 'thinks', 'thought',
      'believe', 'believes', 'understand', 'read', 'reads', 'write', 'writes', 'wrote', 'written', 'count',
      'counts', 'counted', 'run', 'runs', 'ran', 'running', 'jump', 'jumps', 'jumped', 'swim',
      'swims', 'swam', 'flew', 'flown', 'falls', 'fell', 'fallen', 'rise', 'rises', 'risen',
      'climb', 'climbs', 'sank', 'open', 'opens', 'opened', 'close', 'closes', 'closed', 'take',
      'takes', 'took', 'taken', 'leave', 'left', 'carry', 'carries', 'carried', 'put', 'puts',
      'remove', 'turn', 'turns', 'turned', 'return', 'returns', 'depart', 'remain', 'remains', 'search',
      'find', 'finds', 'found', 'lose', 'loses', 'lost', 'win', 'wins', 'won', 'play',
      'plays', 'played', 'work', 'works', 'worked', 'sleep', 'sleeps', 'slept', 'eat', 'eats',
      'ate', 'eaten', 'drink', 'drinks', 'drank', 'drunk', 'laugh', 'laughs', 'cry', 'cries',
      'cried', 'sing', 'sings', 'sang', 'sung', 'dance', 'dances', 'danced', 'build', 'builds',
      'built', 'break', 'breaks', 'broke', 'broken', 'clean', 'cleans', 'cleaned', 'wash', 'washes',
      'washed', 'cook', 'cooks', 'cooked', 'help', 'helps', 'helped', 'explain', 'learn', 'learns',
      'learned', 'teach', 'teaches', 'taught', 'grow', 'grows', 'grew', 'grown', 'choose', 'chooses',
      'chose', 'chosen', 'buy', 'buys', 'bought', 'sell', 'sells', 'sold', 'pay', 'pays',
      'paid', 'send', 'sends', 'sent', 'bring', 'brings', 'brought', 'keep', 'keeps', 'kept',
      'hold', 'holds', 'held', 'pull', 'pulls', 'pulled', 'push', 'pushes', 'pushed', 'throw',
      'throws', 'threw', 'catch', 'catches', 'caught', 'hide', 'hides', 'hid', 'hidden', 'show',
      'shows', 'showed', 'try', 'tries', 'tried', 'use', 'uses', 'used', 'ask', 'asks',
      'asked', 'answer', 'answers', 'call', 'calls', 'called', 'meet', 'meets', 'met', 'love',
      'loves', 'loved', 'hate', 'hates', 'hated', 'hope', 'hopes', 'hoped', 'fear', 'fears',
      'feared', 'wait', 'waits', 'waited', 'live', 'lives', 'lived', 'die', 'dies', 'died',
      'born', 'begin', 'begins', 'began', 'begun', 'start', 'starts', 'ended', 'finish', 'stop',
      'stops', 'stopped', 'follow', 'follows', 'touch', 'touches', 'feel', 'feels', 'felt', 'walk',
      'walks', 'walked', 'ride', 'rides', 'rode', 'drive', 'drives', 'drove', 'driven', 'travel',
      'move', 'moves', 'moved', 'change', 'changes', 'cut', 'cuts', 'draw', 'draws', 'drew',
      'drawn', 'paint', 'paints', 'wear', 'wears', 'wore', 'worn', 'shut', 'shuts', 'sit',
      'sits', 'sat', 'stand', 'stands', 'stood', 'lie', 'lies', 'lay', 'lain', 'wake',
      'wakes', 'woke', 'dream', 'dreams', 'smiled', 'shout', 'shouts', 'whisper', 'listen', 'watch',
      'watches'],
    qualities: ['big', 'bigger', 'small', 'smaller', 'tall', 'taller', 'short', 'shorter', 'long', 'longer',
      'wide', 'wider', 'narrow', 'new', 'newer', 'old', 'older', 'young', 'younger', 'strong',
      'stronger', 'weak', 'weaker', 'hot', 'hotter', 'cold', 'colder', 'dry', 'drier', 'wet',
      'wetter', 'full', 'fuller', 'empty', 'heavy', 'light', 'lighter', 'hard', 'harder', 'soft',
      'softer', 'smooth', 'rough', 'clear', 'clearer', 'dark', 'darker', 'fast', 'faster', 'slow',
      'slower', 'easy', 'easier', 'right', 'wrong', 'rich', 'richer', 'poor', 'poorer', 'happy',
      'happier', 'sad', 'sadder', 'calm', 'calmer', 'good', 'better', 'best', 'bad', 'worse',
      'worst', 'sweet', 'bitter', 'salty', 'fresh', 'dirty', 'cleaner', 'rare', 'rarer', 'common',
      'brave', 'braver', 'kind', 'kinder', 'wise', 'wiser', 'free', 'freer', 'true', 'truer',
      'false', 'sure', 'safe', 'safer', 'quiet', 'loud', 'louder', 'bright', 'dull', 'sharp',
      'sharper', 'blunt', 'thick', 'thicker', 'thin', 'thinner', 'deep', 'deeper', 'shallow', 'flat',
      'flatter', 'round', 'square', 'straight', 'curved', 'crooked', 'even', 'odd', 'lucky', 'unlucky',
      'busy', 'busier', 'lazy', 'lazier', 'clever', 'silly', 'funny', 'funnier', 'serious', 'strange',
      'normal', 'usual', 'unusual', 'simple', 'complex', 'famous', 'unknown', 'modern', 'ancient', 'early',
      'earlier', 'late', 'later', 'whole', 'perfect', 'useful', 'useless', 'pretty', 'ugly', 'lovely',
      'gentle', 'harsh', 'polite', 'rude', 'proud', 'humble', 'honest', 'tired', 'awake', 'asleep',
      'alive', 'dead', 'sick', 'healthy', 'hungry', 'thirsty', 'ready'],
    time: ['hour', 'hours', 'day', 'days', 'night', 'nights', 'month', 'months', 'year', 'years',
      'moment', 'moments', 'minute', 'minutes', 'second', 'seconds', 'week', 'weeks', 'morning', 'evening',
      'noon', 'dawn', 'dusk', 'sunset', 'sunrise', 'season', 'seasons', 'summer', 'winter', 'autumn',
      'today', 'tomorrow', 'yesterday', 'soon', 'delay', 'past', 'future', 'present', 'monday', 'tuesday',
      'friday', 'sunday', 'january', 'february', 'march', 'april', 'june', 'july', 'august', 'october',
      'november', 'december', 'calendar', 'century', 'decade', 'age', 'ages', 'era', 'period', 'periods',
      'while', 'always', 'never', 'often', 'rarely', 'now', 'then', 'when', 'before', 'after',
      'during', 'until', 'since', 'daily', 'weekly', 'monthly', 'yearly', 'holiday', 'weekend', 'birthday',
      'deadline', 'schedule', 'timer'],
    colours: ['red', 'green', 'blue', 'yellow', 'black', 'white', 'grey', 'gray', 'pink', 'purple',
      'brown', 'gold', 'golden', 'silver', 'beige', 'ivory', 'violet', 'indigo', 'crimson', 'scarlet',
      'maroon', 'navy', 'teal', 'turquoise', 'lime', 'amber', 'lilac', 'lavender', 'tan', 'bronze',
      'copper', 'rusty', 'pale', 'paler', 'dim', 'colour', 'colours', 'color', 'colors', 'shade',
      'shades', 'tint', 'hue', 'hues'],
    objects: ['book', 'books', 'pen', 'pens', 'paper', 'papers', 'notebook', 'bag', 'bags', 'box',
      'boxes', 'rope', 'ropes', 'hammer', 'hammers', 'needle', 'needles', 'thread', 'button', 'buttons',
      'umbrella', 'suitcase', 'backpack', 'hat', 'hats', 'shoe', 'shoes', 'glove', 'gloves', 'scarf',
      'ring', 'rings', 'chain', 'chains', 'wheel', 'wheels', 'engine', 'engines', 'boat', 'boats',
      'ship', 'ships', 'train', 'trains', 'plane', 'planes', 'car', 'cars', 'bike', 'bikes',
      'bridge', 'bridges', 'road', 'roads', 'fence', 'fences', 'lantern', 'pencil', 'pencils', 'ruler',
      'rulers', 'eraser', 'scissors', 'glue', 'tape', 'string', 'strings', 'sack', 'sacks', 'basket',
      'baskets', 'crate', 'chests', 'cover', 'covers', 'cap', 'caps', 'screw', 'screws', 'bolt',
      'bolts', 'pliers', 'saws', 'axe', 'axes', 'shovel', 'spade', 'rake', 'hoe', 'ladder',
      'ladders', 'cart', 'carts', 'sledge', 'oar', 'oars', 'sail', 'sails', 'anchor', 'compass',
      'map', 'maps', 'chart', 'charts', 'lens', 'lenses', 'camera', 'cameras', 'phone', 'phones',
      'radio', 'screen', 'screens', 'keyboard', 'cable', 'cables', 'battery', 'torch', 'coin', 'coins',
      'money', 'wallet', 'purse', 'ticket', 'tickets', 'stamp', 'stamps', 'letter', 'letters', 'parcel',
      'package', 'card', 'cards', 'poster', 'posters', 'flag', 'flags', 'toy', 'toys', 'doll',
      'dolls', 'ball', 'balls', 'kite', 'kites', 'dice', 'puzzle', 'puzzles', 'whistle'],
    places: ['city', 'cities', 'town', 'towns', 'street', 'streets', 'squares', 'park', 'parks', 'school',
      'schools', 'church', 'museum', 'museums', 'theatre', 'theater', 'market', 'markets', 'shop', 'shops',
      'store', 'stores', 'bank', 'banks', 'station', 'stations', 'port', 'ports', 'airport', 'hospital',
      'hotel', 'hotels', 'library', 'castle', 'castles', 'tower', 'towers', 'yard', 'yards', 'farm',
      'farms', 'village', 'villages', 'district', 'border', 'borders', 'country', 'region', 'regions', 'county',
      'capital', 'suburb', 'lane', 'lanes', 'alley', 'avenue', 'corner', 'corners', 'bench', 'benches',
      'fountain', 'statue', 'statues', 'cinema', 'stadium', 'arena', 'circus', 'fair', 'inn', 'inns',
      'pub', 'pubs', 'cafe', 'bakery', 'pharmacy', 'butcher', 'grocery', 'workshop', 'factory', 'mill',
      'mills', 'mine', 'mines', 'quarry', 'harbour', 'harbor', 'dock', 'docks', 'shelter', 'cabin',
      'cabins', 'hut', 'huts', 'tent', 'tents', 'camp', 'camps', 'palace', 'mansion', 'cottage',
      'flats', 'building', 'office', 'offices', 'gallery', 'temple', 'chapel', 'abbey', 'ruins', 'tunnel',
      'tunnels', 'crossing', 'junction', 'runway', 'platform'],
    work: ['team', 'teams', 'project', 'projects', 'task', 'tasks', 'meeting', 'meetings', 'contract', 'salary',
      'wage', 'wages', 'client', 'clients', 'invoice', 'agenda', 'goal', 'goals', 'result', 'results',
      'report', 'reports', 'document', 'signature', 'deal', 'deals', 'company', 'trade', 'trades', 'shift',
      'shifts', 'career', 'role', 'roles', 'merit', 'reward', 'rewards', 'training', 'staff', 'boss',
      'bosses', 'manager', 'worker', 'workers', 'employee', 'employer', 'colleague', 'partner', 'partners', 'owner',
      'owners', 'customer', 'supplier', 'budget', 'profit', 'profits', 'loss', 'losses', 'cost', 'costs',
      'price', 'prices', 'discount', 'debt', 'debts', 'credit', 'account', 'accounts', 'balance', 'payment',
      'receipt', 'form', 'forms', 'file', 'files', 'folder', 'archive', 'desk', 'desks', 'printer',
      'message', 'messages', 'email', 'notice', 'doctor', 'nurse', 'teacher', 'lawyer', 'judge', 'soldier',
      'sailor', 'pilot', 'driver', 'waiter', 'baker', 'tailor', 'farmer', 'fisher', 'miner', 'builder',
      'plumber', 'painter', 'engineer', 'artist', 'writer', 'singer', 'dancer', 'actor', 'actress', 'guard',
      'guards', 'clerk'],
    art: ['art', 'arts', 'music', 'song', 'songs', 'painting', 'canvas', 'poem', 'poems', 'novel',
      'novels', 'story', 'stories', 'film', 'films', 'movie', 'movies', 'scene', 'scenes', 'rhythm',
      'note', 'notes', 'chord', 'chords', 'guitar', 'guitars', 'piano', 'pianos', 'violin', 'flute',
      'flutes', 'drum', 'drums', 'choir', 'melody', 'drawing', 'sketch', 'exhibit', 'author', 'poet',
      'poets', 'reader', 'chapter', 'page', 'pages', 'title', 'titles', 'plot', 'plots', 'ending',
      'comedy', 'tragedy', 'drama', 'stage', 'stages', 'script', 'scripts', 'concert', 'band', 'bands',
      'opera', 'ballet', 'costume', 'mask', 'masks', 'sound', 'sounds', 'silence', 'echo', 'echoes',
      'tune'],
    materials: ['iron', 'steel', 'plastic', 'cloth', 'wool', 'silk', 'cotton', 'leather', 'marble', 'granite',
      'cement', 'wax', 'rubber', 'quartz', 'diamond', 'lead', 'zinc', 'crystal', 'clay', 'cork',
      'linen', 'velvet', 'lace', 'metal', 'metals', 'alloy', 'tin', 'nickel', 'brass', 'concrete',
      'brick', 'bricks', 'tile', 'tiles', 'gravel', 'asphalt', 'resin', 'varnish', 'fibre', 'fiber',
      'fabric'],
    general: ['thing', 'things', 'way', 'ways', 'part', 'parts', 'point', 'points', 'sign', 'signs',
      'name', 'names', 'number', 'numbers', 'word', 'words', 'phrase', 'idea', 'ideas', 'memory',
      'doubt', 'doubts', 'choice', 'choices', 'rule', 'rules', 'order', 'orders', 'case', 'cases',
      'luck', 'fate', 'end', 'ends', 'centre', 'center', 'side', 'sides', 'bottom', 'top',
      'tops', 'edge', 'edges', 'line', 'lines', 'circle', 'circles', 'shape', 'shapes', 'size',
      'sizes', 'weight', 'height', 'width', 'length', 'depth', 'space', 'spaces', 'truth', 'error',
      'errors', 'fault', 'faults', 'reason', 'reasons', 'cause', 'causes', 'effect', 'effects', 'example',
      'proof', 'question', 'problem', 'problems', 'solution', 'method', 'methods', 'system', 'systems', 'plan',
      'plans', 'advice', 'news', 'speech', 'talk', 'talks', 'noise', 'noises', 'secret', 'secrets',
      'mystery', 'surprise', 'joke', 'jokes', 'game', 'games', 'gift', 'gifts', 'favour', 'thanks',
      'apology', 'greeting', 'invite', 'visit', 'visits', 'journey', 'trip', 'trips', 'arrival', 'trace',
      'traces', 'force', 'forces', 'power', 'powers', 'rights', 'duty', 'duties', 'law', 'laws',
      'peace', 'war', 'wars', 'fight', 'fights', 'victory', 'defeat', 'promise', 'trust', 'courage',
      'joy', 'sorrow', 'pain', 'anger', 'wish', 'wishes', 'need', 'needs', 'chance', 'risk'],
    common: ['the', 'and', 'but', 'not', 'for', 'with', 'from', 'into', 'over', 'under',
      'above', 'below', 'near', 'far', 'here', 'there', 'this', 'that', 'these', 'those',
      'who', 'what', 'which', 'where', 'why', 'how', 'some', 'any', 'many', 'much',
      'more', 'most', 'less', 'least', 'few', 'all', 'none', 'both', 'each', 'every',
      'other', 'others', 'same', 'such', 'own', 'very', 'too', 'also', 'again', 'once',
      'twice', 'yes', 'yet', 'still', 'just', 'only', 'well', 'ever', 'else', 'she',
      'her', 'his', 'him', 'its', 'our', 'ours', 'their', 'them', 'you', 'your',
      'yours', 'they', 'was', 'were', 'been', 'being', 'have', 'has', 'had', 'having',
      'does', 'did', 'done', 'will', 'may', 'might', 'please', 'hello', 'goodbye', 'sorry',
      'thank', 'welcome', 'maybe', 'perhaps', 'because', 'though', 'unless'],
  },
  parole: [
    { word: 'honeyed', category: 'qualities', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Sweet to the ear, often to the point of seeming insincere.',
      translations: { it: 'mellifluo', fr: 'mielleux', es: 'meloso', de: 'honigsüß' } },
    { word: 'quartz', category: 'materials', grammaticalType: 'noun', difficulty: 2, rarity: 3,
      definition: 'A very hard, clear mineral, one of the commonest in the earth’s crust.',
      translations: { it: 'quarzo', fr: 'quartz', es: 'cuarzo', de: 'Quarz' } },
    { word: 'zephyr', category: 'nature', grammaticalType: 'noun', difficulty: 3, rarity: 4,
      definition: 'A soft, gentle breeze from the west.',
      translations: { it: 'zefiro', fr: 'zéphyr', es: 'céfiro', de: 'Zephir' } },
    { word: 'twilight', category: 'time', grammaticalType: 'noun', difficulty: 2, rarity: 3,
      definition: 'The dim light between sunset and night, or between night and dawn.',
      translations: { it: 'crepuscolo', fr: 'crépuscule', es: 'crepúsculo', de: 'Dämmerung' } },
    { word: 'ubiquitous', category: 'qualities', grammaticalType: 'adjective', difficulty: 4, rarity: 4,
      definition: 'Seeming to be everywhere at the same time.',
      translations: { it: 'ubiquo', fr: 'ubiquiste', es: 'ubicuo', de: 'allgegenwärtig' } },
    { word: 'terse', category: 'qualities', grammaticalType: 'adjective', difficulty: 3, rarity: 3,
      definition: 'Using very few words, and sounding final because of it.',
      translations: { it: 'lapidario', fr: 'laconique', es: 'lacónico', de: 'knapp' } },
    { word: 'ephemeral', category: 'qualities', grammaticalType: 'adjective', difficulty: 4, rarity: 4,
      definition: 'Lasting a very short time.',
      translations: { it: 'effimero', fr: 'éphémère', es: 'efímero', de: 'flüchtig' } },
    { word: 'shrewd', category: 'qualities', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Quick to understand, and good at judging what will happen.',
      translations: { it: 'sagace', fr: 'sagace', es: 'sagaz', de: 'scharfsinnig' } },
    { word: 'meander', category: 'nature', grammaticalType: 'noun', difficulty: 3, rarity: 3,
      definition: 'A wide bend in a river; by extension, a winding course.',
      translations: { it: 'meandro', fr: 'méandre', es: 'meandro', de: 'Mäander' } },
    { word: 'zenith', category: 'nature', grammaticalType: 'noun', difficulty: 3, rarity: 4,
      definition: 'The point of the sky directly overhead.',
      translations: { it: 'zenit', fr: 'zénith', es: 'cenit', de: 'Zenit' } },
    { word: 'quiver', category: 'actions', grammaticalType: 'verb', difficulty: 3, rarity: 3,
      definition: 'To shake with a slight, rapid movement.',
      translations: { it: 'tremare', fr: 'frémir', es: 'temblar', de: 'zittern' } },
    { word: 'jovial', category: 'qualities', grammaticalType: 'adjective', difficulty: 3, rarity: 3,
      definition: 'Cheerful and friendly in manner.',
      translations: { it: 'gioviale', fr: 'jovial', es: 'jovial', de: 'jovial' } },
    { word: 'lucid', category: 'qualities', grammaticalType: 'adjective', difficulty: 3, rarity: 3,
      definition: 'Clear and easy to follow; of a mind, thinking clearly.',
      translations: { it: 'lucido', fr: 'lucide', es: 'lúcido', de: 'klar' } },
    { word: 'tenacious', category: 'qualities', grammaticalType: 'adjective', difficulty: 4, rarity: 4,
      definition: 'Holding on firmly, and not giving up easily.',
      translations: { it: 'tenace', fr: 'tenace', es: 'tenaz', de: 'hartnäckig' } },
    { word: 'magpie', category: 'animals', grammaticalType: 'noun', difficulty: 2, rarity: 3,
      definition: 'A black and white bird known for collecting shiny things.',
      translations: { it: 'gazza', fr: 'pie', es: 'urraca', de: 'Elster' } },
  ],
};
