/**
 * Español.
 *
 * Gli accenti si tolgono (CANCIÓN si gioca con la O), e la Ñ segue la
 * stessa strada: sul campo esce una N. In un gioco di tessere una lettera
 * in piu' che compare una volta su cento vuol dire un campo che quasi mai
 * la offre e una parola che quasi mai si puo' fare — meglio una N, e la
 * parola resta giocabile.
 */
export const es = {
  id: 'es', nome: 'Español', locale: 'es-ES',
  tieniAccenti: false, digrammi: [], sostituzioni: {},
  alfabeto: [
    { lettera: 'E', peso: 137, valore: 1 }, { lettera: 'A', peso: 125, valore: 1 },
    { lettera: 'O', peso: 87, valore: 1 },  { lettera: 'S', peso: 80, valore: 1 },
    { lettera: 'R', peso: 69, valore: 1 },  { lettera: 'N', peso: 67, valore: 1 },
    { lettera: 'I', peso: 63, valore: 1 },  { lettera: 'D', peso: 59, valore: 2 },
    { lettera: 'L', peso: 50, valore: 1 },  { lettera: 'C', peso: 47, valore: 2 },
    { lettera: 'T', peso: 46, valore: 1 },  { lettera: 'U', peso: 39, valore: 1 },
    { lettera: 'M', peso: 32, valore: 2 },  { lettera: 'P', peso: 25, valore: 2 },
    { lettera: 'B', peso: 14, valore: 3 },  { lettera: 'G', peso: 10, valore: 3 },
    { lettera: 'V', peso: 11, valore: 3 },  { lettera: 'Y', peso: 9, valore: 3 },
    { lettera: 'Q', peso: 9, valore: 4 },   { lettera: 'H', peso: 7, valore: 4 },
    { lettera: 'F', peso: 7, valore: 4 },   { lettera: 'Z', peso: 5, valore: 5 },
    { lettera: 'J', peso: 5, valore: 6 },   { lettera: 'X', peso: 2, valore: 8 },
    { lettera: 'K', peso: 1, valore: 8 },   { lettera: 'W', peso: 1, valore: 8 },
  ],
  /**
   * Da una parola, le forme da cui potrebbe derivare: serve a tenere i
   * plurali fuori dalle parole segrete. PERROS viene da PERRO, ARBOLES da
   * ARBOL, PECES da PEZ.
   */
  formeBase: (p) => {
    const f = [];
    if (p.endsWith('CES')) f.push(p.slice(0, -3) + 'Z');
    if (p.endsWith('ES')) f.push(p.slice(0, -2));
    if (p.endsWith('S')) f.push(p.slice(0, -1));
    return f;
  },

  /* Dalla categoria dei verbi si fa indovinare solo l'infinito. */
  verbi: { categoria: 'acciones', infinito: /(AR|ER|IR)$/ },

  categorie: {
    animales: 'Animales', comida: 'Comida', casa: 'Casa', naturaleza: 'Naturaleza', cuerpo: 'Cuerpo',
    trabajo: 'Trabajo', tiempo: 'Tiempo', colores: 'Colores', objetos: 'Objetos', acciones: 'Acciones',
    cualidades: 'Cualidades', lugares: 'Lugares', artes: 'Artes', materiales: 'Materiales', comunes: 'Palabras comunes', general: 'General',
  },
  gruppi: {
    animales: ['perro', 'perros', 'perra', 'gato', 'gatos', 'gata', 'gatas', 'raton', 'ratones', 'caballo',
      'caballos', 'yegua', 'vaca', 'vacas', 'toro', 'toros', 'oveja', 'ovejas', 'cabra', 'cabras',
      'cerdo', 'cerdos', 'gallina', 'gallinas', 'gallo', 'gallos', 'pato', 'patos', 'pez', 'peces',
      'pajaro', 'pajaros', 'aguila', 'aguilas', 'buho', 'buhos', 'cuervo', 'cuervos', 'lobo', 'lobos',
      'zorro', 'zorros', 'oso', 'osos', 'ciervo', 'ciervos', 'leon', 'leones', 'tigre', 'tigres',
      'cebra', 'cebras', 'ballena', 'tiburon', 'cangrejo', 'caracol', 'arana', 'aranas', 'hormiga', 'hormigas',
      'abeja', 'abejas', 'mariposa', 'rana', 'ranas', 'serpiente', 'tortuga', 'conejo', 'conejos', 'ardilla',
      'ardillas', 'cisne', 'cisnes', 'halcon', 'mirlo', 'urraca', 'foca', 'focas', 'paloma', 'palomas',
      'gorrion', 'loro', 'loros', 'pinguino', 'gaviota', 'cigueena', 'garza', 'buitre', 'murcielago', 'topo',
      'topos', 'erizo', 'castor', 'nutria', 'comadreja', 'lagarto', 'lagartija', 'sapo', 'sapos', 'gusano',
      'gusanos', 'babosa', 'escarabajo', 'avispa', 'avispas', 'mosca', 'moscas', 'mosquito', 'pulga', 'pulgas',
      'grillo', 'grillos', 'chicharra', 'libelula', 'pulpo', 'calamar', 'medusa', 'langosta', 'gamba', 'gambas',
      'ostra', 'ostras', 'mejillon', 'salmon', 'trucha', 'atun', 'anguila', 'bacalao', 'delfin', 'delfines',
      'nido', 'nidos', 'huevo', 'huevos', 'ala', 'alas', 'cola', 'colas', 'pata', 'patas',
      'garra', 'garras', 'pelo', 'cuerno', 'cuernos', 'pezuna', 'pico', 'picos', 'pluma', 'plumas',
      'aleta', 'aletas', 'escama', 'concha', 'conchas', 'rebano', 'manada', 'enjambre', 'animal', 'animales',
      'ganado', 'bestia', 'bestias', 'cachorro', 'potro', 'ternero', 'cordero', 'pollito', 'burro', 'burros',
      'mula', 'mulas', 'camello', 'mono', 'monos', 'gorila', 'elefante', 'jirafa', 'leopardo', 'jabali'],
    comida: ['pan', 'panes', 'arroz', 'pasta', 'pastas', 'leche', 'manteca', 'queso', 'quesos', 'carne',
      'carnes', 'sal', 'pimienta', 'azucar', 'miel', 'manzana', 'manzanas', 'pera', 'peras', 'uva',
      'uvas', 'limon', 'limones', 'naranja', 'naranjas', 'melocoton', 'melon', 'melones', 'fresa', 'fresas',
      'cereza', 'cerezas', 'platano', 'ciruela', 'higo', 'higos', 'nuez', 'nueces', 'almendra', 'patata',
      'patatas', 'zanahoria', 'cebolla', 'cebollas', 'ajo', 'ajos', 'judia', 'judias', 'ensalada', 'sopa',
      'sopas', 'pastel', 'tarta', 'tartas', 'salsa', 'salsas', 'aceite', 'harina', 'agua', 'aguas',
      'vino', 'vinos', 'zumo', 'cafe', 'cerveza', 'nata', 'helado', 'helados', 'galleta', 'galletas',
      'caramelo', 'chocolate', 'mermelada', 'yogur', 'tostada', 'bocadillo', 'pizza', 'guiso', 'asado', 'frito',
      'pollo', 'ternera', 'jamon', 'chorizo', 'salchicha', 'tocino', 'pescado', 'marisco', 'lechuga', 'tomate',
      'tomates', 'pepino', 'pimiento', 'calabaza', 'calabacin', 'berenjena', 'espinaca', 'col', 'coles', 'brocoli',
      'apio', 'puerro', 'rabano', 'nabo', 'guisante', 'lenteja', 'lentejas', 'garbanzo', 'haba', 'habas',
      'trigo', 'maiz', 'avena', 'cebada', 'centeno', 'seta', 'setas', 'perejil', 'albahaca', 'oregano',
      'romero', 'menta', 'canela', 'vainilla', 'azafran', 'mostaza', 'vinagre', 'oliva', 'olivas', 'aceituna',
      'desayuno', 'almuerzo', 'comida', 'merienda', 'cena', 'cenas', 'plato', 'platos', 'receta', 'recetas',
      'sabor', 'sabores', 'olor', 'olores', 'hambre', 'sed', 'postre'],
    casa: ['casa', 'casas', 'puerta', 'puertas', 'pared', 'paredes', 'techo', 'techos', 'suelo', 'suelos',
      'cuarto', 'cuartos', 'cocina', 'cocinas', 'bano', 'banos', 'cama', 'camas', 'silla', 'sillas',
      'mesa', 'mesas', 'sofa', 'sofas', 'lampara', 'lamparas', 'ventana', 'ventanas', 'llave', 'llaves',
      'alfombra', 'espejo', 'espejos', 'cajon', 'cajones', 'cortina', 'cortinas', 'cojin', 'cojines', 'manta',
      'mantas', 'vaso', 'vasos', 'tenedor', 'cuchillo', 'cuchara', 'olla', 'ollas', 'horno', 'hornos',
      'armario', 'escalera', 'escaleras', 'sotano', 'desvan', 'garaje', 'jardin', 'balcon', 'balcones', 'pasillo',
      'salon', 'salones', 'dormitorio', 'estante', 'estantes', 'comoda', 'colchon', 'sabana', 'sabanas', 'almohada',
      'toalla', 'toallas', 'jabon', 'esponja', 'escoba', 'escobas', 'cubo', 'cubos', 'cepillo', 'peine',
      'peines', 'reloj', 'relojes', 'jarron', 'marco', 'marcos', 'vela', 'velas', 'enchufe', 'cable',
      'cables', 'tubo', 'tubos', 'grifo', 'grifos', 'manija', 'cerradura', 'peldano', 'porton'],
    naturaleza: ['arbol', 'arboles', 'hoja', 'hojas', 'flor', 'flores', 'raiz', 'raices', 'rama', 'ramas',
      'hierba', 'campo', 'campos', 'bosque', 'bosques', 'colina', 'colinas', 'valle', 'valles', 'rio',
      'rios', 'lago', 'lagos', 'mar', 'mares', 'ola', 'olas', 'arena', 'roca', 'rocas',
      'piedra', 'piedras', 'tierra', 'cielo', 'cielos', 'sol', 'soles', 'luna', 'lunas', 'estrella',
      'estrellas', 'nube', 'nubes', 'lluvia', 'lluvias', 'nieve', 'viento', 'vientos', 'niebla', 'trueno',
      'rayo', 'rayos', 'hielo', 'isla', 'islas', 'desierto', 'cueva', 'cuevas', 'llanura', 'fuente',
      'fuentes', 'cascada', 'semilla', 'semillas', 'fruto', 'frutos', 'espina', 'espinas', 'tronco', 'corteza',
      'brote', 'brotes', 'petalo', 'petalos', 'polen', 'rosa', 'rosas', 'lirio', 'tulipan', 'margarita',
      'amapola', 'orquidea', 'helecho', 'musgo', 'junco', 'arbusto', 'seto', 'setos', 'roble', 'robles',
      'pino', 'pinos', 'abeto', 'abedul', 'sauce', 'olmo', 'olmos', 'palmera', 'olivo', 'olivos',
      'vina', 'vinas', 'barro', 'polvo', 'ceniza', 'cenizas', 'humo', 'llama', 'llamas', 'fuego',
      'fuegos', 'brasa', 'chispa', 'chispas', 'rocio', 'escarcha', 'granizo', 'tormenta', 'huracan', 'inundacion',
      'marea', 'mareas', 'orilla', 'orillas', 'playa', 'playas', 'acantilado', 'arrecife', 'bahia', 'golfo',
      'estrecho', 'canal', 'canales', 'arroyo', 'arroyos', 'charca', 'pantano', 'oasis', 'duna', 'dunas',
      'glaciar', 'cumbre', 'cumbres', 'cresta', 'ladera', 'barranco', 'sendero', 'senderos', 'monte', 'montes'],
    cuerpo: ['cabeza', 'cabezas', 'ojo', 'ojos', 'nariz', 'narices', 'boca', 'bocas', 'oreja', 'orejas',
      'mano', 'manos', 'dedo', 'dedos', 'brazo', 'brazos', 'pierna', 'piernas', 'pie', 'pies',
      'corazon', 'sangre', 'hueso', 'huesos', 'piel', 'pieles', 'pelos', 'diente', 'dientes', 'lengua',
      'lenguas', 'hombro', 'hombros', 'espalda', 'rodilla', 'rodillas', 'codo', 'codos', 'labio', 'labios',
      'una', 'unas', 'muneca', 'cuello', 'cuellos', 'cara', 'caras', 'frente', 'barbilla', 'pecho',
      'pechos', 'nervio', 'nervios', 'musculo', 'musculos', 'vena', 'venas', 'pulmon', 'pulmones', 'higado',
      'estomago', 'rinon', 'cerebro', 'craneo', 'mejilla', 'mejillas', 'ceja', 'cejas', 'pestana', 'parpado',
      'garganta', 'cadera', 'caderas', 'muslo', 'muslos', 'tobillo', 'tobillos', 'talon', 'talones', 'palma',
      'palmas', 'pulgar', 'costilla', 'columna', 'cintura', 'sudor', 'lagrima', 'lagrimas', 'aliento', 'latido',
      'latidos', 'voz', 'voces', 'mirada', 'miradas', 'sonrisa', 'sonrisas', 'gesto', 'gestos'],
    acciones: ['hacer', 'hago', 'haces', 'hace', 'hacemos', 'hacen', 'hecho', 'decir', 'digo', 'dices',
      'dice', 'decimos', 'dicen', 'dicho', 'voy', 'vas', 'vamos', 'van', 'ido', 'venir',
      'vengo', 'vienes', 'viene', 'venimos', 'vienen', 'estar', 'estoy', 'estas', 'esta', 'estamos',
      'estan', 'ser', 'soy', 'eres', 'somos', 'son', 'sido', 'tener', 'tengo', 'tienes',
      'tiene', 'tenemos', 'tienen', 'dar', 'doy', 'das', 'damos', 'dan', 'dado', 'ver',
      'veo', 'ves', 'vemos', 'ven', 'visto', 'saber', 'sabes', 'sabe', 'sabemos', 'saben',
      'querer', 'quiero', 'quieres', 'quiere', 'queremos', 'quieren', 'poder', 'puedo', 'puedes', 'puede',
      'podemos', 'pueden', 'deber', 'debo', 'debes', 'debe', 'deben', 'hablar', 'hablo', 'hablas',
      'habla', 'hablamos', 'hablan', 'oir', 'oigo', 'oyes', 'oye', 'mirar', 'miro', 'miras',
      'mira', 'miramos', 'miran', 'pensar', 'pienso', 'piensas', 'piensa', 'creer', 'creo', 'crees',
      'cree', 'creemos', 'creen', 'entender', 'leer', 'leo', 'lees', 'lee', 'leemos', 'leen',
      'leido', 'escribir', 'escribo', 'escribe', 'escrito', 'contar', 'cuento', 'cuentas', 'cuenta', 'correr',
      'corro', 'corres', 'corre', 'corremos', 'corren', 'saltar', 'salto', 'saltas', 'salta', 'nadar',
      'nado', 'nadas', 'nada', 'volar', 'vuelo', 'vuelas', 'vuela', 'caer', 'caigo', 'caes',
      'cae', 'caido', 'subir', 'subo', 'subes', 'sube', 'bajar', 'bajo', 'bajas', 'baja',
      'abrir', 'abro', 'abres', 'abre', 'abierto', 'cerrar', 'cierro', 'cierras', 'cierra', 'cerrado',
      'tomar', 'tomo', 'tomas', 'toma', 'dejar', 'dejo', 'dejas', 'deja', 'llevar', 'llevo',
      'llevas', 'lleva', 'poner', 'pongo', 'pones', 'pone', 'puesto', 'quitar', 'quito', 'quitas',
      'quita', 'girar', 'giro', 'giras', 'gira', 'volver', 'vuelvo', 'vuelves', 'vuelve', 'vuelto',
      'partir', 'parto', 'parte', 'buscar', 'busco', 'buscas', 'busca', 'hallar', 'hallo', 'halla',
      'perder', 'pierdo', 'pierdes', 'pierde', 'perdido', 'ganar', 'gano', 'ganas', 'gana', 'jugar',
      'juego', 'juegas', 'juega', 'jugamos', 'juegan', 'dormir', 'duermo', 'duermes', 'duerme', 'comer',
      'como', 'comes', 'come', 'comemos', 'comen', 'beber', 'bebo', 'bebes', 'bebe', 'reir',
      'ries', 'rie', 'llorar', 'lloro', 'llora', 'cantar', 'canto', 'cantas', 'canta', 'bailar',
      'bailo', 'bailas', 'baila', 'construir', 'romper', 'rompo', 'rompes', 'rompe', 'roto', 'limpiar',
      'limpio', 'limpia', 'lavar', 'lavo', 'lavas', 'lava', 'cocinar', 'cocino', 'ayudar', 'ayudo',
      'ayudas', 'ayuda', 'explicar', 'aprender', 'aprendo', 'aprende', 'ensenar', 'crecer', 'crezco', 'crece',
      'elegir', 'elijo', 'elige', 'comprar', 'compro', 'compras', 'compra', 'vender', 'vendo', 'vendes',
      'vende', 'pagar', 'pago', 'pagas', 'paga', 'llamar', 'llamo', 'amar', 'amo', 'amas',
      'ama', 'esperar', 'espero', 'esperas', 'espera', 'vivir', 'vivo', 'vives', 'vive', 'morir',
      'muero', 'muere', 'nacer', 'nazco', 'nace', 'seguir', 'sigo', 'sigues', 'sigue', 'tocar',
      'toco', 'tocas', 'toca', 'tirar', 'tiro', 'tiras', 'tira', 'empujar', 'esconder', 'mostrar',
      'muestro', 'muestra', 'probar', 'pruebo', 'prueba', 'usar', 'uso', 'usas', 'usa', 'entrar',
      'entro', 'entra', 'salir', 'salgo', 'sales', 'sale', 'andar', 'ando', 'andas', 'anda',
      'caminar', 'camino'],
    cualidades: ['bueno', 'buena', 'buenos', 'buenas', 'malo', 'mala', 'malos', 'malas', 'grande', 'grandes',
      'pequeno', 'pequena', 'pequenos', 'alto', 'alta', 'altos', 'altas', 'bajos', 'largo', 'larga',
      'largos', 'largas', 'corto', 'corta', 'cortos', 'cortas', 'ancho', 'ancha', 'nuevo', 'nueva',
      'nuevos', 'nuevas', 'viejo', 'vieja', 'viejos', 'viejas', 'joven', 'jovenes', 'fuerte', 'fuertes',
      'debil', 'debiles', 'caliente', 'frio', 'fria', 'frios', 'frias', 'seco', 'seca', 'secos',
      'secas', 'mojado', 'mojada', 'lleno', 'llena', 'llenos', 'vacio', 'vacia', 'vacios', 'pesado',
      'pesada', 'ligero', 'ligera', 'duro', 'dura', 'duros', 'duras', 'blando', 'blanda', 'liso',
      'lisa', 'aspero', 'claro', 'clara', 'claros', 'oscuro', 'oscura', 'rapido', 'rapida', 'rapidos',
      'lento', 'lenta', 'lentos', 'facil', 'faciles', 'dificil', 'justo', 'justa', 'rico', 'rica',
      'ricos', 'ricas', 'pobre', 'pobres', 'feliz', 'felices', 'triste', 'tristes', 'tranquilo', 'dulce',
      'dulces', 'amargo', 'amarga', 'salado', 'salada', 'fresco', 'fresca', 'sucio', 'sucia', 'sucios',
      'limpios', 'raro', 'rara', 'raros', 'comun', 'comunes', 'extrano', 'extrana', 'normal', 'seguro',
      'segura', 'libre', 'libres', 'cansado', 'cansada', 'amable', 'amables', 'cortes', 'honesto', 'honesta',
      'listo', 'lista', 'tonto', 'tonta', 'sabio', 'sabia', 'perezoso', 'valiente', 'util', 'utiles',
      'inutil', 'verdadero', 'falso', 'falsa', 'cierto', 'cierta', 'abierta', 'profundo', 'delgado', 'delgada',
      'grueso', 'gruesa', 'gordo', 'gorda', 'flaco', 'flaca', 'redondo', 'redonda', 'recto', 'recta',
      'torcido', 'plano', 'plana', 'agudo', 'brillante', 'opaco', 'desnudo', 'lejano', 'lejana', 'cercano',
      'cercana', 'antiguo', 'antigua', 'moderno', 'moderna', 'unico', 'unica', 'doble', 'dobles', 'entero',
      'entera', 'medio', 'media', 'ultimo', 'ultima', 'primero', 'primera', 'severo', 'sereno', 'nervioso',
      'timido', 'timida', 'orgulloso', 'humilde', 'tibio', 'crudo', 'cruda', 'cocido', 'maduro', 'madura',
      'enfermo', 'enferma', 'sano', 'sana', 'herido', 'herida', 'viva', 'mudo', 'muda', 'sordo',
      'sorda', 'ciego', 'ciega', 'enorme', 'enormes', 'inmenso', 'gigante', 'minusculo', 'hermoso', 'hermosa',
      'feo'],
    tiempo: ['hora', 'horas', 'dia', 'dias', 'noche', 'noches', 'mes', 'meses', 'ano', 'anos',
      'siglo', 'siglos', 'momento', 'momentos', 'minuto', 'minutos', 'segundo', 'segundos', 'semana', 'semanas',
      'manana', 'mananas', 'tarde', 'tardes', 'mediodia', 'alba', 'ocaso', 'estacion', 'verano', 'veranos',
      'invierno', 'otono', 'primavera', 'ayer', 'hoy', 'pronto', 'retraso', 'epoca', 'epocas', 'pasado',
      'futuro', 'presente', 'lunes', 'martes', 'jueves', 'viernes', 'sabado', 'domingo', 'enero', 'febrero',
      'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'octubre', 'noviembre', 'diciembre', 'fecha',
      'fechas', 'calendario', 'duracion', 'inicio', 'final', 'finales', 'periodo', 'instante', 'siempre', 'nunca',
      'jamas', 'ahora', 'antes', 'despues', 'mientras', 'durante', 'desde', 'hasta', 'diario', 'semanal',
      'mensual', 'anual', 'jornada', 'velada', 'vispera', 'fiesta', 'fiestas', 'vacaciones'],
    colores: ['rojo', 'roja', 'rojos', 'rojas', 'verde', 'verdes', 'azul', 'azules', 'amarillo', 'amarilla',
      'negro', 'negra', 'negros', 'negras', 'blanco', 'blanca', 'blancos', 'blancas', 'gris', 'grises',
      'morado', 'morada', 'marron', 'marrones', 'dorado', 'dorada', 'plateado', 'beige', 'marfil', 'purpura',
      'turquesa', 'ocre', 'violeta', 'indigo', 'carmesi', 'escarlata', 'granate', 'celeste', 'lila', 'coral',
      'esmeralda', 'zafiro', 'rubi', 'color', 'colores', 'tono', 'tonos', 'matiz', 'matices', 'sombra',
      'brillo', 'palido', 'palida', 'oscuros'],
    objetos: ['libro', 'libros', 'boligrafo', 'papel', 'papeles', 'cuaderno', 'bolsa', 'bolsas', 'caja', 'cajas',
      'cuerda', 'cuerdas', 'clavo', 'clavos', 'martillo', 'aguja', 'agujas', 'hilo', 'hilos', 'boton',
      'botones', 'paraguas', 'gafas', 'maleta', 'maletas', 'sombrero', 'zapato', 'zapatos', 'guante', 'guantes',
      'bufanda', 'anillo', 'anillos', 'cadena', 'cadenas', 'rueda', 'ruedas', 'motor', 'motores', 'barco',
      'barcos', 'nave', 'naves', 'tren', 'trenes', 'avion', 'aviones', 'coche', 'coches', 'bici',
      'moto', 'motos', 'puente', 'puentes', 'calle', 'calles', 'verja', 'linterna', 'cesta', 'cestas',
      'lapiz', 'lapices', 'regla', 'reglas', 'goma', 'tijeras', 'pegamento', 'cinta', 'cintas', 'saco',
      'sacos', 'cofre', 'tapa', 'tapas', 'tapon', 'tornillo', 'tuerca', 'alicates', 'sierra', 'hacha',
      'pala', 'palas', 'rastrillo', 'carro', 'carros', 'remo', 'remos', 'ancla', 'brujula', 'mapa',
      'mapas', 'lente', 'lentes', 'camara', 'camaras', 'telefono', 'pantalla', 'teclado', 'pila', 'pilas',
      'moneda', 'monedas', 'dinero', 'cartera', 'billete', 'billetes', 'sello', 'sellos', 'carta', 'cartas',
      'paquete', 'tarjeta', 'tarjetas', 'cartel', 'carteles', 'bandera', 'banderas', 'juguete', 'juguetes', 'munecas',
      'pelota', 'pelotas', 'balon', 'dados', 'campana'],
    lugares: ['ciudad', 'ciudades', 'pueblo', 'pueblos', 'plaza', 'plazas', 'parque', 'parques', 'escuela', 'escuelas',
      'iglesia', 'iglesias', 'museo', 'museos', 'teatro', 'teatros', 'mercado', 'mercados', 'tienda', 'tiendas',
      'banco', 'bancos', 'puerto', 'puertos', 'aeropuerto', 'hospital', 'hotel', 'hoteles', 'castillo', 'torre',
      'torres', 'jardines', 'patio', 'patios', 'granja', 'granjas', 'aldea', 'barrio', 'barrios', 'frontera',
      'region', 'regiones', 'costa', 'costas', 'caminos', 'avenida', 'esquina', 'esquinas', 'estatua', 'cine',
      'cines', 'estadio', 'circo', 'feria', 'ferias', 'bar', 'bares', 'taberna', 'panaderia', 'farmacia',
      'libreria', 'taller', 'talleres', 'fabrica', 'fabricas', 'molino', 'mina', 'minas', 'cantera', 'muelle',
      'faro', 'faros', 'refugio', 'cabana', 'cabanas', 'campamento', 'palacio', 'villa', 'villas', 'edificio',
      'oficina', 'oficinas', 'galeria', 'templo', 'templos', 'capilla', 'ruinas', 'tunel', 'tuneles', 'cruce',
      'terreno', 'huerto'],
    trabajo: ['trabajo', 'trabajos', 'equipo', 'equipos', 'proyecto', 'proyectos', 'tarea', 'tareas', 'reunion', 'reuniones',
      'contrato', 'contratos', 'sueldo', 'cliente', 'clientes', 'factura', 'facturas', 'agenda', 'objetivo', 'objetivos',
      'resultado', 'resultados', 'informe', 'informes', 'documento', 'firma', 'firmas', 'acuerdo', 'acuerdos', 'empresa',
      'empresas', 'oficio', 'oficios', 'turno', 'turnos', 'pausa', 'pausas', 'carrera', 'merito', 'premio',
      'premios', 'formacion', 'destreza', 'colega', 'colegas', 'jefe', 'jefes', 'plazo', 'plazos', 'obrero',
      'obreros', 'empleado', 'empleada', 'gerente', 'duenno', 'socio', 'socios', 'proveedor', 'ganancia', 'ingreso',
      'perdida', 'coste', 'costes', 'precio', 'precios', 'descuento', 'deuda', 'deudas', 'credito', 'pagos',
      'recibo', 'recibos', 'archivo', 'archivos', 'carpeta', 'medico', 'enfermero', 'maestro', 'maestra', 'abogado',
      'juez', 'jueces', 'soldado', 'marinero', 'piloto', 'chofer', 'cocinero', 'camarero', 'panadero', 'sastre',
      'granjero', 'pescador', 'minero', 'albanil', 'pintor'],
    artes: ['arte', 'artes', 'musica', 'musicas', 'cantos', 'baile', 'bailes', 'cuadro', 'cuadros', 'pintura',
      'pincel', 'pinceles', 'lienzo', 'lienzos', 'estatuas', 'poema', 'poemas', 'novela', 'novelas', 'cuentos',
      'pelicula', 'actor', 'actores', 'actriz', 'escena', 'escenas', 'ritmo', 'ritmos', 'nota', 'notas',
      'acorde', 'acordes', 'guitarra', 'guitarras', 'piano', 'pianos', 'violin', 'violines', 'flauta', 'flautas',
      'tambor', 'tambores', 'coro', 'coros', 'melodia', 'melodias', 'dibujo', 'dibujos', 'boceto', 'verso',
      'versos', 'rima', 'rimas', 'opera', 'operas', 'artista', 'artistas', 'autor', 'autores', 'poeta',
      'poetas', 'lector', 'lectores', 'capitulo', 'pagina', 'paginas', 'titulo', 'titulos', 'trama', 'comedia',
      'tragedia', 'drama', 'dramas', 'escenario', 'telon', 'guion', 'concierto', 'orquesta', 'ballet', 'disfraz',
      'mascara', 'mascaras', 'sonido', 'sonidos', 'silencio', 'eco'],
    materiales: ['madera', 'maderas', 'hierro', 'acero', 'cobre', 'oro', 'plata', 'vidrio', 'plastico', 'tela',
      'telas', 'lana', 'seda', 'sedas', 'algodon', 'cuero', 'marmol', 'granito', 'cemento', 'cera',
      'cuarzo', 'diamante', 'bronce', 'plomo', 'zinc', 'cristal', 'arcilla', 'corcho', 'lino', 'terciopelo',
      'encaje', 'metal', 'metales', 'aleacion', 'estano', 'niquel', 'laton', 'ladrillo', 'ladrillos', 'teja',
      'tejas', 'grava', 'asfalto', 'resina', 'barniz', 'fibra', 'fibras', 'tejido'],
    general: ['cosa', 'cosas', 'modo', 'modos', 'partes', 'punto', 'puntos', 'signo', 'signos', 'nombre',
      'nombres', 'numero', 'numeros', 'palabra', 'palabras', 'frase', 'frases', 'historia', 'historias', 'idea',
      'ideas', 'sueno', 'suenos', 'recuerdo', 'duda', 'dudas', 'eleccion', 'orden', 'ordenes', 'caso',
      'casos', 'suerte', 'destino', 'centro', 'centros', 'lado', 'lados', 'fondo', 'fondos', 'borde',
      'bordes', 'linea', 'lineas', 'circulo', 'circulos', 'cuadrado', 'forma', 'formas', 'medida', 'medidas',
      'peso', 'pesos', 'altura', 'alturas', 'distancia', 'espacio', 'espacios', 'verdad', 'mentira', 'error',
      'errores', 'culpa', 'culpas', 'motivo', 'motivos', 'causa', 'causas', 'efecto', 'efectos', 'ejemplo',
      'pruebas', 'pregunta', 'respuesta', 'problema', 'solucion', 'metodo', 'metodos', 'sistema', 'sistemas', 'plan',
      'planes', 'consejo', 'consejos', 'aviso', 'noticia', 'noticias', 'discurso', 'ruido', 'ruidos', 'secreto',
      'secretos', 'misterio', 'sorpresa', 'broma', 'juegos', 'regalo', 'regalos', 'favor', 'gracias', 'perdon',
      'saludo', 'saludos', 'visita', 'visitas', 'viaje', 'viajes', 'salida', 'llegada', 'regreso', 'meta',
      'metas', 'paso', 'pasos', 'huella', 'huellas', 'fuerza', 'fuerzas', 'poderes', 'derecho', 'derechos',
      'ley', 'leyes', 'paz', 'guerra', 'guerras', 'lucha', 'luchas', 'victoria', 'derrota', 'promesa',
      'confianza', 'valor', 'miedo', 'miedos', 'alegria', 'dolor', 'dolores', 'amor', 'odio', 'ira',
      'esperanza', 'llanto', 'vergueenza', 'orgullo', 'envidia', 'celos', 'carino', 'pasion', 'deseo'],
    comunes: ['ella', 'nosotros', 'vosotros', 'ellos', 'ellas', 'mio', 'mia', 'tuyo', 'tuya', 'suyo',
      'suya', 'nuestro', 'nuestra', 'vuestro', 'este', 'estos', 'ese', 'esa', 'esos', 'esas',
      'aquel', 'aquella', 'quien', 'quienes', 'que', 'cual', 'cuales', 'donde', 'cuando', 'cuanto',
      'cuanta', 'cuantos', 'porque', 'tambien', 'todavia', 'quizas', 'acaso', 'apenas', 'casi', 'demasiado',
      'bastante', 'poco', 'poca', 'pocos', 'mucho', 'mucha', 'muchos', 'muchas', 'todo', 'toda',
      'todos', 'todas', 'nadie', 'alguien', 'algo', 'alguno', 'alguna', 'ninguno', 'otro', 'otra',
      'otros', 'otras', 'mismo', 'misma', 'cada', 'ambos', 'varios', 'delante', 'detras', 'encima',
      'debajo', 'dentro', 'fuera', 'cerca', 'lejos', 'junto', 'contra', 'hacia', 'segun', 'entre',
      'sobre', 'sin', 'solo', 'sola', 'solos', 'bien', 'mal', 'mejor', 'peor', 'menos',
      'mas', 'muy', 'hola', 'adios', 'perdona', 'entonces', 'luego', 'ademas'],
  },
  parole: [
    { word: 'meloso', category: 'cualidades', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'De una dulzura excesiva y afectada, sobre todo al hablar.',
      translations: { it: 'mellifluo', en: 'mellifluous', fr: 'mielleux', de: 'honigsüß' } },
    { word: 'cuarzo', category: 'materiales', grammaticalType: 'noun', difficulty: 2, rarity: 3,
      definition: 'Mineral durísimo y transparente, de los más comunes de la corteza terrestre.',
      translations: { it: 'quarzo', en: 'quartz', fr: 'quartz', de: 'Quarz' } },
    { word: 'céfiro', category: 'naturaleza', grammaticalType: 'noun', difficulty: 3, rarity: 4,
      definition: 'Viento suave y templado que sopla de poniente.',
      translations: { it: 'zefiro', en: 'zephyr', fr: 'zéphyr', de: 'Zephir' } },
    { word: 'crepúsculo', category: 'tiempo', grammaticalType: 'noun', difficulty: 3, rarity: 4,
      definition: 'La luz incierta entre el ocaso y la noche.',
      translations: { it: 'crepuscolo', en: 'twilight', fr: 'crépuscule', de: 'Dämmerung' } },
    { word: 'efímero', category: 'cualidades', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Que dura muy poco tiempo.',
      translations: { it: 'effimero', en: 'ephemeral', fr: 'éphémère', de: 'flüchtig' } },
    { word: 'sagaz', category: 'cualidades', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Que entiende deprisa y prevé lo que va a pasar.',
      translations: { it: 'sagace', en: 'shrewd', fr: 'sagace', de: 'scharfsinnig' } },
    { word: 'meandro', category: 'naturaleza', grammaticalType: 'noun', difficulty: 2, rarity: 3,
      definition: 'Curva amplia de un río; por extensión, un camino tortuoso.',
      translations: { it: 'meandro', en: 'meander', fr: 'méandre', de: 'Mäander' } },
    { word: 'cenit', category: 'naturaleza', grammaticalType: 'noun', difficulty: 3, rarity: 4,
      definition: 'El punto del cielo justo encima de quien mira.',
      translations: { it: 'zenit', en: 'zenith', fr: 'zénith', de: 'Zenit' } },
    { word: 'lacónico', category: 'cualidades', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Que se expresa con muy pocas palabras.',
      translations: { it: 'laconico', en: 'terse', fr: 'laconique', de: 'knapp' } },
    { word: 'tenaz', category: 'cualidades', grammaticalType: 'adjective', difficulty: 2, rarity: 3,
      definition: 'Que no suelta lo que agarra, ni abandona lo que se propone.',
      translations: { it: 'tenace', en: 'tenacious', fr: 'tenace', de: 'hartnäckig' } },
    { word: 'diáfano', category: 'cualidades', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Tan fino que deja pasar la luz.',
      translations: { it: 'diafano', en: 'diaphanous', fr: 'diaphane', de: 'durchscheinend' } },
    { word: 'urraca', category: 'animales', grammaticalType: 'noun', difficulty: 2, rarity: 3,
      definition: 'Ave blanca y negra, conocida por recoger objetos brillantes.',
      translations: { it: 'gazza', en: 'magpie', fr: 'pie', de: 'Elster' } },
  ],
};
