/**
 * Français. Gli accenti si tolgono per giocare: sul campo esce una E, e
 * ÉTÉ si forma con tre tessere normali. La cediglia del Ç fa lo stesso
 * (Ç → C): sono segni che cambiano il suono, non la parola, e in un gioco
 * di tessere una tessera in piu' per ognuno renderebbe il campo illeggibile.
 */
export const fr = {
  id: 'fr', nome: 'Français', locale: 'fr-FR',
  tieniAccenti: false, digrammi: [], sostituzioni: { Œ: 'OE', Æ: 'AE' },
  alfabeto: [
    { lettera: 'E', peso: 147, valore: 1 }, { lettera: 'A', peso: 76, valore: 1 },
    { lettera: 'I', peso: 75, valore: 1 },  { lettera: 'S', peso: 79, valore: 1 },
    { lettera: 'N', peso: 71, valore: 1 },  { lettera: 'R', peso: 66, valore: 1 },
    { lettera: 'T', peso: 72, valore: 1 },  { lettera: 'O', peso: 54, valore: 1 },
    { lettera: 'U', peso: 63, valore: 1 },  { lettera: 'L', peso: 55, valore: 1 },
    { lettera: 'D', peso: 37, valore: 2 },  { lettera: 'C', peso: 33, valore: 2 },
    { lettera: 'M', peso: 30, valore: 2 },  { lettera: 'P', peso: 30, valore: 2 },
    { lettera: 'V', peso: 16, valore: 3 },  { lettera: 'Q', peso: 14, valore: 4 },
    { lettera: 'F', peso: 11, valore: 3 },  { lettera: 'B', peso: 9, valore: 3 },
    { lettera: 'G', peso: 9, valore: 3 },   { lettera: 'H', peso: 7, valore: 4 },
    { lettera: 'J', peso: 5, valore: 6 },   { lettera: 'X', peso: 4, valore: 7 },
    { lettera: 'Y', peso: 3, valore: 6 },   { lettera: 'Z', peso: 2, valore: 8 },
    { lettera: 'K', peso: 2, valore: 8 },   { lettera: 'W', peso: 2, valore: 8 },
  ],
  /**
   * Da una parola, le forme da cui potrebbe derivare: serve a tenere i
   * plurali fuori dalle parole segrete. CHIENS viene da CHIEN, OISEAUX da
   * OISEAU, JOURNAUX da JOURNAL.
   */
  formeBase: (p) => {
    const f = [];
    if (p.endsWith('AUX')) f.push(p.slice(0, -3) + 'AL', p.slice(0, -1));
    if (p.endsWith('X')) f.push(p.slice(0, -1));
    if (p.endsWith('S')) f.push(p.slice(0, -1));
    if (p.endsWith('ES')) f.push(p.slice(0, -2));
    return f;
  },

  /* Dalla categoria dei verbi si fa indovinare solo l'infinito. */
  verbi: { categoria: 'actions', infinito: /(ER|IR|RE|OIR)$/ },

  categorie: {
    animaux: 'Animaux', nourriture: 'Nourriture', maison: 'Maison', nature: 'Nature', corps: 'Corps',
    travail: 'Travail', temps: 'Temps', couleurs: 'Couleurs', objets: 'Objets', actions: 'Actions',
    qualites: 'Qualités', lieux: 'Lieux', arts: 'Arts', matieres: 'Matières', communs: 'Mots courants', general: 'Général',
  },
  gruppi: {
    animaux: ['chien', 'chiens', 'chat', 'chats', 'chatte', 'souris', 'cheval', 'chevaux', 'vache', 'vaches',
      'mouton', 'moutons', 'chevre', 'chevres', 'porc', 'porcs', 'poule', 'poules', 'coq', 'coqs',
      'canard', 'canards', 'poisson', 'poissons', 'oiseau', 'oiseaux', 'aigle', 'aigles', 'hibou', 'chouette',
      'corbeau', 'loup', 'loups', 'renard', 'renards', 'ours', 'cerf', 'cerfs', 'lion', 'lions',
      'tigre', 'tigres', 'zebre', 'zebres', 'baleine', 'requin', 'requins', 'crabe', 'crabes', 'escargot',
      'araignee', 'fourmi', 'fourmis', 'abeille', 'abeilles', 'papillon', 'grenouille', 'serpent', 'tortue', 'lapin',
      'lapins', 'ecureuil', 'blaireau', 'loutre', 'phoque', 'cygne', 'cygnes', 'faucon', 'merle', 'moineau',
      'pigeon', 'pigeons', 'colombe', 'perroquet', 'hirondelle', 'mouette', 'cigogne', 'heron', 'vautour', 'chouettes',
      'agneau', 'veau', 'veaux', 'poulain', 'poussin', 'ane', 'anes', 'mulet', 'chameau', 'singe',
      'singes', 'gorille', 'elephant', 'girafe', 'girafes', 'guepard', 'panthere', 'lynx', 'bison', 'sanglier',
      'chevreuil', 'taupe', 'taupes', 'herisson', 'castor', 'belette', 'furet', 'lezard', 'crapaud', 'ver',
      'vers', 'limace', 'limaces', 'mouche', 'mouches', 'guepe', 'guepes', 'moustique', 'puce', 'puces',
      'criquet', 'sauterelle', 'scarabee', 'pieuvre', 'poulpe', 'calmar', 'meduse', 'homard', 'crevette', 'huitre',
      'moule', 'moules', 'saumon', 'truite', 'thon', 'anguille', 'morue', 'dauphin', 'nid', 'nids',
      'oeuf', 'oeufs', 'aile', 'ailes', 'queue', 'queues', 'patte', 'pattes', 'griffe', 'griffes',
      'poil', 'poils', 'corne', 'cornes', 'sabot', 'bec', 'becs', 'plume', 'plumes', 'nageoire',
      'ecaille', 'coquille', 'troupeau', 'meute', 'essaim', 'animal', 'animaux', 'betail', 'bete'],
    nourriture: ['pain', 'pains', 'riz', 'pate', 'pates', 'lait', 'beurre', 'fromage', 'viande', 'viandes',
      'sel', 'poivre', 'sucre', 'miel', 'pomme', 'pommes', 'poire', 'poires', 'raisin', 'raisins',
      'citron', 'citrons', 'orange', 'oranges', 'peche', 'peches', 'melon', 'melons', 'fraise', 'fraises',
      'cerise', 'cerises', 'banane', 'bananes', 'prune', 'prunes', 'abricot', 'figue', 'figues', 'noix',
      'amande', 'amandes', 'noisette', 'salade', 'salades', 'soupe', 'soupes', 'potage', 'gateau', 'gateaux',
      'tarte', 'tartes', 'sauce', 'sauces', 'huile', 'huiles', 'farine', 'eau', 'eaux', 'vin',
      'vins', 'biere', 'bieres', 'jus', 'cafe', 'cafes', 'the', 'creme', 'yaourt', 'glace',
      'glaces', 'bonbon', 'bonbons', 'chocolat', 'biscuit', 'biscuits', 'confiture', 'sirop', 'carotte', 'carottes',
      'oignon', 'oignons', 'ail', 'haricot', 'haricots', 'petit', 'pois', 'chou', 'choux', 'laitue',
      'epinard', 'epinards', 'courge', 'courgette', 'aubergine', 'tomate', 'tomates', 'concombre', 'radis', 'navet',
      'poireau', 'celeri', 'champignon', 'truffe', 'persil', 'basilic', 'thym', 'romarin', 'menthe', 'cannelle',
      'vanille', 'safran', 'moutarde', 'vinaigre', 'olive', 'olives', 'anchois', 'jambon', 'saucisse', 'bacon',
      'steak', 'poulet', 'boeuf', 'rôti', 'ragout', 'bouillon', 'repas', 'diner', 'souper', 'gouter',
      'entree', 'plat', 'plats', 'dessert', 'recette', 'recettes', 'gout', 'gouts', 'odeur', 'odeurs',
      'faim', 'soif', 'assiette', 'verre', 'verres', 'bouteille'],
    maison: ['maison', 'maisons', 'porte', 'portes', 'mur', 'murs', 'toit', 'toits', 'sol', 'sols',
      'piece', 'pieces', 'cuisine', 'bain', 'lit', 'lits', 'chaise', 'chaises', 'table', 'tables',
      'canape', 'lampe', 'lampes', 'fenetre', 'fenetres', 'cle', 'cles', 'tapis', 'miroir', 'miroirs',
      'tiroir', 'tiroirs', 'rideau', 'rideaux', 'coussin', 'couverture', 'fourchette', 'couteau', 'cuillere', 'casserole',
      'four', 'fours', 'evier', 'plafond', 'escalier', 'grenier', 'cave', 'caves', 'garage', 'jardin',
      'balcon', 'balcons', 'couloir', 'salon', 'salons', 'chambre', 'chambres', 'bureau', 'placard', 'armoire',
      'armoires', 'etagere', 'commode', 'matelas', 'drap', 'draps', 'oreiller', 'couette', 'serviette', 'savon',
      'eponge', 'balai', 'balais', 'seau', 'seaux', 'brosse', 'brosses', 'peigne', 'rasoir', 'horloge',
      'pendule', 'vase', 'vases', 'cadre', 'cadres', 'bougie', 'bougies', 'prise', 'prises', 'fil',
      'fils', 'tuyau', 'tuyaux', 'robinet', 'poignee', 'serrure', 'marche', 'marches', 'portail'],
    nature: ['arbre', 'arbres', 'feuille', 'feuilles', 'fleur', 'fleurs', 'racine', 'racines', 'branche', 'branches',
      'herbe', 'herbes', 'champ', 'champs', 'bois', 'foret', 'forets', 'colline', 'collines', 'vallee',
      'vallees', 'riviere', 'rivieres', 'lac', 'lacs', 'mer', 'mers', 'vague', 'vagues', 'sable',
      'roche', 'roches', 'pierre', 'pierres', 'terre', 'terres', 'ciel', 'cieux', 'soleil', 'lune',
      'lunes', 'etoile', 'etoiles', 'nuage', 'nuages', 'pluie', 'pluies', 'neige', 'neiges', 'vent',
      'vents', 'brume', 'brouillard', 'tonnerre', 'eclair', 'eclairs', 'ile', 'iles', 'desert', 'deserts',
      'grotte', 'grottes', 'plaine', 'plaines', 'source', 'sources', 'cascade', 'graine', 'graines', 'fruit',
      'fruits', 'epine', 'epines', 'tronc', 'ecorce', 'bourgeon', 'petale', 'petales', 'pollen', 'rose',
      'roses', 'lys', 'tulipe', 'tulipes', 'marguerite', 'coquelicot', 'orchidee', 'fougere', 'mousse', 'roseau',
      'buisson', 'haie', 'haies', 'chene', 'chenes', 'pin', 'pins', 'sapin', 'sapins', 'bouleau',
      'saule', 'saules', 'peuplier', 'orme', 'ormes', 'palmier', 'olivier', 'vigne', 'vignes', 'boue',
      'poussiere', 'cendre', 'cendres', 'fumee', 'flamme', 'flammes', 'feu', 'feux', 'braise', 'etincelle',
      'rosee', 'gel', 'gele', 'grele', 'orage', 'orages', 'tempete', 'ouragan', 'inondation', 'maree',
      'marees', 'courant', 'rivage', 'rivages', 'plage', 'plages', 'falaise', 'recif', 'baie', 'baies',
      'golfe', 'detroit', 'canal', 'canaux', 'ruisseau', 'etang', 'etangs', 'marais', 'oasis', 'dune',
      'dunes', 'glacier', 'sommet', 'sommets', 'crete', 'pente', 'pentes', 'gorge', 'sentier'],
    corps: ['tete', 'tetes', 'oeil', 'yeux', 'nez', 'bouche', 'bouches', 'oreille', 'oreilles', 'main',
      'mains', 'doigt', 'doigts', 'bras', 'jambe', 'jambes', 'pied', 'pieds', 'coeur', 'coeurs',
      'sang', 'squelette', 'peau', 'peaux', 'cheveu', 'cheveux', 'dent', 'dents', 'langue', 'langues',
      'epaule', 'epaules', 'dos', 'genou', 'genoux', 'coude', 'coudes', 'levre', 'levres', 'ongle',
      'ongles', 'poignet', 'cou', 'cous', 'visage', 'visages', 'front', 'fronts', 'menton', 'poitrine',
      'nerf', 'nerfs', 'muscle', 'muscles', 'veine', 'veines', 'poumon', 'poumons', 'foie', 'estomac',
      'rein', 'reins', 'cerveau', 'crane', 'cranes', 'joue', 'joues', 'sourcil', 'cil', 'cils',
      'paupiere', 'gorges', 'hanche', 'hanches', 'cuisse', 'cuisses', 'cheville', 'talon', 'talons', 'orteil',
      'orteils', 'paume', 'pouce', 'pouces', 'cote', 'cotes', 'taille', 'sueur', 'larme', 'larmes',
      'souffle', 'voix', 'regard', 'regards', 'sourire', 'sourires', 'geste', 'gestes', 'chair'],
    actions: ['faire', 'fais', 'fait', 'faites', 'font', 'dire', 'dis', 'dit', 'disons', 'disent',
      'aller', 'vais', 'vas', 'allez', 'vont', 'venir', 'viens', 'vient', 'venez', 'viennent',
      'etre', 'suis', 'est', 'sommes', 'etes', 'sont', 'avoir', 'avons', 'avez', 'ont',
      'donner', 'donne', 'donnes', 'donnez', 'donnent', 'voir', 'vois', 'voit', 'voyons', 'voyez',
      'voient', 'savoir', 'sais', 'sait', 'savons', 'savez', 'savent', 'vouloir', 'veux', 'veut',
      'voulez', 'veulent', 'pouvoir', 'peux', 'peut', 'pouvez', 'peuvent', 'devoir', 'dois', 'doit',
      'devez', 'doivent', 'parler', 'parle', 'parles', 'parlez', 'parlent', 'entendre', 'entends', 'entend',
      'regarder', 'regarde', 'regardes', 'regardez', 'penser', 'pense', 'penses', 'pensez', 'croire', 'crois',
      'croit', 'croyez', 'comprendre', 'lire', 'lis', 'lisons', 'lisez', 'ecrire', 'ecris', 'ecrit',
      'compter', 'compte', 'comptes', 'courir', 'cours', 'court', 'courez', 'sauter', 'saute', 'sautes',
      'nager', 'nage', 'nages', 'voler', 'vole', 'voles', 'tomber', 'tombe', 'tombes', 'monter',
      'monte', 'montes', 'descendre', 'ouvrir', 'ouvre', 'ouvres', 'ouvert', 'fermer', 'ferme', 'fermes',
      'prendre', 'prends', 'prend', 'prenez', 'laisser', 'laisse', 'porter', 'portez', 'mettre', 'mets',
      'met', 'mettez', 'enlever', 'tourner', 'tourne', 'tournes', 'revenir', 'partir', 'pars', 'part',
      'partez', 'rester', 'reste', 'restes', 'chercher', 'cherche', 'cherches', 'trouver', 'trouve', 'trouves',
      'perdre', 'perds', 'perd', 'gagner', 'gagne', 'gagnes', 'jouer', 'jouez', 'jouent', 'travailler',
      'dormir', 'dors', 'dort', 'manger', 'mange', 'manges', 'mangez', 'boire', 'boit', 'buvez',
      'rire', 'ris', 'rit', 'rions', 'pleurer', 'pleure', 'chanter', 'chante', 'chantes', 'danser',
      'danse', 'construire', 'casser', 'casse', 'nettoyer', 'laver', 'lave', 'laves', 'cuisiner', 'aider',
      'aide', 'aides', 'aidez', 'expliquer', 'apprendre', 'apprends', 'enseigner', 'appeler', 'appelle', 'aimer',
      'aime', 'aimes', 'aimez', 'aiment', 'detester', 'esperer', 'espere', 'craindre', 'attendre', 'attends',
      'attend', 'grandir', 'naitre', 'mourir', 'meurs', 'meurt', 'vivre', 'vis', 'vit', 'vivons',
      'acheter', 'achete', 'vendre', 'vends', 'vend', 'payer', 'paie', 'paies', 'demander', 'demande',
      'repondre', 'reponds', 'repond', 'conduire', 'voyager', 'entrer', 'entre', 'entres', 'sortir', 'sors',
      'sort', 'suivre', 'suit', 'toucher', 'touche', 'touches', 'tenir', 'tiens', 'tient', 'tirer',
      'tire', 'tires', 'pousser', 'pousse', 'jeter', 'jette', 'cacher', 'cache', 'caches', 'montrer',
      'montre', 'montres', 'essayer', 'essaie', 'utiliser', 'utilise', 'marcher'],
    qualites: ['beau', 'belle', 'beaux', 'belles', 'laid', 'laide', 'grand', 'grande', 'grands', 'grandes',
      'petite', 'petits', 'petites', 'haut', 'haute', 'hauts', 'hautes', 'bas', 'basse', 'long',
      'longue', 'longs', 'longues', 'courte', 'courts', 'courtes', 'large', 'larges', 'etroit', 'etroite',
      'neuf', 'neuve', 'nouveau', 'nouvelle', 'vieux', 'vieille', 'jeune', 'jeunes', 'fort', 'forte',
      'forts', 'fortes', 'faible', 'faibles', 'chaud', 'chaude', 'chauds', 'froid', 'froide', 'froids',
      'sec', 'seche', 'mouille', 'plein', 'pleine', 'pleins', 'vide', 'vides', 'lourd', 'lourde',
      'leger', 'legere', 'dur', 'dure', 'durs', 'dures', 'doux', 'douce', 'lisse', 'rugueux',
      'clair', 'claire', 'clairs', 'sombre', 'sombres', 'rapide', 'rapides', 'lent', 'lente', 'lents',
      'lentes', 'facile', 'faciles', 'difficile', 'juste', 'justes', 'faux', 'fausse', 'riche', 'riches',
      'pauvre', 'pauvres', 'heureux', 'heureuse', 'triste', 'tristes', 'calme', 'calmes', 'bon', 'bonne',
      'bons', 'bonnes', 'mauvais', 'amer', 'amere', 'sale', 'salee', 'frais', 'fraiche', 'propre',
      'propres', 'rare', 'rares', 'commun', 'commune', 'etrange', 'normal', 'normale', 'sur', 'sure',
      'libre', 'libres', 'fatigue', 'fatiguee', 'gentil', 'gentille', 'poli', 'polie', 'honnete', 'malin',
      'maligne', 'sage', 'sages', 'paresseux', 'brave', 'braves', 'utile', 'utiles', 'inutile', 'vrai',
      'vraie', 'vrais', 'certain', 'certaine', 'ouverte', 'profond', 'mince', 'minces', 'epais', 'epaisse',
      'gros', 'grosse', 'maigre', 'rond', 'ronde', 'droit', 'droite', 'tordu', 'plate', 'aigu',
      'brillant', 'terne', 'nue', 'loin', 'lointain', 'proche', 'proches', 'ancien', 'ancienne', 'moderne',
      'unique', 'double', 'entier', 'entiere', 'demi', 'dernier', 'derniere', 'premier', 'premiere', 'severe',
      'serein', 'nerveux', 'timide', 'audacieux', 'fier', 'fiere', 'humble', 'tiede', 'cru', 'crue',
      'cuit', 'cuite', 'mure', 'malade', 'malades', 'blesse', 'vif', 'vive', 'muet', 'muette',
      'sourd', 'aveugle', 'enorme', 'immense', 'geant', 'geante', 'minuscule', 'splendide', 'affreux', 'joli',
      'jolie'],
    temps: ['heure', 'heures', 'jour', 'jours', 'nuit', 'nuits', 'mois', 'annee', 'annees', 'ans',
      'siecle', 'siecles', 'moment', 'moments', 'minute', 'minutes', 'seconde', 'secondes', 'semaine', 'semaines',
      'matin', 'matins', 'soir', 'soirs', 'midi', 'aube', 'aubes', 'coucher', 'saison', 'saisons',
      'ete', 'hiver', 'hivers', 'automne', 'printemps', 'hier', 'demain', 'bientot', 'tard', 'retard',
      'epoque', 'epoques', 'passe', 'futur', 'present', 'lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi',
      'samedi', 'dimanche', 'janvier', 'fevrier', 'mars', 'avril', 'mai', 'juin', 'juillet', 'aout',
      'septembre', 'octobre', 'novembre', 'decembre', 'date', 'dates', 'calendrier', 'duree', 'attente', 'debut',
      'debuts', 'fin', 'fins', 'periode', 'instant', 'toujours', 'jamais', 'souvent', 'parfois', 'maintenant',
      'alors', 'avant', 'apres', 'pendant', 'depuis', 'journee', 'soiree', 'veille', 'fete', 'fetes',
      'vacances', 'conge', 'congres', 'agenda', 'delai', 'horaire', 'rendez'],
    couleurs: ['rouge', 'rouges', 'vert', 'verte', 'verts', 'vertes', 'bleu', 'bleue', 'bleus', 'bleues',
      'jaune', 'jaunes', 'noir', 'noire', 'noirs', 'noires', 'blanc', 'blanche', 'blancs', 'blanches',
      'gris', 'grise', 'violet', 'violette', 'brun', 'brune', 'marron', 'dore', 'doree', 'argente',
      'beige', 'ivoire', 'pourpre', 'ocre', 'turquoise', 'indigo', 'lilas', 'ecarlate', 'carmin', 'bordeaux',
      'kaki', 'corail', 'emeraude', 'saphir', 'couleur', 'couleurs', 'teinte', 'teintes', 'nuance', 'nuances',
      'ton', 'tons', 'fonce'],
    objets: ['livre', 'livres', 'stylo', 'stylos', 'papier', 'papiers', 'cahier', 'cahiers', 'sac', 'sacs',
      'boite', 'boites', 'corde', 'cordes', 'clou', 'clous', 'marteau', 'aiguille', 'bouton', 'boutons',
      'parapluie', 'lunettes', 'valise', 'valises', 'chapeau', 'chapeaux', 'chaussure', 'gant', 'gants', 'echarpe',
      'bague', 'bagues', 'chaine', 'chaines', 'roue', 'roues', 'moteur', 'moteurs', 'bateau', 'bateaux',
      'navire', 'train', 'trains', 'avion', 'avions', 'voiture', 'voitures', 'velo', 'velos', 'moto',
      'motos', 'pont', 'ponts', 'route', 'routes', 'chemin', 'chemins', 'barriere', 'lanterne', 'crayon',
      'crayons', 'regle', 'regles', 'gomme', 'ciseaux', 'colle', 'ruban', 'rubans', 'ficelle', 'panier',
      'paniers', 'caisse', 'caisses', 'coffre', 'couvercle', 'bouchon', 'boulon', 'pince', 'pinces', 'scie',
      'scies', 'hache', 'haches', 'pelle', 'pelles', 'rateau', 'brouette', 'charrette', 'traineau', 'rame',
      'rames', 'voile', 'voiles', 'ancre', 'boussole', 'carte', 'cartes', 'jumelles', 'loupe', 'appareil',
      'camera', 'telephone', 'ecran', 'ecrans', 'clavier', 'cable', 'cables', 'pile', 'piles', 'torche',
      'monnaie', 'billet', 'billets', 'timbre', 'lettre', 'lettres', 'colis', 'journal', 'journaux', 'revue',
      'revues', 'affiche', 'drapeau', 'drapeaux', 'jouet', 'jouets', 'poupee', 'poupees', 'ballon', 'ballons',
      'balle', 'balles', 'des', 'puzzle'],
    lieux: ['ville', 'villes', 'village', 'villages', 'rue', 'rues', 'place', 'places', 'parc', 'parcs',
      'ecole', 'ecoles', 'eglise', 'eglises', 'musee', 'musees', 'theatre', 'magasin', 'magasins', 'banque',
      'banques', 'gare', 'gares', 'port', 'ports', 'aeroport', 'hopital', 'hotel', 'hotels', 'librairie',
      'chateau', 'chateaux', 'tour', 'tours', 'jardins', 'cour', 'quartier', 'quartiers', 'frontiere', 'region',
      'regions', 'pays', 'capitale', 'banlieue', 'ruelle', 'avenue', 'avenues', 'coin', 'coins', 'banc',
      'bancs', 'fontaine', 'statue', 'cinema', 'stade', 'stades', 'arene', 'cirque', 'foire', 'foires',
      'auberge', 'bar', 'bars', 'boucher', 'pharmacie', 'boucherie', 'atelier', 'ateliers', 'usine', 'usines',
      'moulin', 'mine', 'mines', 'carriere', 'quai', 'quais', 'phare', 'phares', 'refuge', 'cabane',
      'cabanes', 'tente', 'tentes', 'camp', 'camps', 'palais', 'villa', 'villas', 'immeuble', 'batiment',
      'bureaux', 'galerie', 'temple', 'temples', 'chapelle', 'ruines', 'tunnel', 'tunnels', 'carrefour', 'terrain',
      'terrains', 'verger'],
    travail: ['travail', 'travaux', 'equipe', 'equipes', 'projet', 'projets', 'tache', 'taches', 'reunion', 'reunions',
      'contrat', 'contrats', 'salaire', 'client', 'clients', 'facture', 'factures', 'objectif', 'resultat', 'resultats',
      'rapport', 'rapports', 'document', 'signature', 'accord', 'accords', 'entreprise', 'metier', 'metiers', 'poste',
      'postes', 'pause', 'pauses', 'role', 'roles', 'merite', 'prime', 'primes', 'patron', 'patrons',
      'chef', 'chefs', 'employe', 'employee', 'ouvrier', 'ouvriers', 'collegue', 'collegues', 'associe', 'patronne',
      'gerant', 'budget', 'benefice', 'perte', 'pertes', 'cout', 'couts', 'prix', 'remise', 'dette',
      'dettes', 'credit', 'paiement', 'recu', 'dossier', 'dossiers', 'medecin', 'infirmier', 'avocat', 'juge',
      'juges', 'soldat', 'marin', 'pilote', 'chauffeur', 'cuisinier', 'serveur', 'boulanger', 'tailleur', 'fermier',
      'pecheur', 'mineur', 'macon', 'plombier', 'peintre', 'ingenieur'],
    arts: ['art', 'arts', 'musique', 'chanson', 'chansons', 'chant', 'danses', 'tableau', 'tableaux', 'peinture',
      'pinceau', 'pinceaux', 'toile', 'toiles', 'statues', 'poeme', 'poemes', 'roman', 'romans', 'conte',
      'contes', 'film', 'films', 'acteur', 'actrice', 'scene', 'scenes', 'rythme', 'note', 'notes',
      'guitare', 'guitares', 'piano', 'pianos', 'violon', 'violons', 'flute', 'flutes', 'tambour', 'choeur',
      'melodie', 'dessin', 'dessins', 'croquis', 'exposition', 'artiste', 'artistes', 'auteur', 'auteurs', 'poete',
      'poetes', 'lecteur', 'chapitre', 'page', 'pages', 'titre', 'titres', 'intrigue', 'comedie', 'tragedie',
      'drame', 'drames', 'concert', 'concerts', 'orchestre', 'ballet', 'ballets', 'costume', 'masque', 'masques',
      'son', 'sons', 'silence', 'echo'],
    matieres: ['fer', 'fers', 'acier', 'cuivre', 'argent', 'plastique', 'tissu', 'tissus', 'laine', 'soie',
      'coton', 'cuir', 'marbre', 'granit', 'ciment', 'cire', 'quartz', 'diamant', 'bronze', 'plomb',
      'zinc', 'cristal', 'argile', 'liege', 'lin', 'velours', 'dentelle', 'metal', 'metaux', 'alliage',
      'etain', 'nickel', 'laiton', 'beton', 'brique', 'briques', 'tuile', 'tuiles', 'gravier', 'goudron',
      'resine', 'vernis', 'fibre', 'fibres'],
    general: ['chose', 'choses', 'facon', 'facons', 'partie', 'parties', 'point', 'points', 'signe', 'signes',
      'nom', 'noms', 'nombre', 'nombres', 'mot', 'mots', 'phrase', 'phrases', 'histoire', 'histoires',
      'idee', 'idees', 'reve', 'reves', 'souvenir', 'doute', 'doutes', 'choix', 'ordre', 'ordres',
      'cas', 'chance', 'destin', 'centre', 'centres', 'fond', 'fonds', 'bord', 'bords', 'ligne',
      'lignes', 'cercle', 'cercles', 'carre', 'carres', 'forme', 'formes', 'mesure', 'mesures', 'poids',
      'hauteur', 'largeur', 'longueur', 'espace', 'espaces', 'verite', 'mensonge', 'erreur', 'erreurs', 'faute',
      'fautes', 'raison', 'raisons', 'cause', 'causes', 'effet', 'effets', 'exemple', 'preuve', 'preuves',
      'question', 'reponse', 'reponses', 'probleme', 'solution', 'methode', 'systeme', 'plan', 'plans', 'conseil',
      'conseils', 'avis', 'nouvelles', 'discours', 'bruit', 'bruits', 'secret', 'secrets', 'mystere', 'surprise',
      'blague', 'jeu', 'jeux', 'cadeau', 'cadeaux', 'faveur', 'merci', 'excuse', 'excuses', 'salut',
      'visite', 'visites', 'voyage', 'voyages', 'depart', 'arrivee', 'retour', 'but', 'buts', 'pas',
      'trace', 'traces', 'force', 'forces', 'droits', 'devoirs', 'loi', 'lois', 'paix', 'guerre',
      'guerres', 'lutte', 'luttes', 'victoire', 'defaite', 'promesse', 'confiance', 'courage', 'peur', 'peurs',
      'joie', 'joies', 'douleur', 'amour', 'haine', 'colere', 'espoir'],
    communs: ['moi', 'toi', 'lui', 'elle', 'nous', 'vous', 'eux', 'elles', 'mon', 'mes',
      'tes', 'ses', 'notre', 'nos', 'votre', 'vos', 'leur', 'leurs', 'cet', 'cette',
      'ces', 'celui', 'celle', 'ceux', 'qui', 'que', 'quoi', 'dont', 'comment', 'quand',
      'combien', 'quel', 'quelle', 'quels', 'quelles', 'pourquoi', 'aussi', 'encore', 'deja', 'vraiment',
      'plutot', 'presque', 'trop', 'peu', 'beaucoup', 'assez', 'moins', 'plus', 'tres', 'bien',
      'mal', 'mieux', 'pire', 'devant', 'derriere', 'dessus', 'dessous', 'dedans', 'dehors', 'autour',
      'contre', 'sans', 'chez', 'parmi', 'selon', 'malgre', 'ensemble', 'seul', 'seule', 'seuls',
      'seules', 'chacun', 'quelqu', 'personne', 'rien', 'tout', 'toute', 'tous', 'toutes', 'autre',
      'autres', 'meme', 'memes', 'certains', 'plusieurs', 'chaque', 'aucun', 'aucune', 'donc', 'ainsi',
      'enfin', 'bonjour', 'bonsoir', 'adieu', 'pardon', 'oui', 'non'],
  },
  parole: [
    { word: 'mielleux', category: 'qualites', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'D’une douceur excessive et affectée, surtout dans la façon de parler.',
      translations: { it: 'mellifluo', en: 'mellifluous', es: 'meloso', de: 'honigsüß' } },
    { word: 'quartz', category: 'matieres', grammaticalType: 'noun', difficulty: 2, rarity: 3,
      definition: 'Minéral très dur et transparent, parmi les plus répandus de la croûte terrestre.',
      translations: { it: 'quarzo', en: 'quartz', es: 'cuarzo', de: 'Quarz' } },
    { word: 'zéphyr', category: 'nature', grammaticalType: 'noun', difficulty: 3, rarity: 4,
      definition: 'Vent léger et tiède qui souffle de l’ouest.',
      translations: { it: 'zefiro', en: 'zephyr', es: 'céfiro', de: 'Zephir' } },
    { word: 'crépuscule', category: 'temps', grammaticalType: 'noun', difficulty: 3, rarity: 4,
      definition: 'La lumière incertaine entre le coucher du soleil et la nuit.',
      translations: { it: 'crepuscolo', en: 'twilight', es: 'crepúsculo', de: 'Dämmerung' } },
    { word: 'éphémère', category: 'qualites', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Qui ne dure que très peu de temps.',
      translations: { it: 'effimero', en: 'ephemeral', es: 'efímero', de: 'flüchtig' } },
    { word: 'sagace', category: 'qualites', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Qui comprend vite et voit loin.',
      translations: { it: 'sagace', en: 'shrewd', es: 'sagaz', de: 'scharfsinnig' } },
    { word: 'méandre', category: 'nature', grammaticalType: 'noun', difficulty: 2, rarity: 3,
      definition: 'Boucle large d’une rivière ; par extension, un parcours sinueux.',
      translations: { it: 'meandro', en: 'meander', es: 'meandro', de: 'Mäander' } },
    { word: 'zénith', category: 'nature', grammaticalType: 'noun', difficulty: 3, rarity: 4,
      definition: 'Le point du ciel situé juste au-dessus de la tête.',
      translations: { it: 'zenit', en: 'zenith', es: 'cenit', de: 'Zenit' } },
    { word: 'laconique', category: 'qualites', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Qui s’exprime en très peu de mots.',
      translations: { it: 'laconico', en: 'terse', es: 'lacónico', de: 'knapp' } },
    { word: 'jovial', category: 'qualites', grammaticalType: 'adjective', difficulty: 2, rarity: 3,
      definition: 'D’une gaieté cordiale et communicative.',
      translations: { it: 'gioviale', en: 'jovial', es: 'jovial', de: 'jovial' } },
    { word: 'tenace', category: 'qualites', grammaticalType: 'adjective', difficulty: 2, rarity: 3,
      definition: 'Qui ne lâche pas prise, ni sur les choses ni sur ses idées.',
      translations: { it: 'tenace', en: 'tenacious', es: 'tenaz', de: 'hartnäckig' } },
    { word: 'diaphane', category: 'qualites', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Assez fin pour laisser passer la lumière.',
      translations: { it: 'diafano', en: 'diaphanous', es: 'diáfano', de: 'durchscheinend' } },
  ],
};
