/**
 * Italiano.
 *
 * Una lingua di Lexora e' fatta di tre cose:
 *
 *   alfabeto   le lettere che escono dal sacchetto, con quanto pesano
 *              (la frequenza: quante volte su cento ci si aspetta di
 *              vederle) e quanto valgono. La Q vale otto perche' in
 *              italiano senza la U non va da nessuna parte;
 *   gruppi     il grosso del dizionario, per categoria: qui conta che la
 *              parola esista e a che famiglia appartiene;
 *   parole     le voci scritte per esteso — definizione, traduzioni,
 *              rarita' — che sono quelle che il gioco mostra quando
 *              qualcuno le trova.
 *
 * Non e' un dizionario completo della lingua italiana e non pretende di
 * esserlo: e' un dizionario da partita, scelto perche' con dodici lettere
 * in campo ci si trovi sempre qualcosa. Cresce aggiungendo righe qui, e il
 * motore non se ne accorge.
 */

export const it = {
  id: 'it',
  nome: 'Italiano',
  locale: 'it-IT',
  /* In italiano gli accenti non distinguono le parole in un gioco di
     lettere: PERCHÉ e PERCHE sono la stessa cosa, e sul campo la É non
     esce. */
  tieniAccenti: false,
  digrammi: [],
  sostituzioni: {},

  /* peso = quanto spesso esce, valore = quanto paga */
  alfabeto: [
    { lettera: 'A', peso: 117, valore: 1 }, { lettera: 'E', peso: 118, valore: 1 },
    { lettera: 'I', peso: 113, valore: 1 }, { lettera: 'O', peso: 98, valore: 1 },
    { lettera: 'U', peso: 30, valore: 1 },  { lettera: 'R', peso: 64, valore: 1 },
    { lettera: 'T', peso: 56, valore: 1 },  { lettera: 'N', peso: 69, valore: 1 },
    { lettera: 'S', peso: 50, valore: 1 },  { lettera: 'L', peso: 65, valore: 1 },
    { lettera: 'C', peso: 45, valore: 2 },  { lettera: 'D', peso: 37, valore: 2 },
    { lettera: 'M', peso: 25, valore: 2 },  { lettera: 'P', peso: 31, valore: 2 },
    { lettera: 'B', peso: 9, valore: 3 },   { lettera: 'F', peso: 11, valore: 3 },
    { lettera: 'G', peso: 16, valore: 3 },  { lettera: 'V', peso: 21, valore: 3 },
    { lettera: 'H', peso: 15, valore: 4 },  { lettera: 'Z', peso: 9, valore: 5 },
    { lettera: 'Q', peso: 5, valore: 8 },
  ],

  /**
   * Da una parola, le forme da cui potrebbe derivare.
   *
   * Serve a tenere i plurali e le voci verbali fuori dalle parole segrete:
   * se GATTI deriva da GATTO e GATTO sta nel dizionario, GATTI e' un
   * plurale e non si fa indovinare. La regola non prova a capire da sola
   * se una parola e' plurale — sarebbe indovinare — chiede se il suo
   * singolare esiste, e quello e' un fatto.
   *
   * Vale anche per i verbi, che in italiano finiscono con le stesse
   * vocali: PARLO viene da PARLARE, CORRI da CORRERE. Una parola segreta
   * dev'essere una parola da vocabolario, non una sua forma.
   */
  formeBase: (p) => {
    const f = [];
    const senza = (n) => p.slice(0, -n);
    /* plurali: -o/-e → -i, -a → -e, con le grafie che cambiano */
    if (p.endsWith('CHI')) f.push(senza(3) + 'CO');
    if (p.endsWith('GHI')) f.push(senza(3) + 'GO');
    if (p.endsWith('CHE')) f.push(senza(3) + 'CA');
    if (p.endsWith('GHE')) f.push(senza(3) + 'GA');
    if (p.endsWith('I')) f.push(senza(1) + 'O', senza(1) + 'E', senza(1) + 'IO');
    if (p.endsWith('E')) f.push(senza(1) + 'A');
    /* femminili di aggettivi: -a/-e ← -o */
    if (p.endsWith('A')) f.push(senza(1) + 'O');
    /* voci verbali: dal presente e dal participio all'infinito */
    for (const [fine, radici] of [
      ['O', ['ARE', 'ERE', 'IRE']], ['I', ['ARE', 'ERE', 'IRE']], ['A', ['ARE']],
      ['E', ['ERE']], ['IAMO', ['ARE', 'ERE', 'IRE']], ['ATE', ['ARE']], ['ETE', ['ERE']],
      ['ITE', ['IRE']], ['ANO', ['ARE']], ['ONO', ['ERE', 'IRE']],
      ['ATO', ['ARE']], ['ATA', ['ARE']], ['UTO', ['ERE']], ['ITO', ['IRE']], ['ITA', ['IRE']],
    ]) {
      if (!p.endsWith(fine)) continue;
      for (const r of radici) f.push(p.slice(0, -fine.length) + r);
    }
    return f;
  },

  /* Dalla categoria dei verbi si fa indovinare solo l'infinito: CORRERE
     si', CORRI e VANNO no. Le forme regolari le prende gia' `formeBase`
     — CORRI viene da CORRERE, che c'e' — ma le irregolari no, e FACCIO
     o SARANNO come parole segrete sono peggio di un plurale. */
  verbi: { categoria: 'azioni', infinito: /(ARE|ERE|IRE)$/ },

  categorie: {
    animali: 'Animali', cibo: 'Cibo', casa: 'Casa', natura: 'Natura', corpo: 'Corpo',
    lavoro: 'Lavoro', tempo: 'Tempo', colori: 'Colori', oggetti: 'Oggetti',
    azioni: 'Azioni', qualita: 'Qualità', luoghi: 'Luoghi', arte: 'Arte', numeri: 'Numeri',
    materiali: 'Materiali', famiglia: 'Famiglia', scuola: 'Scuola', sport: 'Sport',
    salute: 'Salute', viaggio: 'Viaggio', sentimenti: 'Sentimenti', comuni: 'Parole comuni',
    generale: 'Generale',
  },

  gruppi: {
    animali: ['ape', 'api', 'cane', 'cani', 'cagna', 'cagne', 'gatto', 'gatti', 'gatta', 'gatte',
      'topo', 'topi', 'lupo', 'lupi', 'lupa', 'orso', 'orsi', 'orsa', 'cervo', 'cervi',
      'volpe', 'volpi', 'rana', 'rane', 'pesce', 'pesci', 'gallo', 'galli', 'gallina', 'galline',
      'oca', 'oche', 'anatra', 'anatre', 'mucca', 'mucche', 'cavallo', 'cavalli', 'cavalla', 'asino',
      'asini', 'pecora', 'pecore', 'capra', 'capre', 'maiale', 'maiali', 'coniglio', 'conigli', 'leone',
      'leoni', 'leonessa', 'tigre', 'tigri', 'zebra', 'zebre', 'gufo', 'gufi', 'corvo', 'corvi',
      'passero', 'passeri', 'aquila', 'aquile', 'serpente', 'serpenti', 'lucertola', 'lucertole', 'ragno', 'ragni',
      'formica', 'formiche', 'mosca', 'mosche', 'zanzara', 'zanzare', 'farfalla', 'farfalle', 'grillo', 'grilli',
      'delfino', 'delfini', 'balena', 'balene', 'squalo', 'squali', 'polpo', 'polpi', 'granchio', 'granchi',
      'riccio', 'ricci', 'talpa', 'talpe', 'cinghiale', 'cinghiali', 'falco', 'falchi', 'merlo', 'merli',
      'rondine', 'rondini', 'tartaruga', 'chiocciola', 'chiocciole', 'bruco', 'bruchi', 'scoiattolo', 'scoiattoli', 'cucciolo',
      'cuccioli', 'gregge', 'branco', 'branchi', 'stormo', 'stormi', 'nido', 'nidi', 'ala', 'ali',
      'zampa', 'zampe', 'coda', 'code', 'piuma', 'piume', 'pelo', 'peli', 'corno', 'corna',
      'zoccolo', 'zoccoli', 'artiglio', 'artigli', 'becco', 'becchi', 'muso', 'musi', 'criniera', 'zanna',
      'zanne', 'guscio', 'gusci', 'pulcino', 'pulcini', 'agnello', 'agnelli', 'vitello', 'vitelli', 'puledro',
      'gabbiano', 'gabbiani', 'cicogna', 'cicogne', 'pavone', 'pavoni', 'colomba', 'colombe', 'piccione', 'piccioni',
      'usignolo', 'civetta', 'civette', 'lumaca', 'lumache', 'verme', 'vermi', 'cavalletta', 'lucciola', 'lucciole',
      'sanguisuga', 'girino', 'girini', 'rospo', 'rospi', 'anguilla', 'anguille', 'trota', 'trote', 'tonno',
      'tonni', 'sardina', 'sardine', 'aragosta', 'gambero', 'gamberi', 'cozza', 'cozze', 'medusa', 'meduse',
      'stambecco', 'camoscio', 'camosci', 'lince', 'linci', 'furetto', 'donnola', 'donnole', 'castoro', 'castori',
      'lontra', 'lontre', 'foca', 'foche', 'orca', 'orche', 'canguro', 'canguri', 'panda', 'gorilla',
      'scimmia', 'scimmie', 'elefante', 'elefanti', 'giraffa', 'giraffe', 'iguana', 'ippopotamo', 'cammello', 'cammelli',
      'dromedario', 'iena', 'iene', 'sciacallo', 'gazzella', 'gazzelle', 'antilope', 'bufalo', 'bufali', 'toro',
      'tori', 'bue', 'buoi', 'porcello', 'somaro', 'somari', 'mulo', 'muli', 'gattino', 'gattini',
      'cagnolino', 'topolino', 'topolini', 'lombrico', 'lombrichi', 'grifone', 'ghepardo'],
    cibo: ['pane', 'pani', 'pasta', 'paste', 'riso', 'olio', 'oli', 'sale', 'pepe', 'burro',
      'latte', 'uovo', 'uova', 'carne', 'carni', 'pollo', 'polli', 'mela', 'mele', 'pera',
      'pere', 'uva', 'fico', 'fichi', 'limone', 'limoni', 'arancia', 'arance', 'banana', 'banane',
      'ciliegia', 'ciliegie', 'fragola', 'fragole', 'pesca', 'pesche', 'melone', 'meloni', 'patata', 'patate',
      'carota', 'carote', 'cipolla', 'cipolle', 'aglio', 'insalata', 'insalate', 'pomodoro', 'pomodori', 'zucca',
      'zucche', 'fagiolo', 'fagioli', 'lenticchia', 'lenticchie', 'noce', 'noci', 'mandorla', 'mandorle', 'miele',
      'zucchero', 'farina', 'farine', 'torta', 'torte', 'biscotto', 'biscotti', 'gelato', 'gelati', 'caffe',
      'vino', 'vini', 'birra', 'birre', 'acqua', 'acque', 'brodo', 'brodi', 'zuppa', 'zuppe',
      'salsa', 'salse', 'formaggio', 'formaggi', 'prosciutto', 'dolce', 'dolci', 'panino', 'panini', 'pizza',
      'pizze', 'sugo', 'sughi', 'ragu', 'crema', 'creme', 'panna', 'succo', 'succhi', 'tisana',
      'tisane', 'spremuta', 'spremute', 'bibita', 'bibite', 'cena', 'cene', 'pranzo', 'pranzi', 'colazione',
      'merenda', 'merende', 'spuntino', 'antipasto', 'contorno', 'contorni', 'piatto', 'piatti', 'ricetta', 'ricette',
      'sapore', 'sapori', 'odore', 'odori', 'gusto', 'gusti', 'fame', 'sete', 'grano', 'orzo',
      'avena', 'segale', 'mais', 'polenta', 'gnocchi', 'lasagna', 'lasagne', 'risotto', 'minestra', 'minestre',
      'crostata', 'crostate', 'budino', 'budini', 'caramella', 'caramelle', 'cioccolato', 'marmellata', 'confettura', 'burrata',
      'ricotta', 'mozzarella', 'parmigiano', 'salame', 'salami', 'salsiccia', 'salsicce', 'bistecca', 'arrosto', 'arrosti',
      'fritto', 'fritti', 'lesso', 'brodino', 'uvetta', 'prugna', 'prugne', 'albicocca', 'albicocche', 'anguria',
      'angurie', 'ananas', 'sorbetto', 'ghiacciolo', 'frittata', 'cocco', 'dattero', 'datteri', 'castagna', 'castagne',
      'nocciola', 'nocciole', 'pistacchio', 'pinolo', 'pinoli', 'oliva', 'olive', 'capperi', 'basilico', 'prezzemolo',
      'rosmarino', 'origano', 'salvia', 'menta', 'cannella', 'vaniglia', 'zafferano', 'peperone', 'peperoni', 'melanzana',
      'melanzane', 'zucchina', 'zucchine', 'spinaci', 'cavolo', 'cavoli', 'broccolo', 'broccoli', 'finocchio', 'finocchi',
      'sedano', 'porro', 'porri', 'rapa', 'rape', 'ravanello', 'lattuga', 'rucola', 'radicchio', 'cetriolo',
      'cetrioli', 'pisello', 'piselli', 'cece', 'ceci', 'fava', 'fave', 'soia', 'tofu', 'aceto',
      'senape', 'maionese', 'boccone', 'bocconi', 'briciola', 'briciole', 'crosta', 'croste', 'mollica', 'impasto',
      'lievito', 'padella', 'padelle', 'teglia', 'teglie', 'mestolo', 'mestoli', 'grembiule', 'tovaglia', 'tovaglie'],
    casa: ['casa', 'case', 'porta', 'porte', 'muro', 'muri', 'tetto', 'tetti', 'scala', 'scale',
      'stanza', 'stanze', 'cucina', 'cucine', 'bagno', 'bagni', 'letto', 'letti', 'sedia', 'sedie',
      'tavolo', 'tavoli', 'divano', 'divani', 'armadio', 'armadi', 'lampada', 'lampade', 'finestra', 'finestre',
      'chiave', 'chiavi', 'tappeto', 'tappeti', 'specchio', 'specchi', 'cassetto', 'cassetti', 'mensola', 'mensole',
      'tenda', 'tende', 'cuscino', 'cuscini', 'coperta', 'coperte', 'bicchiere', 'bicchieri', 'forchetta', 'forchette',
      'coltello', 'coltelli', 'cucchiaio', 'cucchiai', 'pentola', 'pentole', 'forno', 'forni', 'soffitto', 'soffitti',
      'pavimento', 'balcone', 'balconi', 'terrazza', 'terrazze', 'garage', 'cantina', 'cantine', 'soffitta', 'ingresso',
      'ingressi', 'corridoio', 'corridoi', 'salotto', 'salotti', 'camera', 'camere', 'studio', 'studi', 'sgabello',
      'sgabelli', 'poltrona', 'poltrone', 'scaffale', 'scaffali', 'libreria', 'librerie', 'comodino', 'comodini', 'lenzuolo',
      'lenzuola', 'federa', 'federe', 'materasso', 'tovagliolo', 'vassoio', 'vassoi', 'tazza', 'tazze', 'ciotola',
      'ciotole', 'brocca', 'brocche', 'caraffa', 'caraffe', 'bottiglia', 'bottiglie', 'barattolo', 'vaso', 'vasi',
      'secchio', 'secchi', 'scopa', 'scope', 'straccio', 'stracci', 'spugna', 'spugne', 'sapone', 'saponi',
      'rubinetto', 'lavandino', 'doccia', 'docce', 'vasca', 'vasche', 'spazzola', 'spazzole', 'pettine', 'pettini',
      'campanello', 'serratura', 'maniglia', 'maniglie', 'cardine', 'cardini', 'soglia', 'soglie', 'gradino', 'gradini',
      'ringhiera', 'camino', 'camini', 'stufa', 'stufe', 'radiatore', 'presa', 'prese', 'lampadina', 'filo',
      'fili', 'quadro', 'quadri', 'cornice', 'cornici', 'orologio'],
    natura: ['albero', 'alberi', 'foglia', 'foglie', 'fiore', 'fiori', 'radice', 'radici', 'ramo', 'rami',
      'erba', 'erbe', 'prato', 'prati', 'bosco', 'boschi', 'monte', 'monti', 'valle', 'valli',
      'fiume', 'fiumi', 'lago', 'laghi', 'mare', 'mari', 'onda', 'onde', 'sabbia', 'roccia',
      'rocce', 'pietra', 'pietre', 'terra', 'terre', 'cielo', 'cieli', 'sole', 'soli', 'luna',
      'lune', 'stella', 'stelle', 'nube', 'nubi', 'nuvola', 'nuvole', 'pioggia', 'piogge', 'neve',
      'nevi', 'vento', 'venti', 'nebbia', 'nebbie', 'tuono', 'tuoni', 'lampo', 'lampi', 'ghiaccio',
      'isola', 'isole', 'deserto', 'deserti', 'grotta', 'grotte', 'collina', 'colline', 'pianura', 'pianure',
      'sorgente', 'sorgenti', 'cascata', 'cascate', 'seme', 'semi', 'frutto', 'frutti', 'spina', 'spine',
      'tronco', 'tronchi', 'corteccia', 'chioma', 'chiome', 'germoglio', 'bocciolo', 'petalo', 'petali', 'polline',
      'rosa', 'rose', 'giglio', 'gigli', 'tulipano', 'tulipani', 'papavero', 'papaveri', 'margherita', 'violetta',
      'girasole', 'girasoli', 'ortica', 'ortiche', 'muschio', 'felce', 'felci', 'canna', 'canne', 'giunco',
      'cespuglio', 'siepe', 'siepi', 'quercia', 'querce', 'pino', 'pini', 'abete', 'abeti', 'faggio',
      'olmo', 'olmi', 'salice', 'salici', 'pioppo', 'pioppi', 'betulla', 'betulle', 'palma', 'palme',
      'ulivo', 'ulivi', 'vite', 'viti', 'fungo', 'funghi', 'sasso', 'sassi', 'ciottolo', 'ciottoli',
      'fango', 'polvere', 'cenere', 'ceneri', 'fumo', 'fiamma', 'fiamme', 'fuoco', 'fuochi', 'brace',
      'scintilla', 'rugiada', 'brina', 'gelo', 'grandine', 'temporale', 'tempesta', 'uragano', 'tornado', 'alluvione',
      'siccita', 'marea', 'maree', 'corrente', 'correnti', 'riva', 'rive', 'sponda', 'sponde', 'scogliera',
      'scoglio', 'scogli', 'baia', 'baie', 'golfo', 'golfi', 'stretto', 'canale', 'canali', 'ruscello',
      'torrente', 'torrenti', 'stagno', 'stagni', 'palude', 'paludi', 'oasi', 'duna', 'dune', 'ghiacciaio',
      'vetta', 'vette', 'cima', 'cime', 'pendio', 'crinale', 'burrone', 'gola', 'gole', 'sentiero'],
    corpo: ['testa', 'teste', 'occhio', 'occhi', 'naso', 'nasi', 'bocca', 'bocche', 'orecchio', 'orecchie',
      'mano', 'mani', 'dito', 'dita', 'braccio', 'braccia', 'gamba', 'gambe', 'piede', 'piedi',
      'cuore', 'cuori', 'sangue', 'osso', 'ossa', 'pelle', 'pelli', 'capello', 'capelli', 'dente',
      'denti', 'lingua', 'lingue', 'spalla', 'spalle', 'schiena', 'schiene', 'ginocchio', 'gomito', 'gomiti',
      'labbro', 'labbra', 'unghia', 'unghie', 'polso', 'polsi', 'collo', 'colli', 'viso', 'visi',
      'fronte', 'fronti', 'mento', 'menti', 'petto', 'petti', 'nervo', 'nervi', 'muscolo', 'muscoli',
      'tendine', 'tendini', 'vena', 'vene', 'arteria', 'arterie', 'polmone', 'polmoni', 'fegato', 'stomaco',
      'rene', 'reni', 'cervello', 'cranio', 'crani', 'guancia', 'guance', 'ciglio', 'ciglia', 'palpebra',
      'palpebre', 'pupilla', 'pupille', 'iride', 'nuca', 'ascella', 'ascelle', 'fianco', 'fianchi', 'anca',
      'anche', 'coscia', 'cosce', 'caviglia', 'caviglie', 'tallone', 'talloni', 'pianta', 'piante', 'palmo',
      'palmi', 'pollice', 'pollici', 'indice', 'indici', 'mignolo', 'mignoli', 'nocca', 'nocche', 'costola',
      'costole', 'bacino', 'bacini', 'colonna', 'colonne', 'midollo', 'saliva', 'sudore', 'lacrima', 'lacrime',
      'respiro', 'respiri', 'battito', 'battiti', 'voce', 'voci', 'sguardo', 'sguardi', 'sorriso', 'sorrisi',
      'passo', 'passi', 'gesto', 'gesti', 'grasso', 'peso', 'statura'],
    lavoro: ['lavoro', 'lavori', 'ufficio', 'uffici', 'squadra', 'squadre', 'progetto', 'progetti', 'compito', 'compiti',
      'riunione', 'riunioni', 'contratto', 'contratti', 'stipendio', 'stipendi', 'collega', 'colleghi', 'capo', 'capi',
      'cliente', 'clienti', 'fattura', 'fatture', 'agenda', 'agende', 'scadenza', 'scadenze', 'obiettivo', 'obiettivi',
      'risultato', 'risultati', 'relazione', 'relazioni', 'documento', 'documenti', 'firma', 'firme', 'accordo', 'accordi',
      'impresa', 'imprese', 'mestiere', 'mestieri', 'turno', 'turni', 'pausa', 'pause', 'ferie', 'carriera',
      'carriere', 'ruolo', 'ruoli', 'merito', 'meriti', 'premio', 'premi', 'formazione', 'azienda', 'aziende',
      'reparto', 'reparti', 'settore', 'settori', 'colloquio', 'colloqui', 'assunzione', 'dipendente', 'dipendenti', 'operaio',
      'operai', 'impiegato', 'impiegati', 'direttore', 'dirigente', 'dirigenti', 'segretario', 'tecnico', 'tecnici', 'ingegnere',
      'medico', 'medici', 'infermiere', 'maestro', 'maestri', 'maestra', 'maestre', 'professore', 'avvocato', 'avvocati',
      'notaio', 'notai', 'giudice', 'giudici', 'poliziotto', 'pompiere', 'pompieri', 'soldato', 'soldati', 'marinaio',
      'pilota', 'piloti', 'autista', 'autisti', 'cuoco', 'cuochi', 'cameriere', 'panettiere', 'macellaio', 'sarto',
      'sarti', 'calzolaio', 'falegname', 'muratore', 'muratori', 'idraulico', 'meccanico', 'elettrauto', 'fioraio', 'contadino',
      'contadini', 'pescatore', 'pastore', 'pastori', 'minatore', 'minatori', 'artigiano', 'artigiani', 'commesso', 'commessi',
      'venditore', 'compratore', 'padrone', 'padroni', 'socio', 'soci', 'guadagno', 'guadagni', 'perdita', 'perdite',
      'spesa', 'spese', 'costo', 'costi', 'prezzo', 'prezzi', 'sconto', 'sconti', 'debito', 'debiti',
      'credito', 'crediti', 'conto', 'conti', 'bilancio', 'bilanci', 'busta', 'buste', 'timbro', 'timbri',
      'modulo', 'moduli', 'pratica', 'pratiche', 'archivio', 'archivi', 'scrivania', 'scrivanie', 'schermo', 'schermi',
      'tastiera', 'tastiere', 'stampante', 'telefono', 'telefoni', 'messaggio', 'messaggi', 'lettera', 'lettere', 'pacco'],
    azioni: ['fare', 'faccio', 'fai', 'fanno', 'fatto', 'fatta', 'fatti', 'fatte', 'dire', 'dico',
      'dici', 'dice', 'diciamo', 'dite', 'dicono', 'detto', 'detta', 'detti', 'andare', 'vado',
      'vai', 'andiamo', 'andate', 'vanno', 'andato', 'andata', 'andati', 'venire', 'vengo', 'vieni',
      'viene', 'veniamo', 'venite', 'vengono', 'venuto', 'venuta', 'stare', 'sto', 'stai', 'stiamo',
      'state', 'stanno', 'stato', 'stata', 'stati', 'dare', 'dai', 'diamo', 'date', 'danno',
      'dato', 'data', 'dati', 'vedere', 'vedo', 'vedi', 'vede', 'vediamo', 'vedete', 'vedono',
      'visto', 'vista', 'visti', 'viste', 'sapere', 'sai', 'sappiamo', 'sapete', 'sanno', 'saputo',
      'volere', 'voglio', 'vuoi', 'vuole', 'vogliamo', 'volete', 'vogliono', 'voluto', 'potere', 'posso',
      'puoi', 'puo', 'possiamo', 'potete', 'possono', 'potuto', 'dovere', 'devo', 'devi', 'deve',
      'dobbiamo', 'dovete', 'devono', 'dovuto', 'essere', 'sono', 'sei', 'siamo', 'siete', 'avere',
      'hai', 'abbiamo', 'avete', 'hanno', 'avuto', 'parlare', 'parlo', 'parli', 'parla', 'parliamo',
      'parlate', 'parlano', 'parlato', 'parlata', 'sentire', 'sento', 'senti', 'sente', 'sentiamo', 'sentite',
      'sentono', 'sentito', 'sentita', 'guardare', 'guardo', 'guardi', 'guarda', 'guardate', 'guardano', 'guardato',
      'pensare', 'penso', 'pensi', 'pensa', 'pensiamo', 'pensate', 'pensano', 'pensato', 'credere', 'credo',
      'credi', 'crede', 'crediamo', 'credete', 'credono', 'creduto', 'capire', 'capisco', 'capisci', 'capisce',
      'capiamo', 'capite', 'capito', 'capita', 'leggere', 'leggo', 'leggi', 'legge', 'leggiamo', 'leggete',
      'leggono', 'letta', 'scrivere', 'scrivo', 'scrivi', 'scrive', 'scriviamo', 'scrivete', 'scrivono', 'scritto',
      'scritta', 'scritti', 'contare', 'conta', 'contiamo', 'contate', 'contano', 'contato', 'correre', 'corro',
      'corri', 'corre', 'corriamo', 'correte', 'corrono', 'corso', 'corsa', 'corse', 'saltare', 'salto',
      'salti', 'salta', 'saltiamo', 'saltate', 'saltano', 'saltato', 'nuotare', 'nuoto', 'nuoti', 'nuota',
      'nuotiamo', 'nuotate', 'nuotano', 'nuotato', 'volare', 'volo', 'voli', 'vola', 'voliamo', 'volate',
      'volano', 'volato', 'cadere', 'cado', 'cadi', 'cade', 'cadiamo', 'cadete', 'cadono', 'caduto',
      'caduta', 'salire', 'salgo', 'sali', 'saliamo', 'salite', 'salgono', 'salito', 'scendere', 'scendo',
      'scendi', 'scende', 'scendono', 'sceso', 'scesa', 'aprire', 'apro', 'apri', 'apre', 'apriamo',
      'aprite', 'aprono', 'aperto', 'aperta', 'aperti', 'chiudere', 'chiudo', 'chiudi', 'chiude', 'chiudono',
      'chiuso', 'chiusa', 'chiusi', 'prendere', 'prendo', 'prendi', 'prende', 'prendono', 'preso', 'presi',
      'lasciare', 'lascio', 'lasci', 'lascia', 'lasciate', 'lasciano', 'lasciato', 'portare', 'porto', 'porti',
      'portiamo', 'portate', 'portano', 'portato', 'portata', 'mettere', 'metto', 'metti', 'mette', 'mettiamo',
      'mettete', 'mettono', 'messo', 'messa', 'messi', 'togliere', 'tolgo', 'togli', 'toglie', 'tolgono',
      'tolto', 'tolta', 'girare', 'giro', 'giri', 'gira', 'giriamo', 'girate', 'girano', 'girato',
      'tornare', 'torno', 'torni', 'torna', 'torniamo', 'tornate', 'tornano', 'tornato', 'partire', 'parto',
      'parti', 'parte', 'partiamo', 'partite', 'partono', 'partito', 'partita', 'restare', 'resto', 'resti',
      'resta', 'restiamo', 'restate', 'restano', 'restato', 'cercare', 'cerco', 'cerchi', 'cerca', 'cerchiamo',
      'cercate', 'cercano', 'cercato', 'trovare', 'trovo', 'trovi', 'trova', 'troviamo', 'trovate', 'trovano',
      'trovato', 'trovata', 'perdere', 'perdo', 'perdi', 'perde', 'perdono', 'perso', 'persa', 'persi',
      'vincere', 'vinco', 'vinci', 'vince', 'vinciamo', 'vincete', 'vincono', 'vinto', 'vinta', 'giocare',
      'gioco', 'giochi', 'gioca', 'giochiamo', 'giocate', 'giocano', 'giocato', 'lavorare', 'lavora', 'lavorano',
      'lavorato', 'dormire', 'dormo', 'dormi', 'dorme', 'dormiamo', 'dormite', 'dormono', 'dormito', 'mangiare',
      'mangio', 'mangi', 'mangia', 'mangiate', 'mangiano', 'mangiato', 'bere', 'bevo', 'bevi', 'beve',
      'beviamo', 'bevete', 'bevono', 'bevuto', 'ridere', 'rido', 'ridi', 'ride', 'ridiamo', 'ridete',
      'ridono', 'piangere', 'piango', 'piangi', 'piange', 'piangono', 'pianto', 'cantare', 'canto', 'canti',
      'canta', 'cantiamo', 'cantate', 'cantano', 'cantato', 'ballare', 'ballo', 'balli', 'balla', 'balliamo',
      'ballate', 'ballano', 'ballato', 'suonare', 'suono', 'suoni', 'suona', 'suoniamo', 'suonate', 'suonano',
      'suonato', 'rompere', 'rompo', 'rompi', 'rompe', 'rompono', 'rotto', 'rotta', 'rotti', 'pulire',
      'pulisco', 'pulisci', 'pulisce', 'puliamo', 'pulite', 'pulito', 'pulita', 'lavare', 'lavo', 'lavi',
      'lava', 'laviamo', 'lavate', 'lavano', 'lavato', 'cucinare', 'cucino', 'cucini', 'cucinano', 'cucinato',
      'aiutare', 'aiuto', 'aiuti', 'aiuta', 'aiutiamo', 'aiutate', 'aiutano', 'aiutato', 'spiegare', 'spiego',
      'spieghi', 'spiega', 'spiegano', 'spiegato', 'imparare', 'imparo', 'impari', 'impara', 'imparano', 'imparato',
      'insegnare', 'insegno', 'insegni', 'insegna', 'insegnano', 'chiamare', 'chiamo', 'chiami', 'chiama', 'chiamano',
      'chiamato', 'amare', 'amo', 'ami', 'ama', 'amiamo', 'amate', 'amano', 'amato', 'amata',
      'odiare', 'odio', 'odi', 'odia', 'odiano', 'odiato', 'sperare', 'spero', 'speri', 'spera',
      'sperano', 'sperato', 'temere', 'temo', 'temi', 'teme', 'temono', 'temuto', 'ricordare', 'ricordo',
      'ricordi', 'ricorda', 'ricordano', 'dimentico', 'scordare', 'scordo', 'scordi', 'scorda', 'aspettare', 'aspetto',
      'aspetti', 'aspetta', 'aspettano', 'crescere', 'cresco', 'cresci', 'cresce', 'crescono', 'nascere', 'nasco',
      'nasci', 'nasce', 'nascono', 'nato', 'nata', 'nati', 'morire', 'muoio', 'muori', 'muore',
      'moriamo', 'morite', 'muoiono', 'morto', 'morta', 'morti', 'vivere', 'vivo', 'vivi', 'vive',
      'viviamo', 'vivete', 'vivono', 'vissuto', 'comprare', 'compro', 'compri', 'compra', 'comprano', 'comprato',
      'vendere', 'vendo', 'vendi', 'vende', 'vendono', 'venduto', 'pagare', 'pago', 'paghi', 'paga',
      'paghiamo', 'pagate', 'pagano', 'pagato', 'costruire', 'costruisco', 'costruisce', 'costruito', 'chiedere', 'chiedo',
      'chiedi', 'chiede', 'chiedono', 'chiesto', 'chiesta', 'rispondere', 'rispondo', 'rispondi', 'risponde', 'risposto',
      'risposta', 'guidare', 'guido', 'guidi', 'guida', 'guidano', 'guidato', 'viaggiare', 'viaggio', 'viaggi',
      'viaggia', 'entrare', 'entro', 'entri', 'entra', 'entriamo', 'entrate', 'entrano', 'entrato', 'uscire',
      'esco', 'esci', 'esce', 'usciamo', 'uscite', 'escono', 'uscito', 'seguire', 'seguo', 'segui',
      'segue', 'seguono', 'seguito', 'toccare', 'tocco', 'tocchi', 'tocca', 'toccano', 'toccato', 'tenere',
      'tengo', 'tieni', 'tiene', 'teniamo', 'tenete', 'tengono', 'tenuto', 'tirare', 'tiro', 'tiri',
      'tira', 'tirano', 'spingere', 'spingo', 'spingi', 'spinge', 'spingono', 'spinto', 'colpire', 'colpisco',
      'colpisce', 'colpito', 'gettare', 'getto', 'getti', 'getta', 'gettano', 'nascondere', 'nascondo', 'nasconde',
      'nascosto', 'nascosta', 'mostrare', 'mostro', 'mostri', 'mostra', 'mostrano', 'mostrato', 'provare', 'provo',
      'provi', 'prova', 'provano', 'provato', 'usare', 'uso', 'usi', 'usa', 'usiamo', 'usate',
      'usano', 'usato', 'innevare', 'innevo', 'innevi', 'inneva', 'innevato', 'nevicare', 'nevica', 'nevicato',
      'gelare', 'gela', 'grandinare', 'grandina', 'grandinato', 'tuonare', 'tuona', 'tuonato', 'lampeggio', 'lampeggi',
      'lampeggia', 'albeggiare', 'albeggia', 'albeggiato', 'soffiare', 'soffio', 'soffi', 'soffia', 'soffiato', 'gocciolare',
      'gocciolo', 'goccioli', 'gocciola', 'gocciolato', 'allagare', 'allago', 'allaghi', 'allaga', 'allagato', 'seccare',
      'seccato', 'bagnare', 'bagna', 'asciugare', 'asciugo', 'asciughi', 'asciuga', 'asciugato', 'scaldare', 'scaldo',
      'scaldi', 'scalda', 'scaldato', 'raffreddo', 'raffreddi', 'raffredda', 'bruciare', 'brucio', 'bruci', 'brucia',
      'bruciato', 'fumare', 'fumi', 'fuma', 'fumato', 'abbraccio', 'abbracci', 'abbraccia', 'baciare', 'bacio',
      'baci', 'bacia', 'baciato', 'salutare', 'saluta', 'salutato', 'ringrazio', 'ringrazi', 'ringrazia', 'scusare',
      'scuso', 'scusi', 'scusato', 'invitare', 'invita', 'invitato', 'ospitare', 'ospito', 'ospita', 'ospitato',
      'presentare', 'presento', 'presenti', 'presenta', 'presentato', 'incontrare', 'incontra', 'incontrato', 'telefonare', 'telefona',
      'telefonato', 'avvisare', 'avvisa', 'avvisato', 'informare', 'informo', 'informi', 'informa', 'informato', 'annunciare',
      'annuncio', 'annunci', 'annuncia', 'annunciato', 'raccontare', 'racconta', 'raccontato', 'narrare', 'narro', 'narri',
      'narra', 'narrato', 'elencare', 'elenco', 'elenchi', 'elenca', 'elencato', 'nominare', 'nomino', 'nomini',
      'nomina', 'nominato', 'firmare', 'firmo', 'firmi', 'firmato', 'disegnare', 'disegna', 'disegnato', 'colorare',
      'coloro', 'colora', 'cancellare', 'cancella', 'cancellato', 'copiare', 'copio', 'copi', 'copia', 'copiato',
      'stampare', 'stampo', 'stampi', 'stampato', 'piegare', 'piego', 'pieghi', 'piega', 'piegato', 'tagliare',
      'taglia', 'tagliato', 'incollare', 'incollo', 'incolli', 'incolla', 'incollato', 'legare', 'lego', 'leghi',
      'legato', 'slegare', 'slego', 'sleghi', 'slega', 'slegato', 'annodare', 'annodo', 'annodi', 'annoda',
      'annodato', 'filare', 'zappare', 'zappo', 'zappi', 'zappato', 'seminare', 'semino', 'semini', 'semina',
      'seminato', 'piantare', 'pianti', 'piantato', 'potare', 'poto', 'poti', 'pota', 'potato', 'innaffiare',
      'innaffio', 'innaffi', 'innaffia', 'innaffiato', 'concimare', 'concimo', 'concimi', 'concima', 'concimato', 'arare',
      'aro', 'ari', 'ara', 'arato', 'pescare', 'pesco', 'peschi', 'pescato', 'cacciare', 'caccio',
      'cacci', 'caccia', 'cacciato', 'allevare', 'allevo', 'allevi', 'alleva', 'allevato', 'pascolare', 'pascola',
      'pascolato', 'sfamare', 'sfamo', 'sfami', 'sfama', 'sfamato', 'riparare', 'riparo', 'ripari', 'ripara',
      'riparato', 'aggiustare', 'aggiusto', 'aggiusti', 'aggiusta', 'aggiustato', 'smontare', 'smonto', 'smonti', 'smonta',
      'smontato', 'montare', 'monto', 'monta', 'montato', 'avvitare', 'avvito', 'avviti', 'avvita', 'avvitato',
      'inchiodare', 'inchiodo', 'inchiodi', 'inchioda', 'inchiodato', 'martellare', 'martella', 'martellato', 'limare', 'limo',
      'limi', 'lima', 'limato', 'levigare', 'levigo', 'levighi', 'leviga', 'levigato', 'verniciare', 'vernicio',
      'vernicia', 'verniciato', 'intonacare', 'intonaco', 'intonachi', 'intonaca', 'intonacato', 'murare', 'mura', 'murato',
      'scavare', 'scavo', 'scavi', 'scava', 'scavato', 'svuotare', 'svuoto', 'svuoti', 'svuota', 'svuotato',
      'caricare', 'carico', 'carichi', 'carica', 'caricato', 'scaricare', 'scarico', 'scarichi', 'scarica', 'scaricato',
      'spostare', 'sposto', 'sposti', 'sposta', 'spostato', 'sollevare', 'sollevo', 'sollevi', 'solleva', 'sollevato',
      'abbassare', 'abbasso', 'abbassi', 'abbassa', 'abbassato', 'alzare', 'alzo', 'alzi', 'alza', 'alzato',
      'posare', 'poso', 'posi', 'posa', 'posato', 'appoggiare', 'appoggio', 'appoggi', 'appoggia', 'appoggiato',
      'staccare', 'stacco', 'stacchi', 'stacca', 'staccato', 'attaccare', 'attacco', 'attacchi', 'attacca', 'attaccato',
      'schiaccio', 'schiacci', 'schiaccia', 'allargare', 'allargo', 'allarghi', 'allarga', 'allargato', 'stirare', 'stiro',
      'stiri', 'stira', 'stirato', 'srotolare', 'srotolo', 'srotoli', 'srotola', 'srotolato', 'arrotolare', 'arrotolo',
      'arrotoli', 'arrotola', 'arrotolato', 'rotolare', 'rotolo', 'rotoli', 'rotola', 'rotolato', 'scivolare', 'scivoli',
      'scivola', 'scivolato', 'strisciare', 'striscio', 'strisci', 'striscia', 'strisciato', 'arrampico', 'arrampichi', 'arrampica',
      'saltellare', 'saltello', 'saltelli', 'saltella', 'saltellato', 'zoppicare', 'zoppico', 'zoppichi', 'zoppica', 'zoppicato',
      'trottare', 'trotto', 'trotti', 'trotta', 'trottato', 'galoppare', 'galoppo', 'galoppi', 'galoppa', 'galoppato',
      'volteggio', 'volteggi', 'volteggia', 'danzare', 'danzo', 'danzi', 'danzato', 'marciare', 'marci', 'marciato',
      'sfilare', 'sfilo', 'sfili', 'sfila', 'sfilato', 'parcheggio', 'parcheggi', 'parcheggia', 'frenare', 'frena',
      'frenato', 'accelerare', 'accelero', 'acceleri', 'accelera', 'accelerato', 'sterzare', 'sterzo', 'sterzi', 'sterza',
      'sterzato', 'navigare', 'navigo', 'navighi', 'naviga', 'navigato', 'remare', 'rema', 'remato', 'veleggiare',
      'veleggio', 'veleggi', 'veleggia', 'veleggiato', 'atterrare', 'atterro', 'atterri', 'atterra', 'atterrato', 'decollare',
      'decolli', 'decolla', 'decollato', 'arrivare', 'arriva', 'arrivato', 'passare', 'passa', 'attraverso', 'attraversi',
      'attraversa', 'superare', 'supero', 'superi', 'supera', 'superato', 'oltrepasso', 'oltrepassi', 'oltrepassa', 'aggirare',
      'aggiro', 'aggiri', 'aggira', 'aggirato', 'sorpassare', 'sorpasso', 'sorpassi', 'sorpassa', 'sorpassato', 'fermare',
      'fermo', 'fermi', 'ferma', 'fermato', 'bloccare', 'blocco', 'blocchi', 'blocca', 'bloccato', 'liberare',
      'liberato', 'catturare', 'catturo', 'catturi', 'cattura', 'catturato', 'scappare', 'scappo', 'scappi', 'scappa',
      'scappato', 'spiare', 'spio', 'spii', 'spia', 'spiato', 'osservare', 'osservo', 'osservi', 'osserva',
      'osservato', 'fissare', 'fisso', 'fissi', 'fissa', 'fissato', 'sbirciare', 'sbircio', 'sbirci', 'sbircia',
      'sbirciato', 'notare', 'noto', 'noti', 'notato', 'ascoltare', 'ascolto', 'ascolti', 'ascolta', 'ascoltato',
      'origliare', 'origlio', 'origli', 'origlia', 'origliato', 'bisbiglio', 'bisbigli', 'bisbiglia', 'sussurrare', 'sussurro',
      'sussurri', 'sussurra', 'sussurrato', 'gridare', 'grido', 'gridi', 'grida', 'gridato', 'urlare', 'urlo',
      'urli', 'urla', 'urlato', 'borbottare', 'borbotto', 'borbotti', 'borbotta', 'borbottato', 'singhiozzo', 'singhiozzi',
      'singhiozza', 'sospirare', 'sospiro', 'sospiri', 'sospira', 'sospirato', 'sbadiglio', 'sbadigli', 'sbadiglia', 'russare',
      'russo', 'russi', 'russa', 'russato', 'respirare', 'respira', 'respirato', 'masticare', 'mastico', 'mastichi',
      'mastica', 'masticato', 'assaggiare', 'assaggio', 'assaggi', 'assaggia', 'assaggiato', 'gustare', 'gusta', 'gustato',
      'grigliare', 'griglio', 'grigli', 'griglia', 'grigliato', 'salare', 'salo', 'sala', 'zuccherare', 'zuccheri',
      'zucchera', 'zuccherato', 'mescolare', 'mescolo', 'mescoli', 'mescola', 'mescolato', 'impastare', 'impasti', 'impasta',
      'impastato', 'lievitare', 'lieviti', 'lievita', 'lievitato', 'affettare', 'affetti', 'affetta', 'affettato', 'tritare',
      'trito', 'triti', 'trita', 'tritato', 'sbucciare', 'sbuccio', 'sbucci', 'sbuccia', 'sbucciato', 'versare',
      'versa', 'versato', 'sorseggio', 'sorseggi', 'sorseggia', 'brindare', 'brindo', 'brindi', 'brinda', 'brindato',
      'digiunare', 'digiuni', 'digiuna', 'digiunato', 'ingrassare', 'ingrasso', 'ingrassi', 'ingrassa', 'ingrassato', 'pesare',
      'pesa', 'pesato', 'misurare', 'misuro', 'misuri', 'misurato', 'calcolare', 'calcolo', 'calcoli', 'calcola',
      'calcolato', 'sommare', 'sommo', 'sommi', 'sommato', 'moltiplico', 'moltiplica', 'stimare', 'stimo', 'stimi',
      'stimato', 'valutare', 'valuto', 'valuti', 'valuta', 'valutato', 'giudicare', 'giudico', 'giudichi', 'giudica',
      'giudicato', 'paragonare', 'paragono', 'paragoni', 'paragona', 'paragonato', 'dubitare', 'dubito', 'dubiti', 'dubita',
      'dubitato', 'esitare', 'esito', 'esiti', 'esita', 'esitato', 'rischiare', 'rischia', 'rischiato', 'tentare',
      'tento', 'tenti', 'tenta', 'tentato', 'sbagliare', 'sbaglio', 'sbagli', 'sbaglia', 'migliorare', 'miglioro',
      'migliori', 'migliora', 'migliorato', 'peggiorare', 'peggioro', 'peggiori', 'peggiora', 'peggiorato', 'cambiare', 'cambio',
      'cambi', 'cambia', 'cambiato', 'trasformo', 'trasformi', 'trasforma', 'adattare', 'adatto', 'adatti', 'adatta',
      'adattato', 'abituare', 'abituo', 'abitui', 'abitua', 'abituato', 'studiare', 'studia', 'studiato', 'ripassare',
      'ripassi', 'ripassa', 'ripassato', 'insegnato', 'ricordato', 'dimentichi', 'dimentica', 'immaginare', 'immagino', 'immagini',
      'immagina', 'immaginato', 'sognare', 'sogna', 'sognato', 'desiderare', 'desidero', 'desideri', 'desidera', 'desiderato',
      'preoccupo', 'preoccupi', 'preoccupa', 'calmare', 'calmato', 'consolare', 'consolo', 'consoli', 'consola', 'consolato',
      'incoraggio', 'incoraggi', 'incoraggia', 'lodare', 'lodo', 'lodi', 'loda', 'lodato', 'criticare', 'critico',
      'critichi', 'critica', 'criticato', 'rimprovero', 'rimproveri', 'rimprovera', 'perdonare', 'perdoni', 'perdona', 'perdonato',
      'litigare', 'litigo', 'litighi', 'litiga', 'litigato', 'protestare', 'protesto', 'protesti', 'protesta', 'protestato',
      'accusare', 'accuso', 'accusi', 'accusa', 'accusato', 'curare', 'curo', 'curi', 'curato', 'ammalare',
      'ammalo', 'ammali', 'ammala', 'ammalato', 'riposare', 'riposi', 'riposa', 'riposato', 'svegliare', 'svegli',
      'svegliato', 'spogliare', 'spoglio', 'spogli', 'spoglia', 'spogliato', 'spazzare', 'spazzo', 'spazzi', 'spazza',
      'spazzato', 'spolverare', 'spolvero', 'spolveri', 'spolvera', 'spolverato', 'lucidare', 'lucidi', 'lucidato', 'profumare',
      'profumo', 'profumi', 'profuma', 'profumato', 'pettinare', 'pettino', 'pettina', 'pettinato', 'truccare', 'trucca',
      'truccato', 'risparmio', 'risparmi', 'risparmia', 'guadagnare', 'guadagna', 'guadagnato', 'prestare', 'presti', 'presta',
      'prestato', 'regalare', 'regala', 'regalato', 'donare', 'dona', 'donato', 'scambiare', 'scambio', 'scambi',
      'scambia', 'scambiato', 'barattare', 'baratto', 'baratti', 'baratta', 'barattato', 'noleggiare', 'noleggio', 'noleggi',
      'noleggia', 'noleggiato', 'affittare', 'affitto', 'affitti', 'affitta', 'affittato', 'ordinare', 'ordino', 'ordina',
      'ordinato', 'consegnare', 'consegno', 'consegni', 'consegna', 'consegnato', 'timbrare', 'timbra', 'timbrato', 'richiamare',
      'richiamo', 'richiami', 'richiama', 'richiamato', 'organizzo', 'organizzi', 'organizza', 'preparare', 'preparo', 'prepari',
      'prepara', 'preparato', 'programmo', 'programmi', 'programma', 'pianifico', 'pianifichi', 'pianifica', 'iniziare', 'inizia',
      'iniziato', 'cominciare', 'comincio', 'cominci', 'comincia', 'cominciato', 'continuare', 'continuo', 'continui', 'continua',
      'continuato', 'terminare', 'termino', 'termina', 'terminato', 'rimandare', 'rimando', 'rimandi', 'rimanda', 'rimandato',
      'anticipare', 'anticipo', 'anticipi', 'anticipa', 'anticipato', 'ritardare', 'ritarda', 'ritardato', 'aspettato', 'durare',
      'durato', 'bastare', 'basto', 'basti', 'basta', 'bastato', 'mancare', 'manco', 'manchi', 'manca',
      'mancato', 'avanzare', 'avanzo', 'avanzi', 'avanza', 'avanzato', 'aumentare', 'aumento', 'aumenti', 'aumenta',
      'aumentato', 'calare', 'calo', 'cali', 'cala', 'calato', 'abitare', 'abito', 'abiti', 'abita',
      'abitato', 'viaggiato', 'visitare', 'visito', 'visiti', 'visitato', 'esploro', 'esplori', 'esplora', 'esplorato',
      'ritrovare', 'ritrovo', 'ritrovi', 'ritrova', 'ritrovato', 'rubare', 'rubo', 'rubi', 'ruba', 'rubato',
      'fischiare', 'fischio', 'fischi', 'fischia', 'fischiato', 'recitare', 'recito', 'reciti', 'recita', 'recitato',
      'fotografo', 'fotografi', 'fotografa', 'filmare', 'filmo', 'filmi', 'filma', 'filmato', 'registrare', 'registro',
      'registri', 'registra', 'registrato', 'scherzare', 'scherza', 'scherzato', 'annoiare', 'annoio', 'annoi', 'annoia',
      'annoiato', 'stancare', 'stancato', 'allenare', 'alleno', 'alleni', 'allena', 'allenato', 'gareggiare', 'gareggio',
      'gareggi', 'gareggia', 'gareggiato', 'segnare', 'segna', 'segnato', 'tifare', 'tifi', 'tifa', 'tifato',
      'arbitrare', 'arbitra', 'arbitrato', 'tuffare', 'tuffo', 'tuffi', 'tuffa', 'tuffato', 'galleggio', 'galleggi',
      'galleggia', 'affondare', 'affondo', 'affondi', 'affonda', 'affondato', 'pattinare', 'pattino', 'pattini', 'pattina',
      'pattinato', 'sciare', 'scio', 'scii', 'scia', 'sciato', 'scalare', 'scali', 'scalato', 'piovere',
      'piove', 'piovuto', 'accendere', 'accendo', 'accende', 'acceso', 'accesa', 'spegnere', 'spengo', 'spegne',
      'spento', 'spenta', 'sciogliere', 'sciolgo', 'scioglie', 'sciolto', 'sciolta', 'dipingere', 'dipingo', 'dipinge',
      'dipinto', 'dipinta', 'tessere', 'tesso', 'tesse', 'tingere', 'tingo', 'tinge', 'tinto', 'mungere',
      'mungo', 'munge', 'munto', 'raggiungo', 'raggiunge', 'raggiunto', 'accorgersi', 'accorgo', 'accorge', 'accorto',
      'scorgere', 'scorgo', 'scorge', 'scorto', 'friggere', 'friggo', 'frigge', 'fritta', 'bollire', 'bollo',
      'bolle', 'bollito', 'bollita', 'sottrarre', 'sottraggo', 'sottrae', 'sottratto', 'dividere', 'divido', 'divide',
      'diviso', 'divisa', 'scegliere', 'scelgo', 'sceglie', 'scelto', 'decidere', 'decido', 'decide', 'deciso',
      'decisa', 'riuscire', 'riesco', 'riesce', 'riuscito', 'riflettere', 'rifletto', 'riflette', 'riflesso', 'soffrire',
      'soffro', 'soffre', 'sofferto', 'guarire', 'guarisco', 'guarisce', 'guarita', 'dimagrire', 'dimagrisco', 'dimagrito',
      'stendere', 'stendo', 'stende', 'steso', 'stesa', 'spendere', 'spendo', 'spende', 'speso', 'offrire',
      'offro', 'offre', 'offerto', 'offerta', 'ricevere', 'ricevo', 'riceve', 'ricevuto', 'concludere', 'concludo',
      'conclude', 'concluso', 'interrotto', 'diminuire', 'diminuisco', 'diminuito', 'trasferire', 'trasferito', 'restituire', 'restituito',
      'applaudire', 'applaudo', 'applaude', 'applaudito', 'divertire', 'diverto', 'diverte', 'divertito', 'divertita', 'zittire',
      'zittisco', 'zittito', 'tacere', 'taccio', 'tace', 'taciuto', 'tossire', 'tossisco', 'tossisce', 'tossito',
      'starnutire', 'ingoiare', 'sorridere', 'sorrido', 'sorride', 'condire', 'condisco', 'condisce', 'condito', 'condita',
      'spremere', 'spremo', 'spreme', 'spremuto', 'fallire', 'fallisco', 'fallito', 'correggere', 'correggo', 'corregge',
      'corretto', 'corretta', 'punire', 'punisco', 'punisce', 'punito', 'discutere', 'discuto', 'discute', 'discusso',
      'difendere', 'difendo', 'difende', 'difeso', 'difesa', 'proteggere', 'proteggo', 'protegge', 'protetto', 'protetta',
      'soccorrere', 'vestire', 'vesto', 'veste', 'vestito', 'vestita', 'spedire', 'spedisco', 'spedito', 'avvertire',
      'avverto', 'avverte', 'avvertito', 'scoprire', 'scopro', 'scopre', 'scoperto', 'cogliere', 'colgo', 'coglie',
      'colto', 'volgere', 'volgo', 'volge', 'volto', 'giungere', 'giungo', 'giunge', 'giunto', 'ungere',
      'ungo', 'unge', 'unto', 'stringere', 'stringo', 'stringe', 'fingere', 'fingo', 'finge', 'finto',
      'finta', 'convincere', 'convinco', 'convinto', 'concedere', 'concedo', 'concede', 'concesso', 'accadere', 'accade',
      'accaduto', 'succedere', 'succede', 'successo', 'avvenire', 'avviene', 'contenere', 'contiene', 'ottenere', 'ottengo',
      'ottiene', 'ottenuto', 'mantenere', 'mantiene', 'sostenere', 'sostiene', 'trattenere', 'trattiene', 'proporre', 'propongo',
      'propone', 'proposto', 'proposta', 'comporre', 'compongo', 'compone', 'composto', 'esporre', 'espongo', 'espone',
      'esposto', 'imporre', 'impongo', 'impone', 'imposto', 'produrre', 'produco', 'produce', 'prodotto', 'condurre',
      'conduco', 'conduce', 'condotto', 'tradurre', 'traduco', 'traduce', 'tradotto', 'ridurre', 'riduco', 'riduce',
      'ridotto', 'ridotta', 'apparire', 'appare', 'apparso', 'sparire', 'sparisco', 'sparisce', 'sparito', 'sparita',
      'valere', 'vale', 'valso', 'parere', 'pare', 'parso', 'sedere', 'siedo', 'siede', 'seduto',
      'seduta', 'nuocere', 'nuoce', 'porgere', 'porgo', 'porge', 'sorgere', 'sorge', 'sorto', 'rendere',
      'rendo', 'rende', 'reso', 'resa', 'attendere', 'attendo', 'attende', 'atteso', 'pretendere', 'pretendo',
      'pretende', 'sospendere', 'sospeso', 'mordere', 'mordo', 'morde', 'morso', 'morsa', 'ardere', 'arde',
      'arso', 'godere', 'godo', 'gode', 'goduto', 'cedere', 'cedo', 'cede', 'ceduto', 'conoscere',
      'conosco', 'conosce', 'conosciuto', 'piacere', 'piaccio', 'piace', 'piaciuto', 'giacere', 'giace', 'rivedere',
      'rivedo', 'rivede', 'rivisto', 'prevedere', 'prevede', 'provvedere', 'muovere', 'muovo', 'muove', 'mosso',
      'mossa', 'commuovere', 'promuovere', 'scuotere', 'scuote', 'scosso', 'battere', 'batto', 'batte', 'battuto',
      'combattere', 'abbattere', 'abbatto', 'abbatte', 'abbattuto', 'promettere', 'permettere', 'ammettere', 'ammetto', 'ammette',
      'ammesso', 'smettere', 'smetto', 'smette', 'smesso', 'descrivere', 'iscrivere', 'convivere', 'bevuta', 'eleggere',
      'reggere', 'reggo', 'regge', 'retto', 'sconfitto', 'trarre', 'traggo', 'trae', 'tratto', 'attrarre',
      'attrae', 'distrarre', 'distrae', 'sorpreso', 'comprendo', 'comprende', 'compreso', 'apprendere', 'apprendo', 'apprende',
      'appreso', 'dipendere', 'dipende', 'accorgere', 'insorgere', 'partorire', 'partorisce', 'nutrire', 'nutro', 'nutre',
      'nutrito', 'servire', 'servo', 'serve', 'servito', 'servita', 'coprire', 'copro', 'copre', 'convenire',
      'divenire', 'diventare', 'svenire', 'sviene', 'svenuto', 'unire', 'unisco', 'unisce', 'unito', 'unita',
      'riunire', 'finire', 'finisco', 'finisci', 'finisce', 'finito', 'finita', 'ferire', 'ferisco', 'ferisce',
      'gradire', 'gradisco', 'gradito', 'chiarire', 'chiarisco', 'chiarito', 'fiorire', 'fiorisce', 'fiorito', 'sbocciare',
      'appassire', 'appassito', 'marcire', 'marcito', 'arrossire', 'arrossisco', 'ingiallire', 'annerire', 'sbiancare', 'imbiancare',
      'schiarire', 'scurire', 'oscurare', 'illuminare', 'abbagliare', 'brillare', 'luccicare', 'splendere', 'splende', 'tramontare',
      'spuntare', 'sbocciato', 'cucire', 'cucio', 'cuce', 'cucito', 'cucita', 'riempire', 'riempio', 'riempie',
      'riempito', 'premere', 'premo', 'preme', 'premuto', 'inseguire', 'inseguo', 'insegue', 'fuggire', 'fuggo',
      'fugge', 'fuggito', 'sfuggire', 'sfuggo', 'sfugge', 'stupire', 'stupisco', 'stupito', 'obbedire', 'obbedisco',
      'pentire', 'pento', 'pentito', 'svestire', 'consentire', 'mentire', 'mentito', 'ripartire', 'proseguire', 'eseguire',
      'eseguo', 'esegue', 'eseguito', 'aggredire', 'aggredito', 'agire', 'agisco', 'agisce', 'agito', 'reagire',
      'reagisco', 'reagito', 'ubbidire', 'preferire', 'preferisco', 'gioire', 'gioisco', 'gioito', 'tradire', 'tradisco',
      'tradito', 'arredare', 'sancire', 'svanire', 'svanisce', 'svanito', 'impedire', 'impedisco', 'impedito', 'inserire',
      'inserisco', 'inserito', 'perire', 'stabilire', 'stabilito', 'subire', 'subisco', 'suggerire', 'sostituire', 'ripulire',
      'rifinire', 'definire', 'definisco', 'definito', 'digerire', 'digerito', 'nitrire', 'muggire', 'ruggire', 'ruggisce',
      'ruggito', 'ammonire', 'ammonito', 'colorire', 'sfiorire', 'ripetere', 'ripeto', 'ripete', 'ripetuto', 'porre',
      'spargere', 'spargo', 'sparge', 'sparso', 'pungere', 'pungo', 'punge', 'includere', 'escludere', 'escluso',
      'alludere', 'estendere', 'esteso', 'offendere', 'offeso', 'dolere', 'duole', 'solere', 'suole', 'affiggere',
      'trafiggere', 'accogliere', 'deridere', 'uccidere', 'uccido', 'uccide', 'ucciso', 'commettere', 'rimettere', 'emettere',
      'emetto', 'emette', 'emesso', 'connettere', 'assumere', 'assumo', 'assume', 'assunto', 'consumere', 'presumere',
      'esprimere', 'esprimo', 'esprime', 'espresso', 'opprimere', 'reprimere', 'comprimere', 'appendere', 'tendere', 'tendo',
      'teso', 'tesa', 'intendere', 'intendo', 'inteso', 'contrarre', 'sedurre', 'dedurre', 'comparire', 'risalire',
      'mangiamo', 'cresciuto', 'cresciuta', 'chiudiamo', 'prendiamo', 'facciamo', 'compriamo', 'vendiamo', 'studiamo', 'ricordiamo',
      'nasciamo', 'cresciamo', 'perdiamo', 'lavoriamo', 'cuciniamo', 'impariamo', 'insegniamo', 'speriamo', 'sogniamo', 'guardiamo',
      'ascoltiamo', 'seguiamo', 'sarei', 'avrei', 'farei', 'andrei', 'vorrei', 'potrei', 'dovrei', 'direi',
      'starei', 'darei', 'verrei', 'sara', 'saranno', 'avra', 'avranno', 'fara', 'faranno', 'andra',
      'andranno', 'verra', 'verranno', 'dira', 'diranno', 'potra', 'dovra', 'vorra', 'saro', 'avro',
      'andro', 'verro', 'diro', 'potro'],
    qualita: ['bello', 'bella', 'belli', 'belle', 'brutto', 'brutta', 'brutti', 'brutte', 'grande', 'grandi',
      'piccolo', 'piccola', 'piccoli', 'piccole', 'alto', 'alta', 'alti', 'alte', 'basso', 'bassa',
      'bassi', 'basse', 'lungo', 'lunga', 'lunghi', 'lunghe', 'corto', 'corta', 'corti', 'corte',
      'largo', 'larga', 'larghi', 'larghe', 'stretta', 'stretti', 'strette', 'nuovo', 'nuova', 'nuovi',
      'nuove', 'vecchio', 'vecchia', 'vecchi', 'vecchie', 'giovane', 'giovani', 'forte', 'forti', 'debole',
      'deboli', 'caldo', 'calda', 'caldi', 'calde', 'freddo', 'fredda', 'freddi', 'fredde', 'secco',
      'secca', 'secche', 'bagnato', 'bagnata', 'bagnati', 'pieno', 'piena', 'pieni', 'piene', 'vuoto',
      'vuota', 'vuoti', 'vuote', 'pesante', 'pesanti', 'leggero', 'leggera', 'leggeri', 'duro', 'dura',
      'duri', 'dure', 'morbido', 'morbida', 'morbidi', 'liscio', 'liscia', 'lisci', 'ruvido', 'ruvida',
      'chiaro', 'chiara', 'chiari', 'chiare', 'scuro', 'scura', 'scuri', 'scure', 'veloce', 'veloci',
      'lento', 'lenta', 'lenti', 'lente', 'facile', 'facili', 'difficile', 'giusto', 'giusta', 'giusti',
      'giuste', 'sbagliato', 'sbagliata', 'ricco', 'ricca', 'ricchi', 'ricche', 'povero', 'povera', 'poveri',
      'povere', 'felice', 'felici', 'triste', 'tristi', 'calmo', 'calma', 'calmi', 'calme', 'buono',
      'buona', 'buoni', 'buone', 'cattivo', 'cattiva', 'cattivi', 'cattive', 'amaro', 'amara', 'amari',
      'salato', 'salata', 'salati', 'fresco', 'fresca', 'freschi', 'fresche', 'sporco', 'sporca', 'sporchi',
      'sporche', 'puliti', 'raro', 'rara', 'rari', 'rare', 'comune', 'comuni', 'strano', 'strana',
      'strani', 'strane', 'normale', 'normali', 'sicuro', 'sicura', 'sicuri', 'sicure', 'libero', 'libera',
      'liberi', 'libere', 'stanco', 'stanca', 'stanchi', 'stanche', 'sveglio', 'sveglia', 'gentile', 'gentili',
      'cortese', 'scortese', 'onesto', 'onesta', 'onesti', 'oneste', 'furbo', 'furba', 'furbi', 'furbe',
      'stupido', 'stupida', 'stupidi', 'saggio', 'saggia', 'saggi', 'sagge', 'pigro', 'pigra', 'pigri',
      'pigre', 'bravo', 'brava', 'bravi', 'brave', 'capace', 'capaci', 'utile', 'utili', 'inutile',
      'inutili', 'vero', 'vera', 'veri', 'vere', 'falso', 'falsa', 'falsi', 'false', 'certo',
      'certa', 'certi', 'certe', 'profondo', 'profonda', 'sottile', 'sottili', 'spesso', 'spessa', 'grosso',
      'grossa', 'grossi', 'grosse', 'magro', 'magra', 'magri', 'magre', 'grassa', 'grassi', 'grasse',
      'tondo', 'tonda', 'tondi', 'tonde', 'dritto', 'dritta', 'storto', 'storta', 'ripido', 'ripida',
      'piano', 'piana', 'piani', 'piane', 'ripidi', 'acuto', 'acuta', 'lucido', 'lucida', 'opaco',
      'opaca', 'nudo', 'nuda', 'nudi', 'nude', 'coperto', 'lontano', 'lontana', 'lontani', 'lontane',
      'vicino', 'vicina', 'vicini', 'vicine', 'antico', 'antica', 'antichi', 'antiche', 'moderno', 'moderna',
      'moderni', 'moderne', 'unico', 'unica', 'unici', 'doppio', 'doppia', 'doppi', 'doppie', 'intero',
      'intera', 'interi', 'intere', 'mezzo', 'mezza', 'mezzi', 'mezze', 'ultimo', 'ultima', 'ultimi',
      'ultime', 'primo', 'prima', 'primi', 'prime', 'severo', 'severa', 'dolente', 'sereno', 'serena',
      'sereni', 'serene', 'nervoso', 'nervosa', 'nervosi', 'timido', 'timida', 'timidi', 'timide', 'audace',
      'audaci', 'fiero', 'fiera', 'fieri', 'fiere', 'umile', 'umili', 'gelido', 'gelida', 'tiepido',
      'tiepida', 'crudo', 'cruda', 'crudi', 'crude', 'cotto', 'cotta', 'cotti', 'cotte', 'maturo',
      'matura', 'maturi', 'mature', 'acerbo', 'acerba', 'marcio', 'marcia', 'sano', 'sana', 'sani',
      'sane', 'malato', 'malata', 'malati', 'malate', 'ferito', 'ferita', 'feriti', 'guarito', 'vivace',
      'vivaci', 'quieto', 'quieta', 'muto', 'muta', 'sordo', 'sorda', 'cieco', 'cieca', 'zoppo',
      'zoppa', 'brillante', 'brillanti', 'lucente', 'splendido', 'orrendo', 'orrenda', 'enorme', 'enormi', 'minuscolo',
      'gigante', 'giganti', 'immenso', 'immensa', 'infinito'],
    tempo: ['ora', 'ore', 'giorno', 'giorni', 'notte', 'notti', 'mese', 'mesi', 'anno', 'anni',
      'secolo', 'secoli', 'attimo', 'attimi', 'minuto', 'minuti', 'secondo', 'secondi', 'settimana', 'settimane',
      'mattina', 'mattine', 'sera', 'sere', 'pomeriggio', 'alba', 'albe', 'tramonto', 'tramonti', 'stagione',
      'stagioni', 'estate', 'estati', 'inverno', 'inverni', 'autunno', 'autunni', 'primavera', 'ieri', 'oggi',
      'domani', 'presto', 'tardi', 'ritardo', 'ritardi', 'epoca', 'epoche', 'passato', 'futuro', 'presente',
      'lunedi', 'martedi', 'mercoledi', 'giovedi', 'venerdi', 'sabato', 'domenica', 'gennaio', 'febbraio', 'marzo',
      'aprile', 'maggio', 'giugno', 'luglio', 'agosto', 'settembre', 'ottobre', 'novembre', 'dicembre', 'calendario',
      'orario', 'orari', 'durata', 'durate', 'attesa', 'attese', 'inizio', 'inizi', 'termine', 'termini',
      'periodo', 'periodi', 'momento', 'momenti', 'istante', 'istanti', 'sempre', 'mai', 'subito', 'adesso',
      'ancora', 'gia', 'dopo', 'mentre', 'quando', 'notturno', 'diurno', 'annuale', 'mensile', 'giornata',
      'giornate', 'serata', 'serate', 'nottata', 'mattinata', 'vigilia', 'festa', 'feste', 'vacanza', 'vacanze',
      'compleanno', 'ricorrenza', 'proroga', 'rinvio'],
    colori: ['rosso', 'rossa', 'rossi', 'rosse', 'verde', 'verdi', 'blu', 'giallo', 'gialla', 'gialli',
      'gialle', 'nero', 'nera', 'neri', 'nere', 'bianco', 'bianca', 'bianchi', 'bianche', 'grigio',
      'grigia', 'grigi', 'grigie', 'viola', 'arancione', 'arancioni', 'azzurro', 'azzurra', 'azzurri', 'azzurre',
      'marrone', 'marroni', 'oro', 'dorato', 'dorata', 'argento', 'argentea', 'beige', 'turchese', 'porpora',
      'ocra', 'celeste', 'celesti', 'indaco', 'lilla', 'fucsia', 'amaranto', 'granata', 'avorio', 'salmone',
      'corallo', 'smeraldo', 'zaffiro', 'rubino', 'ebano', 'bruno', 'bruna', 'bruni', 'brune', 'biondo',
      'bionda', 'biondi', 'bionde', 'rossiccio', 'grigiastro', 'colorato', 'colorata', 'colorati', 'incolore', 'scolorito',
      'tinta', 'tinte', 'sfumatura', 'tono', 'toni'],
    numeri: ['uno', 'una', 'due', 'tre', 'quattro', 'cinque', 'sette', 'otto', 'nove', 'dieci',
      'undici', 'dodici', 'tredici', 'quindici', 'sedici', 'trenta', 'quaranta', 'cinquanta', 'sessanta', 'settanta',
      'ottanta', 'novanta', 'cento', 'mille', 'milione', 'milioni', 'miliardo', 'zero', 'seconda', 'terzo',
      'terza', 'quarto', 'quarta', 'quinto', 'quinta', 'sesto', 'sesta', 'settimo', 'ottavo', 'nono',
      'decimo', 'meta', 'terzi', 'quarti', 'triplo', 'paio', 'paia', 'coppia', 'coppie', 'dozzina',
      'decina', 'decine', 'centinaio', 'migliaio', 'poco', 'poca', 'pochi', 'poche', 'molto', 'molta',
      'molti', 'molte', 'tanto', 'tanta', 'tanti', 'tante', 'tutto', 'tutta', 'tutti', 'tutte',
      'nessuno', 'nessuna', 'alcuni', 'alcune', 'parecchi', 'numero', 'numeri', 'cifra', 'cifre', 'somma',
      'somme', 'totale', 'quantita', 'gruppo', 'gruppi', 'insieme', 'serie', 'fila', 'file', 'riga',
      'righe'],
    oggetti: ['libro', 'libri', 'penna', 'penne', 'carta', 'carte', 'foglio', 'fogli', 'quaderno', 'quaderni',
      'borsa', 'borse', 'scatola', 'scatole', 'corda', 'corde', 'chiodo', 'chiodi', 'martello', 'martelli',
      'ago', 'aghi', 'bottone', 'bottoni', 'ombrello', 'ombrelli', 'occhiali', 'orologi', 'valigia', 'valigie',
      'zaino', 'zaini', 'cappello', 'cappelli', 'scarpa', 'scarpe', 'guanto', 'guanti', 'sciarpa', 'sciarpe',
      'anello', 'anelli', 'catena', 'catene', 'ruota', 'ruote', 'motore', 'motori', 'barca', 'barche',
      'nave', 'navi', 'treno', 'treni', 'aereo', 'aerei', 'auto', 'bici', 'moto', 'ponte',
      'ponti', 'strada', 'strade', 'sentieri', 'cancello', 'cancelli', 'recinto', 'recinti', 'lanterna', 'lanterne',
      'candela', 'candele', 'matita', 'matite', 'gomma', 'gomme', 'righello', 'forbici', 'colla', 'nastro',
      'nastri', 'spago', 'sacco', 'sacchi', 'sacchetto', 'cesto', 'cesti', 'cassa', 'casse', 'baule',
      'bauli', 'cofano', 'coperchio', 'tappo', 'tappi', 'imbuto', 'chiodino', 'bullone', 'bulloni', 'pinza',
      'pinze', 'cacciavite', 'sega', 'seghe', 'ascia', 'asce', 'accetta', 'pala', 'pale', 'rastrello',
      'zappa', 'zappe', 'falce', 'falci', 'aratro', 'carriola', 'carretto', 'carro', 'carri', 'slitta',
      'slitte', 'remo', 'remi', 'vela', 'vele', 'ancore', 'timone', 'timoni', 'bussola', 'mappa',
      'mappe', 'cartina', 'binocolo', 'macchina', 'macchine', 'radio', 'computer', 'cellulare', 'tablet', 'cavo',
      'cavi', 'batteria', 'batterie', 'pila', 'pile', 'torcia', 'torce', 'coltellino', 'temperino', 'moneta',
      'monete', 'banconota', 'assegno', 'chiavetta', 'biglietto', 'biglietti', 'cartolina', 'giornale', 'giornali', 'rivista',
      'riviste', 'romanzo', 'diario', 'diari', 'album', 'foto', 'poster', 'bandiera', 'bandiere', 'stendardo',
      'giocattolo', 'bambola', 'bambole', 'palla', 'palle', 'pallone', 'palloni', 'dado', 'dadi', 'birilli',
      'scacchi', 'dama', 'puzzle', 'aquilone', 'altalena', 'scivolo', 'trottola', 'fischietto', 'tromba', 'trombe'],
    luoghi: ['citta', 'paese', 'paesi', 'periferia', 'piazza', 'piazze', 'parco', 'parchi', 'scuola', 'scuole',
      'chiesa', 'chiese', 'museo', 'musei', 'teatro', 'teatri', 'mercato', 'mercati', 'negozio', 'negozi',
      'banca', 'banche', 'stazione', 'stazioni', 'aeroporto', 'ospedale', 'ospedali', 'albergo', 'alberghi', 'ristorante',
      'biblioteca', 'palestra', 'palestre', 'castello', 'castelli', 'torre', 'torri', 'giardino', 'giardini', 'cortile',
      'cortili', 'campo', 'campi', 'fattoria', 'fattorie', 'villaggio', 'quartiere', 'quartieri', 'confine', 'confini',
      'frontiera', 'regione', 'regioni', 'provincia', 'borgo', 'borghi', 'via', 'vie', 'viale', 'viali',
      'vicolo', 'vicoli', 'incrocio', 'incroci', 'rotonda', 'aiuola', 'panchina', 'panchine', 'fontana', 'fontane',
      'monumento', 'statua', 'statue', 'piazzale', 'cortina', 'cinema', 'stadio', 'stadi', 'arena', 'arene',
      'circo', 'circhi', 'sagra', 'osteria', 'osterie', 'bar', 'trattoria', 'panetteria', 'farmacia', 'farmacie',
      'edicola', 'edicole', 'macelleria', 'gelateria', 'pizzeria', 'cartoleria', 'officina', 'officine', 'fabbrica', 'fabbriche',
      'magazzino', 'deposito', 'cantiere', 'cantieri', 'miniera', 'miniere', 'faro', 'fari', 'molo', 'moli',
      'darsena', 'banchina', 'rifugio', 'rifugi', 'baita', 'baite', 'capanna', 'capanne', 'baracca', 'chalet',
      'villa', 'ville', 'palazzo', 'palazzi', 'torretta', 'condominio', 'alloggio', 'monolocale', 'sottotetto', 'cantinola',
      'terreno', 'terreni', 'orto', 'orti', 'vigna', 'vigne', 'frutteto', 'uliveto', 'risaia', 'risaie',
      'pascolo', 'pascoli', 'stalla', 'stalle', 'fienile', 'pollaio', 'canile', 'zoo', 'acquario', 'serra',
      'serre', 'vivaio'],
    arte: ['arte', 'arti', 'musica', 'musiche', 'danza', 'danze', 'colore', 'colori', 'pennello', 'pennelli',
      'tela', 'tele', 'poesia', 'poesie', 'romanzi', 'racconto', 'racconti', 'film', 'attore', 'attori',
      'attrice', 'attrici', 'regista', 'registi', 'scena', 'scene', 'ritmo', 'ritmi', 'nota', 'note',
      'chitarra', 'chitarre', 'violino', 'violini', 'flauto', 'flauti', 'tamburo', 'tamburi', 'coro', 'cori',
      'melodia', 'melodie', 'disegno', 'disegni', 'schizzo', 'schizzi', 'mostre', 'galleria', 'gallerie', 'pittura',
      'pitture', 'pittore', 'pittori', 'scultura', 'sculture', 'scultore', 'artista', 'artisti', 'opera', 'opere',
      'capolavoro', 'stile', 'stili', 'bellezza', 'armonia', 'armonie', 'simmetria', 'contrasto', 'sfondo', 'sfondi',
      'figura', 'figure', 'ritratto', 'ritratti', 'paesaggio', 'paesaggi', 'natura', 'telaio', 'telai', 'argilla',
      'creta', 'gesso', 'marmo', 'bronzo', 'affresco', 'mosaico', 'mosaici', 'vetrata', 'vetrate', 'incisione',
      'stampa', 'stampe', 'fotografia', 'scatto', 'scatti', 'ripresa', 'canzone', 'canzoni', 'strofa', 'strofe',
      'ritornello', 'verso', 'versi', 'rima', 'rime', 'metrica', 'sonetto', 'sonetti', 'poeta', 'poeti',
      'scrittore', 'autore', 'autori', 'lettore', 'lettori', 'copertina', 'capitolo', 'capitoli', 'pagina', 'pagine',
      'titolo', 'titoli', 'trama', 'trame', 'finale', 'commedia', 'tragedia', 'dramma', 'drammi', 'sipario',
      'palco', 'palchi', 'platea', 'copione', 'battuta', 'orchestra', 'concerto', 'concerti', 'sinfonia', 'sonata',
      'sonate', 'balletto', 'balletti', 'ballerina', 'ballerino', 'maschera', 'maschere', 'costume', 'costumi', 'trucco',
      'trucchi', 'luce', 'luci'],
    materiali: ['legno', 'legni', 'ferro', 'ferri', 'acciaio', 'rame', 'vetro', 'vetri', 'plastica', 'plastiche',
      'stoffa', 'stoffe', 'lana', 'lane', 'seta', 'cotone', 'cuoio', 'marmi', 'granito', 'cemento',
      'cera', 'cere', 'quarzo', 'diamante', 'diamanti', 'piombo', 'zinco', 'cristallo', 'cristalli', 'ceramica',
      'sughero', 'lino', 'canapa', 'iuta', 'velluto', 'raso', 'pizzo', 'pizzi', 'feltro', 'pelliccia',
      'tulle', 'metallo', 'metalli', 'lega', 'leghe', 'nichel', 'platino', 'ottone', 'ghisa', 'lamiera',
      'mattone', 'mattoni', 'tegola', 'tegole', 'calce', 'malta', 'ghiaia', 'asfalto', 'catrame', 'resina',
      'resine', 'vernice', 'vernici', 'smalto', 'smalti', 'fibra', 'fibre', 'filato', 'tessuto', 'tessuti',
      'ordito', 'panno', 'panni'],
    generale: ['cosa', 'cose', 'modo', 'modi', 'punto', 'punti', 'segno', 'segni', 'nome', 'nomi',
      'parola', 'parole', 'frase', 'frasi', 'storia', 'storie', 'idea', 'idee', 'sogno', 'sogni',
      'dubbio', 'dubbi', 'scelta', 'scelte', 'regola', 'regole', 'ordine', 'ordini', 'caso', 'casi',
      'sorte', 'destino', 'destini', 'fine', 'fini', 'centro', 'centri', 'lato', 'lati', 'fondo',
      'fondi', 'bordo', 'bordi', 'angolo', 'angoli', 'linea', 'linee', 'cerchio', 'quadrato', 'quadrati',
      'triangolo', 'forma', 'forme', 'misura', 'misure', 'pesi', 'altezza', 'altezze', 'distanza', 'distanze',
      'spazio', 'spazi', 'verita', 'bugia', 'bugie', 'errore', 'errori', 'colpa', 'colpe', 'motivo',
      'motivi', 'causa', 'cause', 'effetto', 'effetti', 'esempio', 'esempi', 'prove', 'domanda', 'domande',
      'risposte', 'problema', 'problemi', 'soluzione', 'soluzioni', 'metodo', 'metodi', 'sistema', 'sistemi', 'consiglio',
      'consigli', 'avviso', 'avvisi', 'notizia', 'notizie', 'discorso', 'discorsi', 'dialogo', 'dialoghi', 'silenzio',
      'rumore', 'rumori', 'eco', 'segreto', 'segreti', 'mistero', 'misteri', 'sorpresa', 'sorprese', 'scherzo',
      'scherzi', 'regalo', 'regali', 'dono', 'doni', 'favore', 'favori', 'grazie', 'scusa', 'scuse',
      'saluto', 'saluti', 'invito', 'inviti', 'incontro', 'incontri', 'visita', 'visite', 'ritorno', 'partenza',
      'arrivo', 'arrivi', 'mete', 'orma', 'orme', 'forza', 'forze', 'poteri', 'diritto', 'diritti',
      'doveri', 'pace', 'guerra', 'guerre', 'lotta', 'lotte', 'vittoria', 'vittorie', 'sconfitta', 'patto',
      'patti', 'promessa', 'promesse', 'fiducia', 'coraggio', 'paura', 'paure', 'gioia', 'gioie', 'dolore',
      'dolori', 'amore', 'amori', 'rabbia', 'noia', 'speranza', 'speranze'],
    comuni: ['lui', 'lei', 'noi', 'voi', 'loro', 'mio', 'mia', 'miei', 'mie', 'tuo',
      'tua', 'tuoi', 'tue', 'suo', 'sua', 'suoi', 'sue', 'nostro', 'nostra', 'nostri',
      'nostre', 'vostro', 'vostra', 'vostri', 'vostre', 'questo', 'questa', 'questi', 'queste', 'quello',
      'quella', 'quelli', 'quelle', 'chi', 'che', 'cui', 'come', 'dove', 'quanto', 'quanta',
      'quanti', 'quante', 'quale', 'quali', 'perche', 'appena', 'davvero', 'forse', 'invece', 'infatti',
      'inoltre', 'insomma', 'magari', 'neanche', 'nemmeno', 'oppure', 'ovvero', 'piuttosto', 'purtroppo', 'quasi',
      'sebbene', 'sennonche', 'soltanto', 'solamente', 'sopratutto', 'talvolta', 'tuttavia', 'perfino', 'persino', 'certamente',
      'davanti', 'dietro', 'sopra', 'sotto', 'dentro', 'fuori', 'accanto', 'intorno', 'contro', 'senza',
      'oltre', 'presso', 'tramite', 'assieme', 'sola', 'solo', 'ognuno', 'ognuna', 'qualcuno', 'qualcosa',
      'niente', 'nulla', 'appunto', 'proprio', 'stesso', 'stessa', 'stessi', 'stesse', 'altro', 'altra',
      'altri', 'altre', 'medesimo', 'ciascuno', 'entrambi', 'entrambe', 'ambedue', 'bene', 'male', 'meglio',
      'peggio', 'meno', 'piu', 'assai', 'abbastanza', 'troppo', 'troppa', 'troppi', 'troppe', 'affatto',
      'quindi', 'dunque', 'allora', 'perlomeno', 'almeno', 'circa', 'ecco', 'prego', 'ciao', 'salve',
      'buongiorno', 'buonasera', 'benvenuto', 'benvenuta', 'auguri', 'evviva', 'lentamente', 'facilmente', 'raramente'],
    famiglia: ['padre', 'padri', 'madre', 'madri', 'figlio', 'figli', 'figlia', 'figlie', 'fratello', 'fratelli',
      'sorella', 'sorelle', 'nonno', 'nonni', 'nonna', 'nonne', 'nipote', 'nipoti', 'zio', 'zii',
      'zia', 'zie', 'cugino', 'cugini', 'cugina', 'cugine', 'marito', 'mariti', 'moglie', 'mogli',
      'sposo', 'sposa', 'sposi', 'genitore', 'genitori', 'famiglia', 'famiglie', 'parente', 'parenti', 'bambino',
      'bambini', 'bambina', 'bambine', 'ragazzo', 'ragazzi', 'ragazza', 'ragazze', 'uomo', 'uomini', 'donna',
      'donne', 'persona', 'persone', 'gente', 'signore', 'signori', 'signora', 'signorina', 'amico', 'amici',
      'amica', 'amiche', 'compagno', 'compagni', 'compagna', 'ospite', 'ospiti', 'padrino', 'madrina', 'suocero',
      'suocera', 'genero', 'nuora', 'cognato', 'cognata', 'erede', 'eredi', 'antenato', 'stirpe', 'neonato',
      'infante', 'adulto', 'adulti', 'anziano', 'anziani', 'anziana', 'vedovo', 'vedova', 'orfano', 'gemello',
      'gemelli', 'gemella', 'sposalizio', 'nozze', 'battesimo', 'culla', 'cognome', 'parentela'],
    scuola: ['classe', 'classi', 'lezione', 'lezioni', 'esame', 'esami', 'voto', 'voti', 'esercizio', 'esercizi',
      'lavagna', 'lavagne', 'banco', 'banchi', 'astuccio', 'alunno', 'alunni', 'alunna', 'allievo', 'allievi',
      'studente', 'studenti', 'scolaro', 'scolari', 'insegnante', 'docente', 'docenti', 'preside', 'bidello', 'aula',
      'aule', 'intervallo', 'campanella', 'materia', 'materie', 'geografia', 'scienze', 'italiano', 'inglese', 'francese',
      'spagnolo', 'tedesco', 'latino', 'greco', 'filosofia', 'chimica', 'fisica', 'biologia', 'algebra', 'geometria',
      'aritmetica', 'grammatica', 'sintassi', 'lettura', 'letture', 'scrittura', 'dettato', 'tema', 'riassunto', 'traduzione',
      'verifica', 'ripasso', 'compasso', 'goniometro', 'diploma', 'laurea', 'universita', 'facolta', 'corsi', 'tesi',
      'ricerca', 'ricerche', 'appello'],
    sport: ['sport', 'agonismo', 'giocatore', 'giocatori', 'allenatore', 'arbitro', 'arbitri', 'rete', 'reti', 'gol',
      'punteggio', 'tempi', 'fallo', 'falli', 'rigore', 'rigori', 'calcio', 'tennis', 'lancio', 'lanci',
      'ciclismo', 'sci', 'racchetta', 'canestro', 'guantoni', 'pista', 'piste', 'traguardo', 'gara', 'gare',
      'torneo', 'tornei', 'girone', 'gironi', 'finali', 'medaglia', 'medaglie', 'coppa', 'coppe', 'trofeo',
      'trofei', 'record', 'primato', 'primati', 'allenarsi', 'scarpini', 'tifoso', 'tifosi', 'tifo', 'spalti',
      'tribuna', 'tribune', 'atleta', 'atleti', 'campione', 'campioni', 'campionato', 'classifica', 'pareggio', 'riposo',
      'fatica'],
    salute: ['salute', 'dottore', 'dottori', 'malattia', 'malattie', 'febbre', 'tosse', 'starnuto', 'malessere', 'ferite',
      'taglio', 'tagli', 'graffio', 'graffi', 'livido', 'lividi', 'benda', 'bende', 'cerotto', 'cerotti',
      'farmaco', 'farmaci', 'medicina', 'medicine', 'pillola', 'pillole', 'sciroppo', 'pomata', 'siringa', 'siringhe',
      'vaccino', 'vaccini', 'cura', 'cure', 'terapia', 'terapie', 'clinica', 'cliniche', 'barella', 'ambulanza',
      'pronto', 'soccorso', 'diagnosi', 'analisi', 'sonno', 'quiete', 'stanchezza', 'benessere', 'dieta', 'diete',
      'digiuno', 'appetito', 'nausea', 'vertigine', 'allergia', 'allergie', 'infezione', 'virus', 'batterio', 'guarigione',
      'rimedio', 'ricovero', 'degenza', 'ricaduta', 'igiene', 'sicurezza', 'rischio', 'rischi', 'pericolo'],
    viaggio: ['trasferta', 'tappa', 'tappe', 'percorso', 'percorsi', 'itinerario', 'autostrada', 'casello', 'benzina', 'volante',
      'freno', 'freni', 'bagaglio', 'bagagli', 'borsone', 'passaporto', 'dogana', 'estero', 'straniero', 'turista',
      'turisti', 'guide', 'ostello', 'pensione', 'caparra', 'reception', 'binario', 'binari', 'vagone', 'vagoni',
      'carrozza', 'cuccetta', 'decollo', 'scalo', 'traghetto', 'crociera', 'cabina', 'sosta', 'soste', 'transito',
      'partenze', 'souvenir', 'avventura', 'scoperta', 'esplorare', 'cammino', 'escursione'],
    sentimenti: ['delusione', 'stupore', 'vergogna', 'orgoglio', 'invidia', 'gelosia', 'pieta', 'affetto', 'tenerezza', 'passione',
      'desiderio', 'nostalgia', 'malinconia', 'tristezza', 'allegria', 'felicita', 'entusiasmo', 'timore', 'angoscia', 'ansia',
      'panico', 'terrore', 'sollievo', 'sfiducia', 'rispetto', 'stima', 'disprezzo', 'clemenza', 'rancore', 'rimorso',
      'pentimento', 'curiosita', 'meraviglia', 'incanto', 'disgusto', 'amicizia', 'solitudine', 'compagnia', 'tenerume', 'simpatia',
      'antipatia', 'emozione', 'emozioni', 'sensazione', 'umore'],
  },

  /* Le voci con la scheda: sono queste che il gioco racconta quando
     qualcuno le trova. Rarita' 3 e 4 sono quelle che compaiono. */
  parole: [
    { word: 'mellifluo', category: 'qualita', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Che ha una dolcezza eccessiva e artificiosa, soprattutto nel modo di parlare.',
      translations: { en: 'mellifluous', fr: 'mielleux', es: 'meloso', de: 'honigsüß' },
      tags: ['letterario'] },
    { word: 'quarzo', category: 'materiali', grammaticalType: 'noun', difficulty: 2, rarity: 3,
      definition: 'Minerale durissimo e trasparente, fra i più diffusi della crosta terrestre.',
      translations: { en: 'quartz', fr: 'quartz', es: 'cuarzo', de: 'Quarz' } },
    { word: 'zefiro', category: 'natura', grammaticalType: 'noun', difficulty: 3, rarity: 4,
      definition: 'Vento leggero e tiepido che spira da ponente.',
      translations: { en: 'zephyr', fr: 'zéphyr', es: 'céfiro', de: 'Zephir' },
      tags: ['poetico'] },
    { word: 'crepuscolo', category: 'tempo', grammaticalType: 'noun', difficulty: 3, rarity: 4,
      definition: 'La luce incerta fra il tramonto e la notte, o fra la notte e l’alba.',
      translations: { en: 'twilight', fr: 'crépuscule', es: 'crepúsculo', de: 'Dämmerung' } },
    { word: 'ubiquo', category: 'qualita', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Che è o sembra essere in ogni luogo nello stesso momento.',
      translations: { en: 'ubiquitous', fr: 'ubiquiste', es: 'ubicuo', de: 'allgegenwärtig' } },
    { word: 'lapidario', category: 'qualita', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Detto di uno stile brevissimo e definitivo, come inciso nella pietra.',
      translations: { en: 'terse', fr: 'lapidaire', es: 'lapidario', de: 'lapidar' } },
    { word: 'alacre', category: 'qualita', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Che lavora con energia pronta e allegra.',
      translations: { en: 'brisk', fr: 'alerte', es: 'diligente', de: 'flink' } },
    { word: 'meandro', category: 'natura', grammaticalType: 'noun', difficulty: 2, rarity: 3,
      definition: 'Ansa larga di un fiume; per estensione, un percorso tortuoso.',
      translations: { en: 'meander', fr: 'méandre', es: 'meandro', de: 'Mäander' } },
    { word: 'zenit', category: 'natura', grammaticalType: 'noun', difficulty: 3, rarity: 4,
      definition: 'Il punto del cielo esattamente sopra la testa di chi guarda.',
      translations: { en: 'zenith', fr: 'zénith', es: 'cenit', de: 'Zenit' } },
    { word: 'effimero', category: 'qualita', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Che dura pochissimo, destinato a finire presto.',
      translations: { en: 'ephemeral', fr: 'éphémère', es: 'efímero', de: 'flüchtig' } },
    { word: 'sagace', category: 'qualita', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Che capisce in fretta e vede lontano; acuto di mente.',
      translations: { en: 'shrewd', fr: 'sagace', es: 'sagaz', de: 'scharfsinnig' } },
    { word: 'ozio', category: 'tempo', grammaticalType: 'noun', difficulty: 2, rarity: 3,
      definition: 'Il tempo libero da ogni occupazione, inteso come riposo o come inerzia.',
      translations: { en: 'idleness', fr: 'oisiveté', es: 'ocio', de: 'Müßiggang' } },
    { word: 'gazza', category: 'animali', grammaticalType: 'noun', difficulty: 2, rarity: 3,
      definition: 'Uccello bianco e nero, noto per l’abitudine di raccogliere oggetti lucenti.',
      translations: { en: 'magpie', fr: 'pie', es: 'urraca', de: 'Elster' } },
    { word: 'zolfo', category: 'materiali', grammaticalType: 'noun', difficulty: 2, rarity: 3,
      definition: 'Elemento giallo dall’odore pungente, comune nelle zone vulcaniche.',
      translations: { en: 'sulphur', fr: 'soufre', es: 'azufre', de: 'Schwefel' } },
    { word: 'querela', category: 'lavoro', grammaticalType: 'noun', difficulty: 3, rarity: 4,
      definition: 'Atto con cui una persona chiede che si proceda contro chi l’ha offesa.',
      translations: { en: 'complaint', fr: 'plainte', es: 'querella', de: 'Klage' } },
    { word: 'arguto', category: 'qualita', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Che dice cose intelligenti e spiritose insieme.',
      translations: { en: 'witty', fr: 'spirituel', es: 'agudo', de: 'geistreich' } },
    { word: 'vetusto', category: 'qualita', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Antico al punto da mostrare i segni del tempo.',
      translations: { en: 'ancient', fr: 'vétuste', es: 'vetusto', de: 'altehrwürdig' } },
    { word: 'quiete', category: 'generale', grammaticalType: 'noun', difficulty: 2, rarity: 3,
      definition: 'Lo stato di chi o di ciò che è fermo e silenzioso.',
      translations: { en: 'quiet', fr: 'quiétude', es: 'quietud', de: 'Stille' } },
    { word: 'esiguo', category: 'qualita', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Talmente scarso da bastare appena.',
      translations: { en: 'meagre', fr: 'exigu', es: 'exiguo', de: 'gering' } },
    { word: 'nitido', category: 'qualita', grammaticalType: 'adjective', difficulty: 2, rarity: 3,
      definition: 'Che si vede con contorni netti, senza sfocature.',
      translations: { en: 'sharp', fr: 'net', es: 'nítido', de: 'klar' } },
    { word: 'ligio', category: 'qualita', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Fedele fino allo scrupolo a una regola o a un dovere.',
      translations: { en: 'dutiful', fr: 'scrupuleux', es: 'fiel', de: 'pflichtbewusst' } },
    { word: 'zavorra', category: 'oggetti', grammaticalType: 'noun', difficulty: 3, rarity: 4,
      definition: 'Peso che si carica su una nave per tenerla stabile; ciò che appesantisce inutilmente.',
      translations: { en: 'ballast', fr: 'lest', es: 'lastre', de: 'Ballast' } },
    { word: 'aulico', category: 'arte', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Di linguaggio alto e solenne, da corte.',
      translations: { en: 'lofty', fr: 'noble', es: 'áulico', de: 'erhaben' } },
    { word: 'coacervo', category: 'generale', grammaticalType: 'noun', difficulty: 4, rarity: 4,
      definition: 'Ammasso disordinato di cose diverse messe insieme.',
      translations: { en: 'jumble', fr: 'amas', es: 'cúmulo', de: 'Anhäufung' } },
    { word: 'tenace', category: 'qualita', grammaticalType: 'adjective', difficulty: 2, rarity: 3,
      definition: 'Che non molla la presa, né sulle cose né sui propositi.',
      translations: { en: 'tenacious', fr: 'tenace', es: 'tenaz', de: 'hartnäckig' } },
    { word: 'diafano', category: 'qualita', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Così sottile da lasciar passare la luce.',
      translations: { en: 'diaphanous', fr: 'diaphane', es: 'diáfano', de: 'durchscheinend' } },
    { word: 'gioviale', category: 'qualita', grammaticalType: 'adjective', difficulty: 2, rarity: 3,
      definition: 'Di carattere allegro e cordiale.',
      translations: { en: 'jovial', fr: 'jovial', es: 'jovial', de: 'jovial' } },
    { word: 'ostico', category: 'qualita', grammaticalType: 'adjective', difficulty: 2, rarity: 3,
      definition: 'Difficile da capire o da mandare giù.',
      translations: { en: 'tough', fr: 'ardu', es: 'arduo', de: 'schwierig' } },
    { word: 'peculiare', category: 'qualita', grammaticalType: 'adjective', difficulty: 3, rarity: 4,
      definition: 'Che appartiene in modo particolare a qualcuno o a qualcosa.',
      translations: { en: 'peculiar', fr: 'particulier', es: 'peculiar', de: 'eigentümlich' } },
    { word: 'zuffa', category: 'azioni', grammaticalType: 'noun', difficulty: 2, rarity: 3,
      definition: 'Rissa confusa fra più persone.',
      translations: { en: 'brawl', fr: 'bagarre', es: 'riña', de: 'Rauferei' } },
  ],
};
