/* Lotto 07 — gli assistant manager. Dieci archetipi, e la stessa regola per tutti:
   quello che promettono puo' non avverarsi, e il giocatore non puo' saperlo prima. */
import { r } from './schema.js';

export default [
  r('g001', 'PROPOSTA_TAGLIO_COSTI', 'realistica', 1, 'Le forniture di secondo livello',
    'Ho trovato un fornitore che costa un quinto in meno a parità di qualità dichiarata. Dico dichiarata perché non l’ho ancora provato, ma i conti sono conti.',
    'Proviamo. E poi controlliamo la qualità.', 'Restiamo con quello che conosciamo.', 'Il fornitore aspetta una risposta.'),
  r('g002', 'PROPOSTA_TAGLIO_COSTI', 'realistica', 2, 'Il riscaldamento del magazzino',
    'Spegnerlo di notte fa risparmiare parecchio. Gli ingredienti reggono, secondo me. È una cosa che si può provare per un mese e si vede.',
    'Un mese di prova. Poi guardiamo gli ingredienti.', 'Gli ingredienti non li rischio.', 'Il magazzino resta caldo, per ora.'),
  r('g003', 'PROPOSTA_TAGLIO_COSTI', 'sarcastica', 2, 'Le piccole spese',
    'Ho fatto l’elenco di tutto quello che si compra e non è indispensabile. È un elenco lungo e nessuna voce è grande, ma insieme fanno una cifra che si sente.',
    'Tagliamo l’elenco lungo.', 'Le piccole spese tengono su la gente.', 'L’elenco aspetta il taglio.'),
  r('g004', 'PROPOSTA_TAGLIO_COSTI', 'realistica', 3, 'Il turno di notte',
    'Chiudere di notte fa risparmiare stipendi maggiorati e riscaldamento. Perdiamo capacità, ma con la domanda di adesso non serve tutta.',
    'Chiudiamo la notte. Speriamo che la domanda non torni.', 'La notte resta aperta.', 'La notte continua, per ora.'),

  r('g005', 'PROPOSTA_TAGLIO_WELFARE', 'sarcastica', 2, 'La mensa',
    'Il pasto costa più di quanto renda in gratitudine. Ho fatto i conti: si può dare un contributo invece del pasto, ed è metà della spesa.',
    'Metà spesa. Sperando che se ne accorgano poco.', 'La mensa resta. È l’unica cosa che li tiene.', 'La mensa continua a cuocere.'),
  r('g006', 'PROPOSTA_TAGLIO_WELFARE', 'realistica', 3, 'I giorni in più',
    'Diamo tre giorni di riposo oltre quelli dovuti. Nessun’altra officina lo fa. Togliendoli recuperiamo giornate di lavoro senza spendere una moneta.',
    'Li togliamo. Non spendiamo niente e recuperiamo giorni.', 'I tre giorni restano.', 'I tre giorni sono ancora lì.'),
  r('g007', 'PROPOSTA_TAGLIO_WELFARE', 'sarcastica', 3, 'Le piccole cortesie',
    'Il tè del pomeriggio, la legna in più d’inverno, il carro che li riporta a casa quando piove. Sono abitudini, non diritti. Le abitudini si possono cambiare.',
    'Le abitudini cambiano. Vediamo come la prendono.', 'Le abitudini restano. Sono poco e valgono molto.', 'Le abitudini continuano, per ora.'),

  r('g008', 'PROPOSTA_LICENZIAMENTO', 'realistica', 2, 'Due posti di troppo',
    'Con la produzione di adesso siamo in due più del necessario. Non dico chi: dico che il numero è due, e che il numero non l’ho inventato io.',
    'Due. Speriamo che il numero fosse giusto.', 'Nessuno esce. Troveremo altro.', 'Il numero resta lì, in attesa.'),
  r('g009', 'PROPOSTA_LICENZIAMENTO', 'sarcastica', 3, 'Il rendimento più basso',
    'C’è una persona che rende metà degli altri da otto mesi. Ne abbiamo parlato, non è cambiato niente. A un certo punto è una decisione, non un problema.',
    'A un certo punto è una decisione. Va bene.', 'Ne parliamo ancora, invece di mandarlo via.', 'Ne riparliamo. Ancora.'),
  r('g010', 'PROPOSTA_LICENZIAMENTO', 'realistica', 3, 'Tagliare per salvare',
    'Con la cassa così, o esce qualcuno adesso o escono tutti fra due mesi. Non è una minaccia, è aritmetica. Mi rendo conto che è brutta da sentire.',
    'Aritmetica. Facciamolo, e che sia l’ultima volta.', 'Nessuno esce. Troviamo un’altra strada.', 'L’aritmetica non aspetta, però.'),

  r('g011', 'PROPOSTA_INVESTIMENTO', 'realistica', 1, 'Il nuovo distillatore',
    'Costa quanto due mesi di stipendi e fa il lavoro di tre persone. Si ripaga in un anno, se la produzione resta questa. Se cala, ci resta un distillatore fermo.',
    'Si ripaga in un anno. Compriamolo.', 'Non adesso. Non con questa cassa.', 'Il distillatore resta dal venditore.'),
  r('g012', 'PROPOSTA_INVESTIMENTO', 'realistica', 2, 'La cella per gli ingredienti',
    'Buttiamo un terzo del fresco. Una cella fredda costa parecchio ma quello che buttiamo lo buttiamo tutte le settimane, e continuerà.',
    'Smettiamo di buttare. Compriamo.', 'Continuiamo a buttare, per ora.', 'Buttiamo ancora un po’.'),
  r('g013', 'PROPOSTA_INVESTIMENTO', 'sarcastica', 3, 'La ricerca sulle pozioni nuove',
    'Nessuno qui prova niente di nuovo da anni. Propongo un budget per sperimentare. Non garantisco risultati: se garantissi risultati non sarebbe ricerca.',
    'Non garantisci niente. È il punto della ricerca, va bene.', 'Con questa cassa non si sperimenta.', 'La ricerca aspetta il budget.'),
  r('g014', 'PROPOSTA_INVESTIMENTO', 'realistica', 2, 'Il secondo laboratorio',
    'Affittare la stanza accanto ci raddoppierebbe lo spazio. Costa ogni mese, non una volta sola, e questo è il rischio. Ma stiamo lavorando stretti.',
    'Prendiamo la stanza. Stiamo troppo stretti.', 'Restiamo stretti e senza affitto.', 'La stanza resta libera, per ora.'),

  r('g015', 'PROPOSTA_OUTSOURCING', 'realistica', 2, 'L’imbottigliamento fuori',
    'C’è un’officina che imbottiglia a meno di quanto ci costa farlo. Perderemmo il controllo sull’ultima fase, che è quella che il cliente vede.',
    'Costa meno. Proviamo, e teniamo gli occhi aperti.', 'L’ultima fase resta nostra.', 'Ci penso. L’offerta scade.'),
  r('g016', 'PROPOSTA_OUTSOURCING', 'sarcastica', 3, 'Le etichette a cottimo',
    'Un tale del porto le fa a un terzo del nostro costo. Non ho controllato come, e forse è meglio non chiederlo, ma il prezzo è quello.',
    'Meglio non chiederlo. Va bene.', 'Preferisco sapere come si fanno le nostre cose.', 'Il tale del porto aspetta.'),
  r('g017', 'PROPOSTA_OUTSOURCING', 'realistica', 3, 'Le consegne a un corriere',
    'Dare le consegne alla Gilda dei corrieri ci toglie un carro, un cavallo e una persona. Ci toglie anche il rapporto diretto con chi riceve.',
    'Togliamoci carro e cavallo. Il rapporto lo terremo per lettera.', 'Le consegne le facciamo noi.', 'La Gilda resta in attesa.'),

  r('g018', 'PROPOSTA_RIORGANIZZAZIONE', 'realistica', 2, 'Rifare i reparti',
    'I reparti sono nati come capitava e adesso il lavoro attraversa la stanza tre volte. Rifarli costa due settimane di confusione e poi va meglio. Secondo me.',
    'Due settimane di confusione. Le mettiamo in conto.', 'Restiamo come siamo. Funziona.', 'La confusione può aspettare.'),
  r('g019', 'PROPOSTA_RIORGANIZZAZIONE', 'sarcastica', 3, 'La catena di comando',
    'Nessuno sa a chi rispondere e ognuno risponde a chi gli conviene. Propongo di scriverlo una volta per tutte. Qualcuno si offenderà: è il prezzo di scriverlo.',
    'Scriviamolo. Qualcuno si offenderà.', 'Meglio non scriverlo. Si offenderebbero tutti.', 'Lo scriveremo. Prima o poi.'),
  r('g020', 'PROPOSTA_RIORGANIZZAZIONE', 'realistica', 3, 'I turni ridisegnati',
    'Con i turni di adesso ci sono ore in cui siamo in troppi e ore in cui siamo in tre. Ridisegnarli fa risparmiare senza mandare via nessuno, ma sposta le abitudini di tutti.',
    'Nessuno esce e si risparmia. Facciamolo.', 'Le abitudini di tutti valgono qualcosa.', 'I turni restano come sono, per ora.'),

  r('g021', 'PROPOSTA_CONSULENZA', 'sarcastica', 1, 'Un occhio da fuori',
    'C’è un tale che gira le officine e dice cosa non va. Costa un mese di stipendio per tre giorni. Dice cose che sappiamo già, ma le dice a tutti insieme.',
    'Le dice a tutti insieme. È il valore.', 'Le sappiamo già. Risparmiamo.', 'Il tale gira altre officine intanto.'),
  r('g022', 'PROPOSTA_CONSULENZA', 'demenziale', 3, 'L’esperto di clima aziendale',
    'Misura il morale con un questionario e ci dà un numero. Non so cosa faremo del numero, ma avere un numero è meglio che non averlo. Credo.',
    'Un numero. Vediamo che ci diciamo.', 'Il morale lo vedo camminando per l’officina.', 'Il numero aspetta di essere misurato.'),
  r('g023', 'PROPOSTA_CONSULENZA', 'realistica', 2, 'Il perito per la contabilità',
    'I nostri conti sono tenuti come si teneva vent’anni fa. Un perito li rimette in ordine e ci dice dove perdiamo soldi. Costa, e potrebbe dire che perdiamo soldi con lui.',
    'Che ce lo dica. Meglio saperlo.', 'I conti li teniamo come sappiamo.', 'Il perito aspetta.'),

  r('g024', 'PROPOSTA_MARKETING', 'realistica', 1, 'I banditori al mercato',
    'Tre giorni di banditore nelle tre piazze grandi. Costa poco e si vede subito se funziona, perché la gente arriva o non arriva.',
    'Si vede subito. Proviamo.', 'Niente banditori. Ci conoscono già.', 'I banditori aspettano.'),
  r('g025', 'PROPOSTA_MARKETING', 'sarcastica', 2, 'La ballata su di noi',
    'Ho parlato con un bardo. Per una cifra ragionevole scrive una canzone sulle nostre pozioni e la canta in giro. Le sue canzoni piacciono, anche quando sono false.',
    'Anche quando sono false. Va bene.', 'Non compriamo canzoni.', 'Il bardo aspetta il compenso.'),
  r('g026', 'PROPOSTA_MARKETING', 'realistica', 2, 'L’insegna nuova',
    'La nostra si legge male e sta in una via di passaggio. Rifarla grande costa quanto due commesse piccole e la vedrebbero tutti quelli che passano.',
    'La vedono tutti quelli che passano. Facciamola.', 'L’insegna vecchia si legge abbastanza.', 'L’insegna resta com’è.'),
  r('g027', 'PROPOSTA_MARKETING', 'realistica', 3, 'La fiera della capitale',
    'Uno stand costa parecchio e ci vogliono due persone per tre giorni. Ma ci vanno tutti quelli che comprano in grande, e noi non ci siamo mai andati.',
    'Non ci siamo mai andati. È ora.', 'Troppo caro per tre giorni.', 'La fiera è a data fissa, però.'),

  r('g028', 'PROPOSTA_AUMENTO_RITMI', 'realistica', 2, 'Un decimo in più',
    'Chiedo di alzare la produzione di un decimo per un mese. Si può fare: lo dicono i numeri. Se la gente regge, poi resta così.',
    'Un decimo per un mese. Vediamo se reggono.', 'Non li spingo. Rendono già.', 'Il decimo aspetta.'),
  r('g029', 'PROPOSTA_AUMENTO_RITMI', 'sarcastica', 3, 'La settimana intensa',
    'Una settimana a ritmo doppio per recuperare l’arretrato. Poi si torna normali. Lo chiamerei sprint, che suona meglio di "una settimana pesante".',
    'Chiamiamolo sprint. Una settimana.', 'L’arretrato si recupera piano.', 'Lo sprint resta in programma.'),
  r('g030', 'PROPOSTA_AUMENTO_RITMI', 'realistica', 3, 'Le pause più corte',
    'Le pause di adesso sono più lunghe di quelle di chiunque altro. Accorciarle di un quarto ci dà mezza giornata a settimana per persona, senza spendere niente.',
    'Mezza giornata a settimana. Accorciamo.', 'Le pause restano come sono.', 'Le pause restano, per ora.'),

  r('g031', 'PROPOSTA_ASSUNZIONE', 'realistica', 1, 'Serve un paio di braccia',
    'Il magazzino è sotto di una persona da quando è uscito il vecchio. Chi c’è fa il doppio e prima o poi si stanca o sbaglia. Uno nuovo costa, ma costa meno di un errore grosso.',
    'Assumiamo. Prima dell’errore grosso.', 'Reggeranno ancora un po’.', 'Reggeranno ancora un po’, immagino.'),
  r('g032', 'PROPOSTA_ASSUNZIONE', 'realistica', 2, 'Un apprendista',
    'Costa poco e in sei mesi diventa utile. Nei primi due però rallenta chi lo insegna, e chi lo insegna è già quello che ha più lavoro.',
    'Sei mesi e diventa utile. Prendiamolo.', 'Non adesso. Chi insegna è già pieno.', 'L’apprendista aspetta fuori.'),
  r('g033', 'PROPOSTA_ASSUNZIONE', 'sarcastica', 3, 'Uno che sappia già tutto',
    'Ho trovato una persona che sa fare tutto quello che ci manca. Chiede una paga alta, ma sostituisce due mezze competenze con una intera.',
    'Una intera al posto di due mezze. Va bene.', 'Costa come due. Perché è due.', 'La persona intera aspetta una risposta.'),
];
