/* Lotto 04 — il tempo: PERMESSO_PERSONALE, FLESSIBILITA_ORARIA, LAVORO_DA_CASA, FERIE_LUNGHE. */
import { r } from './schema.js';

export default [
  r('t001', 'PERMESSO_PERSONALE', 'realistica', 1, 'La visita del figlio',
    'Il guaritore riceve solo di mattina e solo il giovedì. Recupero le ore quando volete, anche il settimo giorno. Ma il giovedì mattina devo esserci io.',
    'Vai. E non recuperare niente.', 'Manderò mia moglie. Lavora anche lei.', 'Il giovedì arriva comunque, però.'),
  r('t002', 'PERMESSO_PERSONALE', 'realistica', 1, 'Due ore per il notaio',
    'Firma di successione, mi tocca esserci di persona. Due ore, una volta sola, e non tornerà.',
    'Due ore. Vai tranquillo.', 'Cercherò di spostarla. Non credo si possa.', 'Provo a spostarla ancora una volta.'),
  r('t003', 'PERMESSO_PERSONALE', 'realistica', 2, 'Il trasloco di mia madre',
    'Ha ottant’anni e nessun altro. Serve un giorno intero, e serve fra due settimane, quindi lo dico adesso e non all’ultimo.',
    'Un giorno. E hai fatto bene a dirlo adesso.', 'Va bene. Le dirò di chiamare qualcun altro.', 'Vedo se si può spostare. Ha ottant’anni.'),
  r('t004', 'PERMESSO_PERSONALE', 'sarcastica', 2, 'Il funerale del vicino',
    'Non eravamo amici. Anzi, litigavamo per il muro. Ma è morto e sua moglie mi ha chiesto di esserci, e a certe richieste non si dice di no.',
    'Vai. Anche i muri finiscono.', 'Manderò dei fiori. Con un biglietto lungo.', 'I fiori partono comunque.'),
  r('t005', 'PERMESSO_PERSONALE', 'realistica', 1, 'Il permesso di ieri',
    'Ieri sono uscito un’ora prima senza chiedere perché era un’emergenza. Vengo a dirlo adesso invece di sperare che non si noti.',
    'Hai fatto bene a dirlo. Passa.', 'Un’ora la segno. La prossima volta chiedi.', 'Ne riparliamo, ma l’ora è già passata.'),
  r('t006', 'PERMESSO_PERSONALE', 'demenziale', 2, 'Il compleanno del cane',
    'Compie sette anni, che in anni di cane sono quarantanove, e quarantanove è un’età che si festeggia. Basta il pomeriggio. Ho già ordinato la torta.',
    'Hai già ordinato la torta. Vai.', 'Il cane festeggerà in tua assenza.', 'Il cane compie gli anni comunque.'),
  r('t007', 'PERMESSO_PERSONALE', 'realistica', 2, 'Il processo',
    'Sono testimone in una causa che non mi riguarda. Se non mi presento è la corte a occuparsi di me, e questo riguarda anche voi.',
    'Se lo chiede la corte non si discute.', 'Non presentarsi è un reato, però.', 'La corte non aspetta, però.'),
  r('t008', 'PERMESSO_PERSONALE', 'realistica', 1, 'Mezza giornata per l’esame',
    'Sto studiando da conciatore di pelli la sera. L’esame è di lunedì mattina. È l’ultimo di tre anni.',
    'L’ultimo di tre anni. Vai, e in bocca al lupo.', 'Allora saranno tre anni buttati.', 'L’esame è lunedì, comunque.'),
  r('t009', 'PERMESSO_PERSONALE', 'realistica', 2, 'La scuola ha chiamato',
    'Mio figlio ha fatto qualcosa e vogliono parlarmi oggi. Non so cosa e questa è la parte che mi preoccupa.',
    'Vai adesso. Il resto si recupera.', 'Andrò domani. Sperando basti.', 'Domani, se aspettano.'),
  r('t010', 'PERMESSO_PERSONALE', 'sarcastica', 3, 'Il torneo di dadi',
    'Sono in semifinale nel torneo del quartiere. È di martedì pomeriggio e non sposto io la semifinale. Recupero tutto, ma martedì non ci sono.',
    'Vinci, almeno.', 'La semifinale si giocherà senza di me.', 'La semifinale è martedì comunque.'),

  r('t011', 'FLESSIBILITA_ORARIA', 'realistica', 1, 'Un’ora dopo la mattina',
    'Accompagno mio figlio a scuola e arrivo trafelato dieci minuti dopo l’apertura. Se entro un’ora dopo e esco un’ora dopo, faccio le stesse ore ma senza correre.',
    'Stesse ore, meno corsa. Bene.', 'Continuerò a correre, allora.', 'Corro ancora un po’.'),
  r('t012', 'FLESSIBILITA_ORARIA', 'realistica', 1, 'Il turno spezzato',
    'Rendo di più la mattina presto e la sera tardi; nel mezzo del pomeriggio non combino niente. Vorrei provare a spezzare la giornata per un mese e poi guardiamo i numeri.',
    'Un mese di prova e i numeri. D’accordo.', 'Restiamo con l’orario di tutti.', 'Ne riparliamo, forse.'),
  r('t013', 'FLESSIBILITA_ORARIA', 'realistica', 2, 'Il quarto giorno lungo',
    'Vorrei fare quattro giorni più lunghi invece di cinque normali. Le ore sono le stesse e il quinto giorno ci guadagno un viaggio di due ore.',
    'Le ore sono le stesse. Proviamo.', 'Restano cinque giorni.', 'Cinque giorni ancora un po’.'),
  r('t014', 'FLESSIBILITA_ORARIA', 'sarcastica', 2, 'Il ritmo naturale',
    'Ho letto che ognuno ha un ritmo naturale e il mio comincia a mezzogiorno. Non è pigrizia: è un fatto documentato. Da me.',
    'Documentato da te. Proviamo lo stesso.', 'Il ritmo naturale si adatta all’officina.', 'Il ritmo aspetta con te.'),
  r('t015', 'FLESSIBILITA_ORARIA', 'realistica', 2, 'La pausa lunga',
    'Vorrei una pausa di due ore a metà giornata e finire più tardi. In quelle due ore vado a prendere mia figlia, e non c’è nessun altro che possa.',
    'Vai a prenderla. Il resto si sistema.', 'Dovrà trovare un altro modo.', 'Cercherò un altro modo, intanto.'),
  r('t016', 'FLESSIBILITA_ORARIA', 'demenziale', 3, 'L’orario lunare',
    'Le mie capacità seguono le fasi della luna: sono al meglio tre giorni dopo il novilunio. Vorrei un orario che segua il calendario lunare invece di quello del sole.',
    'Il calendario lunare. Proviamo, ma i conti li guardo io.', 'Seguiremo il sole, come tutti.', 'La luna intanto continua per conto suo.'),
  r('t017', 'FLESSIBILITA_ORARIA', 'realistica', 1, 'Il mercoledì corto',
    'Il mercoledì c’è il mercato delle erbe e chiude presto. Se esco due ore prima quel giorno compro meglio e spendo meno, e recupero il giovedì.',
    'Compri meglio e spendi meno. Vai.', 'Compreremo al prezzo di sempre.', 'Il mercato chiude presto comunque.'),
  r('t018', 'FLESSIBILITA_ORARIA', 'realistica', 2, 'Non sono una persona da mattina',
    'Nelle prime due ore sbaglio, e sbaglio cose che poi qualcuno deve rifare. Non chiedo meno ore: chiedo di spostarle dove servono a qualcosa.',
    'Meglio spostarle che rifare il lavoro.', 'Continueremo a rifare le prime due ore.', 'Rifacciamo ancora un po’.'),

  r('t019', 'LAVORO_DA_CASA', 'realistica', 1, 'Due ore di strada',
    'Abito lontano e faccio due ore di cammino al giorno. Il mio lavoro è scrivere e contare, e si scrive e si conta anche a casa. Due giorni a settimana cambierebbero tutto.',
    'Due giorni. Proviamo.', 'Continuo a camminare, allora.', 'Cammino ancora un po’.'),
  r('t020', 'LAVORO_DA_CASA', 'realistica', 2, 'La settimana dei registri',
    'Quando faccio i conti di fine mese ho bisogno di silenzio, e qui il silenzio non esiste. Vorrei farli a casa: sono tre giorni, una volta al mese.',
    'Tre giorni al mese, va bene.', 'Li farai qui, col rumore.', 'Col rumore ancora un po’.'),
  r('t021', 'LAVORO_DA_CASA', 'sarcastica', 2, 'La concentrazione',
    'In officina sono interrotto in media undici volte al giorno. Le ho contate. Da casa sarei interrotto solo da me stesso, e con me stesso so essere severo.',
    'Undici interruzioni. Va bene, prova.', 'Continueremo a interromperti.', 'Undici al giorno, ancora un po’.'),
  r('t022', 'LAVORO_DA_CASA', 'realistica', 1, 'Il figlio malato',
    'È a letto da tre giorni e non posso lasciarlo solo. Non chiedo un permesso: chiedo di lavorare da casa, che il mio lavoro lo permette.',
    'Lavora da casa. Guarisca in fretta.', 'Allora dovrà essere un permesso.', 'Restiamo in sospeso, intanto lui è a letto.'),
  r('t023', 'LAVORO_DA_CASA', 'demenziale', 3, 'La casa migliore',
    'Ho attrezzato una stanza uguale all’officina, con lo stesso banco e la stessa luce. È identica, tranne che non c’è nessuno che parla. È obiettivamente superiore.',
    'Obiettivamente superiore. Proviamo.', 'La stanza identica resterà vuota.', 'La stanza aspetta, identica.'),
  r('t024', 'LAVORO_DA_CASA', 'realistica', 2, 'Un giorno alla settimana',
    'Uno solo. Il venerdì, quando qui c’è meno gente e io ho la parte del lavoro che si fa da soli. Se non funziona lo togliamo dopo un mese.',
    'Un giorno, e si guarda dopo un mese.', 'Nessun giorno. Ci vediamo qui.', 'Ne riparliamo il mese prossimo.'),

  r('t025', 'FERIE_LUNGHE', 'realistica', 2, 'Tre settimane in una volta',
    'Non ho preso ferie da due anni e le ho accumulate. Vorrei prenderne tre di fila per andare a casa mia, che è lontana e non si raggiunge in un fine settimana.',
    'Tre settimane. Te le sei guadagnate.', 'Le prenderai spezzate, come tutti.', 'Ne riparliamo. Casa mia resta lontana.'),
  r('t026', 'FERIE_LUNGHE', 'realistica', 3, 'Il mese sabbatico',
    'Sono stanco in un modo che le domeniche non risolvono. Chiedo un mese senza paga. Torno, e torno meglio di come vado via.',
    'Un mese. Torna meglio.', 'Un mese non si può. Riposati la domenica.', 'La stanchezza aspetta con me.'),
  r('t027', 'FERIE_LUNGHE', 'sarcastica', 3, 'Il viaggio di scoperta',
    'Vorrei attraversare il regno da nord a sud per capire come lavorano gli altri. Sono sei settimane e tornerei pieno di idee nuove. Alcune anche buone.',
    'Alcune anche buone. Va bene, vai.', 'Le idee nuove si trovano anche qui.', 'Le idee aspettano al nord.'),
  r('t028', 'FERIE_LUNGHE', 'realistica', 2, 'Il matrimonio lontano',
    'Mia sorella si sposa dall’altra parte del mare. Fra andata, permanenza e ritorno sono quindici giorni. Non capita due volte.',
    'Quindici giorni. Salutala da parte nostra.', 'Manda un regalo.', 'Il matrimonio è quel giorno, comunque.'),
  r('t029', 'FERIE_LUNGHE', 'demenziale', 4, 'Il pellegrinaggio',
    'Ho fatto un voto: se la commessa della capitale andava bene, sarei andato a piedi al santuario del nord. È andata bene. Sono quaranta giorni di cammino.',
    'Un voto è un voto. Va’.', 'Il voto lo hai fatto tu, non l’officina.', 'Il santuario non si sposta.'),
  r('t030', 'FERIE_LUNGHE', 'realistica', 2, 'Le ferie che non ho mai preso',
    'Ho quarantatré giorni non goduti negli ultimi tre anni. Non li chiedo tutti: ne chiedo dieci, e vorrei che gli altri non sparissero.',
    'Dieci adesso, e gli altri restano segnati.', 'Dieci non si possono. Facciamo cinque.', 'Restano tutti e quarantatré in sospeso.'),
];
