/* Lotto 06 — le persone contro le persone, e le assurdita':
   CONFLITTO_TRA_COLLEGHI, LAMENTELA_SU_COLLEGA, RICATTO_IMPLICITO, DIRITTO_DI_VETO,
   RICHIESTA_ASSURDA_BASSO_COSTO, RICHIESTA_ASSURDA_ALTO_COSTO. */
import { r } from './schema.js';

export default [
  r('p001', 'CONFLITTO_TRA_COLLEGHI', 'realistica', 1, 'Non ci parliamo più',
    'Io e quello del banco accanto non ci rivolgiamo la parola da tre settimane. Il lavoro passa da lui a me e viceversa, quindi il lavoro ne risente. Serve che qualcuno ci metta in una stanza.',
    'Vi metto in una stanza. Domattina.', 'Ve la sbrigate fra voi, allora.', 'Ce la sbrigheremo. Male, probabilmente.'),
  r('p002', 'CONFLITTO_TRA_COLLEGHI', 'realistica', 2, 'Il merito di un altro',
    'Il lavoro sulla pozione del sonno l’abbiamo fatto in due e lui l’ha raccontato come suo. Non voglio punizioni. Voglio che si dica come sono andate le cose.',
    'Si dirà come sono andate. Davanti a tutti.', 'Non entro in queste cose.', 'Ci penso. Intanto la storia resta la sua.'),
  r('p003', 'CONFLITTO_TRA_COLLEGHI', 'realistica', 2, 'Chi urla vince',
    'Nel reparto c’è uno che alza la voce e ottiene sempre quello che vuole. Non è il migliore: è il più rumoroso. E adesso alzano la voce anche gli altri.',
    'Chi urla smette di vincere da domani.', 'Alza la voce anche tu, allora.', 'Chi urla continua a vincere, intanto.'),
  r('p004', 'CONFLITTO_TRA_COLLEGHI', 'sarcastica', 2, 'La guerra della finestra',
    'Metà reparto la vuole aperta, l’altra metà chiusa. Si alzano a turno per aprirla e chiuderla. Ho contato ventidue volte in un giorno. Serve una decisione, non un accordo.',
    'La decisione la prendo io: aperta la mattina.', 'Decidete voi. Ventitré volte, domani.', 'Ventidue diventeranno trenta, immagino.'),
  r('p005', 'CONFLITTO_TRA_COLLEGHI', 'realistica', 3, 'Due squadre nella stessa stanza',
    'Il reparto si è spaccato in due gruppi che non si passano più le informazioni. Ognuno rifà quello che ha già fatto l’altro. È diventato un problema di lavoro, non di simpatie.',
    'Lo affronto io, prima che diventi permanente.', 'Che se la vedano fra loro.', 'Ci penso. Le due squadre intanto restano due.'),
  r('p006', 'CONFLITTO_TRA_COLLEGHI', 'realistica', 1, 'Il turno scambiato senza dirlo',
    'Ha scambiato il turno con un altro e nessuno me l’ha detto. Sono arrivato e c’era il vuoto. Non è la prima volta e non è successo per caso.',
    'I turni si cambiano dicendolo. Regola nuova.', 'Mettetevi d’accordo fra voi.', 'Vediamo. Intanto continuo a trovare il vuoto.'),

  r('p007', 'LAMENTELA_SU_COLLEGA', 'realistica', 1, 'Arriva sempre tardi',
    'Venti minuti, ogni giorno. Io comincio in orario e faccio la sua parte per venti minuti. Non voglio che lo punisca: voglio che qualcuno glielo dica.',
    'Glielo dico io. Oggi.', 'Sono venti minuti. Lasciamo stare.', 'Glielo dirò, prima o poi.'),
  r('p008', 'LAMENTELA_SU_COLLEGA', 'realistica', 2, 'Non pulisce mai',
    'Lascia il banco come lo trova chi viene dopo, cioè sporco. Il turno seguente perde mezz’ora a sistemare. È sempre la stessa persona e sempre lo stesso banco.',
    'Chi sporca pulisce. Lo dico chiaro.', 'Pulisce chi trova lo sporco, allora.', 'Vediamo. Intanto pulisce chi trova.'),
  r('p009', 'LAMENTELA_SU_COLLEGA', 'sarcastica', 2, 'Il rumore',
    'Canta. Tutto il giorno. Non canta male, e questo peggiora le cose, perché non posso nemmeno lamentarmi che canta male.',
    'Gli chiedo di cantare piano.', 'Canterà. Tu concentrati.', 'Canterà ancora, per un po’.'),
  r('p010', 'LAMENTELA_SU_COLLEGA', 'realistica', 2, 'Sbaglia e non lo dice',
    'Ha rovinato due lotti e li ha rimessi in mezzo agli altri invece di segnalarli. L’ho scoperto per caso. Se succede ancora se ne accorge un cliente.',
    'Questo è grave. Me ne occupo.', 'Sarà stato un caso.', 'Ci guarderò. Intanto i lotti sono in mezzo.'),
  r('p011', 'LAMENTELA_SU_COLLEGA', 'realistica', 1, 'Parla di me in giro',
    'Racconta cose mie a gente che non c’entra. Cose vere, ma mie. Non voglio uno scontro: voglio che smetta.',
    'Smetterà. Glielo dico io.', 'Sono chiacchiere. Passano.', 'Le chiacchiere passeranno, forse.'),
  r('p012', 'LAMENTELA_SU_COLLEGA', 'demenziale', 3, 'Mangia il mio pranzo',
    'Da due mesi qualcuno mangia il mio pranzo. Ho fatto una trappola con la senape forte e ho scoperto chi è. Adesso però la senape l’ho finita e vorrei giustizia.',
    'Giustizia e senape nuova. Va bene.', 'Nascondi meglio il pranzo.', 'La senape aspetta di essere rimpiazzata.'),

  r('p013', 'RICATTO_IMPLICITO', 'realistica', 2, 'L’offerta dall’altra parte',
    'Mi hanno cercato dall’Alchimia Meridionale. Non ho detto sì e non ho detto no. Sono venuto qui prima, perché mi sembrava corretto.',
    'Hai fatto bene a venire qui prima. Restiamo.', 'Fai quello che ti conviene.', 'Ci penso. Anche loro, immagino.'),
  r('p014', 'RICATTO_IMPLICITO', 'sarcastica', 3, 'Le mie condizioni',
    'Non è una minaccia, è un’informazione: se le cose restano queste, a fine stagione non ci sono. Poi ognuno fa i suoi conti, io i miei li ho già fatti.',
    'Cambiamo le cose, allora.', 'Fai i tuoi conti. Io ho fatto i miei.', 'I conti restano aperti per tutti e due.'),
  r('p015', 'RICATTO_IMPLICITO', 'realistica', 3, 'Il reparto viene con me',
    'Se me ne vado, due persone del mio reparto mi seguono. Non gliel’ho chiesto io: me l’hanno detto loro. Preferivo che lo sapeste da me.',
    'Preferivo saperlo da te. E preferisco che restiate.', 'Che vadano, allora.', 'Vediamo. Loro intanto aspettano una risposta.'),
  r('p016', 'RICATTO_IMPLICITO', 'realistica', 2, 'Il cliente mi conosce',
    'Quello della capitale tratta con me da quattro anni. Non è una minaccia, ma è un fatto: se cambio officina, il primo a saperlo è lui.',
    'È un fatto, e ne teniamo conto.', 'I clienti sono dell’officina, non tuoi.', 'Il fatto resta un fatto, intanto.'),
  r('p017', 'RICATTO_IMPLICITO', 'demenziale', 4, 'La lettera già scritta',
    'Ho qui la lettera di dimissioni. È scritta bene, l’ho fatta rileggere. Non la consegno: la tengo in tasca, e ogni tanto la tocco per ricordarmi che potrei.',
    'Toglila dalla tasca. Parliamone davvero.', 'Tienila in tasca. Sai dov’è la porta.', 'La lettera resta in tasca, allora.'),

  r('p018', 'DIRITTO_DI_VETO', 'sarcastica', 4, 'Voglio dire la mia sulle assunzioni',
    'Sono io che lavoro con chi arriva, quindi sono io che dovrei dire se va bene. Non chiedo di scegliere: chiedo di poter dire di no.',
    'Potrai dire di no. Speriamo raramente.', 'Le assunzioni le decide chi paga.', 'Ci penso. Intanto scelgo io.'),
  r('p019', 'DIRITTO_DI_VETO', 'sarcastica', 4, 'Le decisioni del reparto',
    'Negli ultimi mesi ho preso io tutte le decisioni del reparto, di fatto. Vorrei che fosse anche di diritto, altrimenti mi ritrovo a difendere scelte che non ho fatto.',
    'Di fatto e di diritto. Va bene.', 'Di fatto sì, di diritto no.', 'Restiamo al "di fatto", per ora.'),
  r('p020', 'DIRITTO_DI_VETO', 'demenziale', 4, 'Il diritto di parola sul menù',
    'Se si decide che cosa si mangia alla mensa senza chiedermelo, io quel cibo non lo mangio. Chiedo un posto nella commissione. So che non esiste una commissione: chiedo anche quella.',
    'Creiamo la commissione. E tu ci sei.', 'Non c’è nessuna commissione, e non ci sarà.', 'La commissione resta da fondare.'),

  r('p021', 'RICHIESTA_ASSURDA_BASSO_COSTO', 'demenziale', 1, 'Un nome per il calderone',
    'Passo dieci ore al giorno con lui e non ha un nome. Vorrei chiamarlo Osvaldo e mettere una targhetta. Costa quanto un chiodo e mi cambia la giornata.',
    'Osvaldo. Va bene.', 'Il calderone resta anonimo.', 'Osvaldo attende il battesimo.'),
  r('p022', 'RICHIESTA_ASSURDA_BASSO_COSTO', 'demenziale', 1, 'Una pianta sul banco',
    'Una piccola, di quelle che non muoiono. Dicono che l’aria migliori e comunque a me fa piacere avere qualcosa di vivo che non parla.',
    'Qualcosa di vivo che non parla. Approvato.', 'Niente pianta. C’è già poco spazio.', 'La pianta resta al vivaio.'),
  r('p023', 'RICHIESTA_ASSURDA_BASSO_COSTO', 'sarcastica', 2, 'Il campanello personale',
    'Vorrei un campanellino da suonare quando finisco un lotto. Non per vantarmi: per segnare la fine di una cosa. Costa due monete.',
    'Due monete per la soddisfazione. Va bene.', 'Segna la fine su un foglio.', 'Il campanello aspetta di suonare.'),
  r('p024', 'RICHIESTA_ASSURDA_BASSO_COSTO', 'demenziale', 2, 'Il giorno del cappello',
    'Propongo un giorno al mese in cui si può venire col cappello che si vuole. Non costa niente, non toglie niente, e la gente ne parlerebbe per settimane.',
    'Un giorno col cappello. Non costa niente.', 'Si lavora a testa scoperta.', 'Il cappello aspetta il suo giorno.'),
  r('p025', 'RICHIESTA_ASSURDA_BASSO_COSTO', 'demenziale', 2, 'La cassetta dei suggerimenti',
    'Una scatola con una fessura, all’ingresso. Ci metto dentro io i primi biglietti così parte. Poi vedremo se scrive anche qualcun altro.',
    'Una scatola con una fessura. Facile.', 'I suggerimenti si dicono a voce.', 'La scatola resta un’idea.'),
  r('p026', 'RICHIESTA_ASSURDA_BASSO_COSTO', 'sarcastica', 3, 'Il titolo onorifico',
    'Non chiedo una promozione. Chiedo di poter scrivere "Primo" davanti al mio mestiere sui documenti interni. Non cambia niente per nessuno, tranne che per me.',
    '"Primo". Non cambia niente per nessuno. Va bene.', 'I titoli si guadagnano, non si chiedono.', 'Il titolo resta in sospeso.'),

  r('p027', 'RICHIESTA_ASSURDA_ALTO_COSTO', 'demenziale', 3, 'La sala del silenzio',
    'Una stanza vuota, insonorizzata, dove chiunque possa stare dieci minuti senza che nessuno gli parli. Servono muri nuovi e un po’ di lana. Ne beneficerebbero tutti.',
    'Una stanza vuota costosa. Va bene.', 'Il silenzio si trova fuori, ed è gratis.', 'Il silenzio aspetta i muri.'),
  r('p028', 'RICHIESTA_ASSURDA_ALTO_COSTO', 'sarcastica', 3, 'Il ritiro di squadra',
    'Tre giorni tutti insieme in una locanda in collina, a fare esercizi di fiducia. Costa come un mese di scorte ma torneremmo un gruppo unito. O almeno lo sapremmo.',
    'Torneremo un gruppo unito. Speriamo.', 'La fiducia si costruisce lavorando.', 'La collina resta dov’è.'),
  r('p029', 'RICHIESTA_ASSURDA_ALTO_COSTO', 'demenziale', 4, 'Il ritratto dei fondatori',
    'Propongo di far dipingere un ritratto grande di tutti noi, da appendere all’ingresso. Un pittore vero costa, ma fra cinquant’anni sarà l’unica cosa che resta.',
    'Fra cinquant’anni. Va bene, dipingiamo.', 'Fra cinquant’anni ci ricorderemo di questa spesa.', 'Il pittore aspetta la commessa.'),
  r('p030', 'RICHIESTA_ASSURDA_ALTO_COSTO', 'demenziale', 4, 'Il consulente del benessere',
    'Vorrei che qualcuno venisse una volta a settimana a farci fare esercizi di respirazione al posto della riunione. La riunione dura un’ora e non serve a niente; la respirazione almeno respira.',
    'Al posto della riunione. In effetti.', 'Le riunioni restano. Anche il respiro.', 'Respireremo alla prossima riunione.'),
  r('p031', 'RICHIESTA_ASSURDA_ALTO_COSTO', 'sarcastica', 4, 'Il nuovo emblema',
    'Il nostro emblema è vecchio di quarant’anni e sembra vecchio di quaranta anni. Rifarlo costa, ma daremmo l’idea di un’officina che guarda avanti.',
    'Guardiamo avanti, allora. Rifacciamolo.', 'L’emblema resta. Guardiamo avanti lo stesso.', 'L’emblema vecchio ci guarda ancora.'),
  r('p032', 'RICHIESTA_ASSURDA_ALTO_COSTO', 'demenziale', 3, 'Le divise nuove',
    'Divise uguali per tutti, con lo stemma ricamato. Costano parecchio ma i clienti vedrebbero un’officina seria invece di quindici persone vestite come capita.',
    'Quindici persone vestite uguali. Va bene.', 'Continueremo a vestirci come capita.', 'Come capita, ancora un po’.'),
];
