/* Lotto 03 — soldi in prestito e rimborsi: ANTICIPO_STIPENDIO, RIMBORSO_DISCUTIBILE. */
import { r } from './schema.js';

export default [
  r('a001', 'ANTICIPO_STIPENDIO', 'realistica', 1, 'Il tetto di casa',
    'Si è aperto con la pioggia della settimana scorsa. Il conciatetti vuole essere pagato prima di salire. Restituisco in tre mesi, sulla busta, senza discussioni.',
    'Bene. E chiudi quel tetto.', 'Capisco. Metterò un secchio anche a casa.', 'Il secchio regge ancora un po’.'),
  r('a002', 'ANTICIPO_STIPENDIO', 'realistica', 1, 'La medicina di mia madre',
    'Costa quanto mezza busta e serve adesso, non a fine mese. Non chiedo un regalo: chiedo di anticipare quello che è già mio.',
    'È tuo. Prendilo.', 'Va bene. Troverò un altro modo.', 'Cerco un altro modo intanto.'),
  r('a003', 'ANTICIPO_STIPENDIO', 'realistica', 2, 'Il trasloco',
    'Devo lasciare la stanza dove sto e la nuova vuole due mensilità in anticipo. Ho i soldi, ma li ho fra tre settimane.',
    'Tre settimane le copriamo noi.', 'Allora dormirò dove capita per tre settimane.', 'Vediamo dove dormo intanto.'),
  r('a004', 'ANTICIPO_STIPENDIO', 'sarcastica', 2, 'Un investimento sicuro',
    'C’è un tale al mercato che vende quote di una miniera. Rende il triplo in un mese. Mi serve solo l’anticipo per entrare adesso, prima che chiuda.',
    'Va bene. Ma la miniera non esiste, lo sai.', 'Hai ragione tu. Probabilmente non esiste.', 'La miniera aspetta. Come me.'),
  r('a005', 'ANTICIPO_STIPENDIO', 'realistica', 1, 'La scuola dei figli',
    'La retta si paga tutta insieme a inizio stagione. La mia busta arriva a metà. È l’unica settimana dell’anno in cui i conti non tornano.',
    'Una settimana all’anno la copriamo.', 'Salterò questa stagione, allora.', 'Vedo se si può saltare.'),
  r('a006', 'ANTICIPO_STIPENDIO', 'realistica', 2, 'Il debito col prestatore',
    'Ho preso dei soldi da un tale del porto e gli interessi crescono ogni settimana. Un anticipo adesso mi costa niente; aspettare mi costa il doppio.',
    'Meglio noi che quello del porto.', 'Continuo con quello del porto, allora.', 'Quello del porto aspetta. Male.'),
  r('a007', 'ANTICIPO_STIPENDIO', 'demenziale', 3, 'Il matrimonio del cugino',
    'Si sposa in una città a tre giorni di viaggio e mi ha chiesto di portare il dolce. Il dolce costa. Il viaggio costa. Il cugino non lo sopporto, ma è cugino.',
    'Va bene. Saluta il cugino.', 'Il cugino si sposerà senza dolce.', 'Il cugino aspetta il dolce.'),
  r('a008', 'ANTICIPO_STIPENDIO', 'realistica', 1, 'Gli attrezzi miei',
    'I ferri buoni me li compro io, come tutti. Quello che uso si è spezzato e uno nuovo costa un terzo di busta. Senza, lavoro peggio anche qui.',
    'Se lavori meglio conviene a tutti e due.', 'Uso quelli scadenti, allora.', 'Quelli scadenti per adesso.'),
  r('a009', 'ANTICIPO_STIPENDIO', 'realistica', 2, 'Il funerale',
    'È morto mio fratello. Non è una cosa di cui voglio parlare. Mi serve un anticipo e mi servono due giorni, e preferirei chiedere una cosa sola.',
    'Prendi i soldi e i giorni. Mi dispiace.', 'Va bene. Chiedo solo i giorni, allora.', 'Aspetto. Il funerale no.'),
  r('a010', 'ANTICIPO_STIPENDIO', 'sarcastica', 2, 'La scommessa',
    'Ho puntato sulla corsa dei cinghiali e ho perso. Non chiedo comprensione, chiedo un anticipo. La comprensione la trovo da solo, la vergogna anche.',
    'Onesto, almeno. Va bene.', 'Il cinghiale e io impareremo.', 'Il cinghiale ha già imparato.'),
  r('a011', 'ANTICIPO_STIPENDIO', 'realistica', 1, 'La cauzione',
    'Il padrone di casa chiede una cauzione nuova perché ha cambiato le regole. È una cifra che ho, ma non oggi. In cinque settimane restituisco tutto.',
    'Cinque settimane, d’accordo.', 'Cercherò un’altra stanza.', 'Cerco una stanza intanto.'),
  r('a012', 'ANTICIPO_STIPENDIO', 'realistica', 2, 'Non ho mai chiesto prima',
    'Sono qui da sei anni e non ho mai chiesto un anticipo. Lo dico perché immagino che conti, e perché mi costa chiederlo adesso.',
    'Sei anni contano. Ecco.', 'Va bene. Torno a non chiedere.', 'Torno a non chiedere, per ora.'),

  r('a013', 'RIMBORSO_DISCUTIBILE', 'sarcastica', 2, 'Il corso di leadership',
    'Tre giorni in una locanda sul lago con un maestro che insegna a comandare. Costa come sei mesi di scorte, ma dopo saprò guidare le persone. Ho già prenotato.',
    'Hai già prenotato. Bene, allora paghiamo.', 'Disdirò. Con grande capacità di leadership.', 'La locanda tiene il posto ancora un po’.'),
  r('a014', 'RIMBORSO_DISCUTIBILE', 'realistica', 2, 'Il viaggio dal fornitore',
    'Sono andato di persona a contrattare le radici e ho ottenuto uno sconto. Il viaggio l’ho pagato io: vitto, alloggio e cavallo. Vorrei indietro quello che ho speso.',
    'Giusto: hai risparmiato più di quanto hai speso.', 'Allora la prossima volta scrivo una lettera.', 'La prossima volta scrivo, forse.'),
  r('a015', 'RIMBORSO_DISCUTIBILE', 'sarcastica', 3, 'La cena coi clienti',
    'Abbiamo cenato coi tre della capitale. Il conto è alto perché uno di loro ha ordinato il pesce grande. Il contratto l’hanno firmato, comunque.',
    'Il pesce grande ha portato il contratto. Paghiamo.', 'Il pesce grande lo paghi tu, allora.', 'Il pesce grande aspetta il rimborso.'),
  r('a016', 'RIMBORSO_DISCUTIBILE', 'demenziale', 3, 'Il consulente spirituale',
    'Ho consultato una veggente sull’andamento del mercato delle pozioni. Ha detto cose molto interessanti sul prossimo trimestre. Costa, ma è una spesa di studi di settore.',
    'Studi di settore. Va bene, per una volta.', 'La veggente non l’aveva previsto, immagino.', 'La veggente aspetta il pagamento.'),
  r('a017', 'RIMBORSO_DISCUTIBILE', 'realistica', 2, 'I libri del mestiere',
    'Ho comprato due trattati sulla distillazione a freddo. Li tengo in officina e li usa chiunque. Vorrei che li pagasse l’officina, visto che li usa l’officina.',
    'Se li usa l’officina li paga l’officina. Giusto.', 'Allora me li riporto a casa.', 'Restano in officina intanto, a mie spese.'),
  r('a018', 'RIMBORSO_DISCUTIBILE', 'sarcastica', 3, 'Il cavallo veloce',
    'Per la consegna urgente ho noleggiato un cavallo veloce invece del carro. È arrivata in tempo. Costa quattro volte il carro, ma è arrivata in tempo.',
    'È arrivata in tempo. Va bene.', 'La prossima volta arriverà tardi e costerà poco.', 'Il cavallo ha già corso, comunque.'),
  r('a019', 'RIMBORSO_DISCUTIBILE', 'realistica', 2, 'Il grembiule comprato di corsa',
    'Il mio si è bruciato in mezzo al turno e ne ho comprato uno al mercato per finire la giornata. Ho lo scontrino ed è la cifra che è, cioè poca.',
    'Poca cifra, nessun problema.', 'Terrò lo scontrino come ricordo.', 'Lo scontrino aspetta con me.'),
  r('a020', 'RIMBORSO_DISCUTIBILE', 'demenziale', 4, 'Il ritiro di meditazione',
    'Una settimana di silenzio su una montagna, per tornare più concentrato. Il silenzio costa parecchio, sorprendentemente. Ma tornerei un’altra persona.',
    'Torna un’altra persona, allora. Speriamo migliore.', 'Il silenzio te lo fai in officina, gratis.', 'La montagna resta dov’è.'),
  r('a021', 'RIMBORSO_DISCUTIBILE', 'sarcastica', 2, 'Il pranzo di lavoro da solo',
    'Ho pranzato pensando al lavoro. Era un pranzo di lavoro a tutti gli effetti: il lavoro c’era, io c’ero, e ho pensato tutto il tempo.',
    'Ci hai pensato tutto il tempo. Va bene, una volta.', 'Pensare al lavoro non è un pranzo di lavoro.', 'Ci penserò ancora, gratis.'),
  r('a022', 'RIMBORSO_DISCUTIBILE', 'realistica', 2, 'Gli ingredienti anticipati',
    'Il fornitore aveva le radici buone e voleva contanti subito. Ho pagato di tasca mia perché domani non ci sarebbero più state. Sono nel magazzino, si possono contare.',
    'Ci sono e servono. Rimborsato.', 'La prossima volta le lascio al fornitore.', 'Le radici sono già in magazzino, comunque.'),
];
