/* Lotto 11 — l'ultimo giro: quello che manca, e qualche assurdita' in piu'. */
import { r } from './schema.js';

export default [
  r('s037', 'SICUREZZA_SUL_LAVORO', 'realistica', 1, 'I guanti bucati',
    'Quelli in dotazione hanno tutti un buco nello stesso punto, perché il modello è sbagliato. Chi maneggia gli acidi se ne accorge tardi.',
    'Modello sbagliato, guanti nuovi. Fatto.', 'Fate attenzione al buco.', 'Attenzione al buco, ancora un po’.'),
  r('s038', 'SICUREZZA_SUL_LAVORO', 'realistica', 3, 'Il magazzino dei volatili',
    'Teniamo i solventi accanto al forno perché non c’è altro posto. Finché nessuno rovescia niente va bene. Basta una volta.',
    'Basta una volta. Li spostiamo.', 'Nessuno rovescerà niente.', 'Restano lì, per ora.'),
  r('s039', 'SICUREZZA_SUL_LAVORO', 'sarcastica', 4, 'Il regolamento',
    'Ho scritto io un regolamento di sicurezza perché non ne esisteva uno. Sono due pagine. Vorrei che qualcuno lo leggesse, e possibilmente lo firmasse.',
    'Lo leggo e lo firmo. Grazie di averlo scritto.', 'Due pagine di regolamento non servono a nessuno.', 'Le due pagine aspettano una firma.'),
  r('m045', 'STRUMENTO_ROTTO', 'demenziale', 2, 'Il campanello della porta',
    'Suona da solo. A ore casuali. Ci alziamo tutti, andiamo alla porta, non c’è nessuno. È successo undici volte ieri.',
    'Undici volte. Aggiustiamolo.', 'Ignoratelo.', 'Ignoriamo il campanello, allora.'),
  r('m046', 'BENEFIT_MATERIALE_PICCOLO', 'realistica', 2, 'Un secondo mazzo di chiavi',
    'Siamo in cinque ad aprire e c’è un mazzo solo. Chi arriva primo aspetta chi ha le chiavi, e chi ha le chiavi a volte è in ritardo.',
    'Cinque persone, due mazzi. Ovvio.', 'Aspettate chi ha le chiavi.', 'Aspettiamo ancora un po’.'),
  r('m047', 'BENEFIT_MATERIALE_GRANDE', 'realistica', 3, 'Il tetto sopra il magazzino',
    'Da riparare davvero, non con le pezze. È il posto dove sta la merce, ed è l’unico locale che non ha visto un muratore in vent’anni.',
    'Vent’anni. Chiamiamo il muratore.', 'Le pezze reggeranno un altro inverno.', 'Le pezze reggono ancora un po’.'),
  r('t039', 'PERMESSO_PERSONALE', 'realistica', 2, 'La visita che rimando da mesi',
    'Ho un dolore che rimando perché non trovo mai il momento. Il guaritore ha un posto martedì. Se lo salto, il prossimo è fra due mesi.',
    'Vai martedì. Non rimandare oltre.', 'Prendi il posto fra due mesi.', 'Due mesi passano in fretta, dici?'),
  r('t040', 'FLESSIBILITA_ORARIA', 'demenziale', 3, 'Il pisolino',
    'Ho letto che un quarto d’ora di sonno dopo pranzo raddoppia la resa del pomeriggio. Chiedo un quarto d’ora, e sono disposto a recuperarlo la sera.',
    'Un quarto d’ora recuperato. Proviamo.', 'Si dorme a casa.', 'Il pisolino aspetta la sera.'),
  r('t041', 'FERIE_LUNGHE', 'realistica', 3, 'Il congedo per la nascita',
    'Nasce mia figlia fra tre settimane. Chiedo dieci giorni. Non tornerò prima e preferisco dirlo adesso invece di sparire.',
    'Dieci giorni. Auguri.', 'Prenditene tre.', 'Ne riparliamo. Lei nasce comunque.'),
  r('c036', 'FORMAZIONE', 'sarcastica', 3, 'Il corso di negoziazione',
    'Vorrei imparare a trattare meglio coi fornitori. Mi rendo conto che il primo effetto sarà che tratterò meglio anche con voi.',
    'Tratterai meglio anche con me. Rischiamo.', 'Tratti già abbastanza bene.', 'Il corso aspetta, e io imparo lo stesso.'),
  r('c037', 'PROMOZIONE_IMMERITATA', 'sarcastica', 3, 'Il titolo che mi spetta',
    'Sono l’unico del reparto senza un titolo scritto sul registro. Non chiedo compiti diversi, chiedo che ci sia scritto qualcosa accanto al mio nome.',
    'Qualcosa accanto al nome. Va bene.', 'Il nome basta.', 'Il nome resta da solo.'),
  r('c038', 'RICONOSCIMENTO', 'realistica', 2, 'Il lavoro invisibile',
    'Quello che faccio si nota solo quando manca. Da tre anni non manca mai. Vorrei che ogni tanto si notasse anche quando c’è.',
    'Si nota. Da oggi anche a voce.', 'Se non manca vuol dire che funziona.', 'Continuerà a non mancare.'),
  r('p040', 'CONFLITTO_TRA_COLLEGHI', 'sarcastica', 3, 'Il territorio',
    'Due reparti litigano per chi deve usare il banco lungo. È diventata una questione di principio, e le questioni di principio non le risolve chi ci sta dentro.',
    'Decido io chi usa il banco. Fine.', 'Se la vedano fra reparti.', 'La questione di principio resta aperta.'),
  r('p041', 'LAMENTELA_SU_COLLEGA', 'sarcastica', 3, 'Il grande esperto',
    'C’è uno che spiega a tutti come si fa il loro lavoro. Non lo sa fare, ma lo spiega. Ha una sicurezza che ammiro e che vorrei smettesse di usare su di me.',
    'Gli chiedo di spiegare meno. Con delicatezza.', 'Ascoltalo e fai come vuoi.', 'Continuerà a spiegare, immagino.'),
  r('p042', 'DIRITTO_DI_VETO', 'sarcastica', 4, 'Il diritto di dire no ai clienti',
    'Ci sono clienti che ci fanno perdere soldi e li accettiamo lo stesso. Vorrei poterne rifiutare uno all’anno, a mia scelta, senza dover spiegare perché.',
    'Uno all’anno, senza spiegazioni. Va bene.', 'I clienti li decide chi paga gli stipendi.', 'Il diritto aspetta.'),
  r('p043', 'DIRITTO_DI_VETO', 'realistica', 4, 'Firmo io quello che esce',
    'Se un lotto esce difettoso la colpa è mia, ma la decisione di farlo uscire non è mia. Chiedo di poter fermare una consegna. Una sola parola: no.',
    'Puoi fermarla. È giusto che chi risponde decida.', 'La consegna la decide chi vende.', 'Ci penso. Intanto firmo per gli altri.'),
  r('p044', 'RICHIESTA_ASSURDA_BASSO_COSTO', 'demenziale', 1, 'Il gatto ufficiale',
    'Ne gira uno nel cortile e mangia i topi. Propongo di dargli un nome e una ciotola, così diventa nostro e resta. Costa gli avanzi.',
    'Il gatto è assunto. Costo: gli avanzi.', 'Il gatto è del cortile, non nostro.', 'Il gatto continua senza contratto.'),
  r('p045', 'RICHIESTA_ASSURDA_BASSO_COSTO', 'sarcastica', 3, 'La sedia girevole',
    'Ne ho vista una che gira su sé stessa. Non serve a niente in termini di lavoro. Serve moltissimo in termini di dignità.',
    'In termini di dignità. Va bene.', 'La dignità si trova altrove.', 'La sedia gira senza di te.'),
  r('p046', 'RICHIESTA_ASSURDA_ALTO_COSTO', 'demenziale', 4, 'Il giardino sul tetto',
    'Sul tetto c’è spazio e non ci va nessuno. Un piccolo giardino di erbe: sarebbe bello, e in teoria coltiveremmo qualche ingrediente. In teoria.',
    'In teoria. Va bene, facciamolo.', 'Il tetto resta un tetto.', 'Il tetto aspetta il suo giardino.'),
  r('p047', 'RICHIESTA_ASSURDA_ALTO_COSTO', 'sarcastica', 3, 'La festa di fine stagione',
    'Non abbiamo mai festeggiato niente in quarantotto anni. Propongo una sera, cibo e musica, per tutti. Costa come due giornate di produzione.',
    'Quarantotto anni senza feste. Facciamola.', 'Festeggeremo quando ci sarà da festeggiare.', 'La festa resta un’idea.'),
  r('riserva-11', 'PROPOSTA_ASSUNZIONE', 'realistica', 1, 'Manca una persona',
    'Da qualche parte siamo scoperti e il lavoro si accumula. Assumere costa e non assumere costa: la differenza è che il secondo costo non si vede in bilancio.',
    'Il costo che non si vede è il peggiore. Assumiamo.', 'Regge ancora un po’.', 'Reggerà ancora un po’, spero.'),
  r('riserva-12', 'PROPOSTA_LICENZIAMENTO', 'realistica', 2, 'Siamo in troppi',
    'Con questi numeri l’organico è sovradimensionato. Non è una cosa che mi fa piacere dire e non è nemmeno una cosa che mi fa piacere proporre.',
    'Non fa piacere a nessuno. Facciamolo.', 'Nessuno esce. Troviamo altro.', 'Ci penso. I numeri restano quelli.'),
  r('riserva-13', 'PROPOSTA_MARKETING', 'realistica', 1, 'Farci vedere',
    'Nessuno sa che esistiamo, fuori dalle tre strade qui intorno. Una spesa modesta e mirata cambierebbe questa cosa, o almeno la scalfirebbe.',
    'Almeno la scalfiamo. Va bene.', 'Ci conoscono quelli che contano.', 'Continuiamo a non farci vedere.'),
  r('riserva-14', 'FORMAZIONE', 'realistica', 1, 'Vorrei imparare una cosa',
    'C’è una competenza che qui non ha nessuno e che ci servirebbe. Non è gratis impararla, e nel frattempo rendo meno. Dopo, però, la sappiamo.',
    'Dopo la sappiamo. Vai.', 'Impariamo quando servirà davvero.', 'Imparerò più avanti, forse.'),
  r('riserva-15', 'PROMOZIONE', 'realistica', 2, 'Vorrei crescere',
    'Faccio la stessa cosa da tanto e la faccio bene. Non chiedo di comandare qualcuno: chiedo che ci sia una strada, e di sapere qual è.',
    'La strada c’è, e comincia adesso.', 'Non c’è una strada. Almeno lo sai.', 'La strada la cerchiamo insieme, forse.'),
  r('riserva-16', 'SICUREZZA_SUL_LAVORO', 'realistica', 1, 'C’è una cosa pericolosa',
    'Non è ancora successo niente. Lo dico proprio per questo: dopo che succede, dirlo non serve più a niente.',
    'Prima che succeda. Grazie.', 'Staremo attenti.', 'Staremo attenti, per ora.'),
  r('riserva-17', 'FERIE_LUNGHE', 'realistica', 2, 'Ho bisogno di staccare',
    'Non sono malato e non sto peggio di altri. Sono stanco, e la stanchezza che ho non passa con una domenica.',
    'Non passa con una domenica. Prenditi tempo.', 'Riposati nel fine settimana.', 'La stanchezza aspetta con me.'),
  r('riserva-18', 'CAMBIO_MANSIONE', 'realistica', 1, 'Non è il mio posto',
    'Faccio una cosa che non so fare bene, e lo vedete anche voi. Ce n’è un’altra che saprei fare, e nessuno me l’ha mai chiesto.',
    'Nessuno te l’aveva chiesto. Cambiamo.', 'Impara quella che fai.', 'Ci penso. Intanto continuo male.'),
  r('riserva-19', 'ANTICIPO_STIPENDIO', 'realistica', 1, 'Mi servono adesso',
    'Non è una spesa voluttuaria e non è una cosa di cui voglio parlare. È una cifra che è già mia, solo qualche settimana prima.',
    'È già tua. Prendila.', 'Aspetta la fine del mese.', 'Aspetto. Anche la cosa aspetta.'),
  r('riserva-20', 'CONFLITTO_TRA_COLLEGHI', 'realistica', 2, 'Non si lavora così',
    'Fra due persone del reparto è successo qualcosa e adesso tutto passa attraverso me. Sono diventato un ponte, e i ponti si consumano.',
    'Smetti di fare il ponte. Ci penso io.', 'Fai il ponte ancora un po’.', 'Il ponte regge ancora, immagino.'),
];
