/* Lotto 09 — rinforzo agli assistant manager, che erano i piu' magri. */
import { r } from './schema.js';

export default [
  r('g034', 'PROPOSTA_TAGLIO_WELFARE', 'realistica', 2, 'La legna d’inverno',
    'Diamo una fascina a testa da novembre a marzo. Non lo fa nessun altro nel quartiere. Toglierla si sente subito, ma è una spesa che si vede in bilancio.',
    'La togliamo. Si sentirà.', 'La legna resta. Fa freddo davvero.', 'La legna resta accesa, per ora.'),
  r('g035', 'PROPOSTA_TAGLIO_WELFARE', 'realistica', 3, 'Il carro della sera',
    'Riportiamo a casa chi abita lontano quando piove. È un cavallo, un uomo e due ore. Chi abita vicino non lo usa e nemmeno se ne accorgerebbe.',
    'Chi abita vicino non se ne accorge. Tagliamo.', 'Chi abita lontano sì, però.', 'Il carro parte ancora, per ora.'),
  r('g036', 'PROPOSTA_TAGLIO_WELFARE', 'sarcastica', 3, 'Il tè del pomeriggio',
    'Costa poco e fa perdere venti minuti a diciassette persone, tutti i giorni. Venti per diciassette fa quasi un’ora di lavoro al giorno, in tazze.',
    'Un’ora al giorno in tazze. Basta tè.', 'Il tè resta. Un’ora di tregua serve.', 'Il tè continua a bollire.'),
  r('g037', 'PROPOSTA_TAGLIO_WELFARE', 'realistica', 4, 'La cassa di soccorso',
    'Mettiamo da parte una somma per chi ha un guaio. Nessuno l’ha usata negli ultimi mesi, e quei soldi fermi ci servirebbero adesso.',
    'Nessuno la usa. La prendiamo.', 'Esiste proprio per quando non serve.', 'Resta ferma un altro po’.'),
  r('g038', 'PROPOSTA_LICENZIAMENTO', 'realistica', 2, 'Il reparto che non rende',
    'Un intero reparto produce meno di quanto costa da quattro mesi. O si chiude, o si trova cosa gli manca. Chiudere lo so fare; l’altra cosa no.',
    'Chiudiamolo. Non so fare l’altra cosa nemmeno io.', 'Cerchiamo cosa gli manca.', 'Ci pensiamo. Il reparto intanto costa.'),
  r('g039', 'PROPOSTA_LICENZIAMENTO', 'realistica', 3, 'Chi è arrivato per ultimo',
    'Se dobbiamo tagliare, il criterio più semplice è l’ultimo arrivato. Non è il più giusto. È il più semplice, e nessuno può discuterlo.',
    'Il più semplice, non il più giusto. Va bene.', 'Non taglio col criterio più comodo.', 'Il criterio aspetta di essere scelto.'),
  r('g040', 'PROPOSTA_LICENZIAMENTO', 'sarcastica', 4, 'La riduzione naturale',
    'Non licenziamo nessuno: semplicemente non sostituiamo chi se ne va. In sei mesi siamo in quattro di meno senza aver fatto niente. Elegante, no?',
    'Elegante. Anche un po’ vigliacco, ma va bene.', 'Chi se ne va si sostituisce.', 'L’eleganza aspetta.'),
  r('g041', 'PROPOSTA_OUTSOURCING', 'realistica', 2, 'Il magazzino a un terzo',
    'C’è un deposito fuori porta che tiene la merce a meno di quanto ci costa il nostro spazio. Perdiamo di averla sotto mano.',
    'Sotto mano non è gratis. Spostiamo.', 'La merce resta dove la vediamo.', 'La merce resta qui, per ora.'),
  r('g042', 'PROPOSTA_OUTSOURCING', 'realistica', 3, 'La contabilità a un cambiavalute',
    'Tiene i conti a mezza dozzina di botteghe e prende poco. Sa quello che fa. Vede anche tutti i nostri numeri, e questo è il punto.',
    'Vede i nostri numeri. Accettiamo il punto.', 'I conti restano in casa.', 'I conti restano qui, per ora.'),
  r('g043', 'PROPOSTA_OUTSOURCING', 'sarcastica', 4, 'Tutto tranne la ricetta',
    'La mia proposta radicale: teniamo la formula e diamo fuori tutto il resto. Diventiamo tre persone e un segreto. Costa un quarto di adesso.',
    'Tre persone e un segreto. Proviamo.', 'Un’officina è anche le persone.', 'La proposta radicale attende.'),
  r('g044', 'PROPOSTA_RIORGANIZZAZIONE', 'realistica', 2, 'Un solo responsabile per turno',
    'Adesso decidono in tre e si contraddicono. Uno solo per turno, a rotazione. Chi perde il ruolo la prenderà male, ma le contraddizioni finiscono.',
    'Uno solo. Che se la prendano.', 'Restiamo in tre. Meno litigi.', 'I tre continuano a contraddirsi.'),
  r('g045', 'PROPOSTA_RIORGANIZZAZIONE', 'realistica', 3, 'Il lavoro a squadre fisse',
    'Adesso ognuno fa un po’ tutto e nessuno diventa bravo in niente. Squadre fisse: due settimane di caos e poi si specializzano.',
    'Due settimane di caos. Le mettiamo in conto.', 'La flessibilità ci ha salvati più volte.', 'Il caos può aspettare.'),
  r('g046', 'PROPOSTA_RIORGANIZZAZIONE', 'sarcastica', 4, 'Il grande spostamento',
    'Ho disegnato una pianta nuova dell’officina. Ogni banco si sposta, ogni scaffale cambia posto. Per una settimana non si produce niente. Poi, secondo i miei conti, andrà tutto meglio.',
    'Secondo i tuoi conti. Speriamo bene.', 'Una settimana ferma non ce la possiamo permettere.', 'La pianta resta un disegno.'),
  r('g047', 'PROPOSTA_CONSULENZA', 'realistica', 2, 'Il maestro distillatore',
    'Un vecchio maestro passa due giorni a guardare come lavoriamo e ci dice cosa sbagliamo. Prende caro, ma di distillazione ne sa più di tutti noi.',
    'Ne sa più di noi. Chiamiamolo.', 'Impariamo dai nostri errori, gratis.', 'Il maestro ha l’agenda piena, comunque.'),
  r('g048', 'PROPOSTA_CONSULENZA', 'sarcastica', 3, 'Lo studio di mercato',
    'Un tale vende uno studio su cosa comprerà il regno l’anno prossimo. Costa parecchio. Non so quanto ci abbia preso l’anno scorso, perché non l’abbiamo comprato.',
    'Non sappiamo se ci prende. Compriamolo e scopriamolo.', 'Continuiamo a non saperlo, gratis.', 'Lo studio resta invenduto.'),
  r('g049', 'PROPOSTA_CONSULENZA', 'realistica', 3, 'Il perito della sicurezza',
    'Prima che arrivino gli ispettori, meglio che venga qualcuno a dirci cosa troveranno. Costa meno della multa, se la multa arriva.',
    'Meno della multa. Chiamiamolo.', 'Speriamo che non vengano.', 'Speriamo di avere tempo.'),
  r('g050', 'PROPOSTA_MARKETING', 'realistica', 2, 'Le fiale col nostro segno',
    'Vendiamo in fiale anonime e nessuno sa che sono nostre. Un segno inciso sul vetro costa poco per pezzo e si vede ogni volta che qualcuno beve.',
    'Si vede ogni volta. Facciamolo.', 'Il vetro anonimo costa meno.', 'Il vetro resta anonimo.'),
  r('g051', 'PROPOSTA_MARKETING', 'sarcastica', 3, 'Il regalo ai nobili',
    'Mandiamo una cassa in omaggio alle tre case importanti. Non ci pagheranno, ma se una la usa lo saprà tutta la corte. È una scommessa, e le scommesse si perdono.',
    'Le scommesse si perdono. Ma questa la facciamo.', 'Non regaliamo casse ai ricchi.', 'Le casse restano in magazzino.'),
  r('g052', 'PROPOSTA_MARKETING', 'realistica', 3, 'Il banco al mercato del giovedì',
    'Un banco fisso al mercato grande, tutti i giovedì. Serve una persona per una giornata a settimana, e vendiamo direttamente senza intermediari.',
    'Senza intermediari. Prendiamo il banco.', 'Non abbiamo una persona da staccare.', 'Il banco resta libero.'),
  r('g053', 'PROPOSTA_AUMENTO_RITMI', 'realistica', 2, 'Recuperare l’arretrato',
    'Abbiamo undici ordini in ritardo. O si spinge per due settimane, o cominciamo a perdere clienti che poi non tornano.',
    'Due settimane. Poi si respira.', 'I clienti aspetteranno. Speriamo.', 'L’arretrato cresce intanto.'),
  r('g054', 'PROPOSTA_AUMENTO_RITMI', 'sarcastica', 4, 'Il turno in più',
    'Aggiungiamo un turno serale e chiediamo a chi c’è già di coprirlo a rotazione. È volontario, naturalmente. Sarà volontario in modo molto convinto.',
    'Volontario in modo convinto. Ho capito.', 'Niente turno in più.', 'Il turno serale aspetta i volontari.'),
  r('g055', 'PROPOSTA_ASSUNZIONE', 'realistica', 2, 'Il sostituto di chi è uscito',
    'È andato via un mese fa e il suo lavoro è rimasto lì. Lo stiamo dividendo fra quattro persone che avevano già il loro.',
    'Il lavoro non sparisce da solo. Assumiamo.', 'Continuiamo a dividerlo.', 'Continuiamo a dividerlo, per ora.'),
  r('g056', 'PROPOSTA_ASSUNZIONE', 'realistica', 3, 'Una persona per la notte',
    'Chi fa la notte è solo e da un anno chiede di essere in due. Costa un salario. Se una notte succede qualcosa, costa molto di più.',
    'Se succede qualcosa costa di più. Assumiamo.', 'La notte resta di uno.', 'La notte resta di uno, per ora.'),
  r('g057', 'PROPOSTA_INVESTIMENTO', 'realistica', 2, 'La macina a mulino',
    'Al posto di macinare a mano. Costa come tre mesi di un salario e libera due persone per il lavoro vero. Si rompe raramente, dicono.',
    'Libera due persone. Compriamola.', 'Macineremo a mano.', 'A mano ancora un po’.'),
  r('g058', 'PROPOSTA_INVESTIMENTO', 'sarcastica', 4, 'L’officina di sopra',
    'Il piano di sopra è vuoto e in vendita. Comprarlo adesso costa la metà di quanto costerà quando ci servirà. Il rischio è che non ci serva mai.',
    'Il rischio è che non serva mai. Compriamo.', 'Compreremo quando servirà, al doppio.', 'Il piano di sopra resta vuoto.'),
  r('g059', 'PROPOSTA_TAGLIO_COSTI', 'realistica', 2, 'Le fiale di seconda scelta',
    'Il vetro con una piccola imperfezione costa un terzo in meno e tiene uguale. Si vede, però, e quello che si vede il cliente lo giudica.',
    'Il cliente giudicherà. Risparmiamo.', 'Il vetro resta buono.', 'Il vetro buono ancora un po’.'),
  r('g060', 'PROPOSTA_TAGLIO_COSTI', 'sarcastica', 3, 'Le luci',
    'Spegniamo metà lanterne. Si vede lo stesso, più o meno. E chi lavora di fino può avvicinarsi alla finestra.',
    'Si vede lo stesso, più o meno. Va bene.', 'Le lanterne restano accese.', 'Restano accese, per ora.'),
  r('g061', 'PROPOSTA_INVESTIMENTO', 'realistica', 3, 'Le scorte a prezzo di stagione',
    'Comprare adesso il fabbisogno di sei mesi costa un quinto in meno. Ci restano soldi bloccati in magazzino, e se la domanda cambia restano bloccati lì.',
    'Un quinto in meno. Compriamo.', 'Non blocco la cassa in magazzino.', 'Il prezzo di stagione scade, però.'),
  r('g062', 'PROPOSTA_MARKETING', 'demenziale', 4, 'Il concorso',
    'Un concorso: chi trova il tappo dorato dentro una fiala vince una fornitura a vita. Ne mettiamo uno solo. Il costo è basso e se ne parlerebbe per mesi.',
    'Un tappo dorato. Se ne parlerà.', 'Non facciamo concorsi.', 'Il tappo dorato resta nel cassetto.'),
  r('g063', 'PROPOSTA_AUMENTO_RITMI', 'realistica', 3, 'La produzione a obiettivo',
    'Diamo a ogni squadra un numero da raggiungere invece di un orario da rispettare. Chi finisce prima va a casa. Chi non ci arriva, non va a casa.',
    'Chi finisce prima va a casa. Proviamo.', 'L’orario resta un orario.', 'L’obiettivo aspetta.'),
  r('g064', 'PROPOSTA_ASSUNZIONE', 'realistica', 3, 'Un venditore vero',
    'Vendiamo a chi ci cerca. Nessuno qui va a cercare i clienti. Una persona che lo faccia di mestiere si paga da sola, se è brava. Se non è brava, no.',
    'Se è brava si paga da sola. Prendiamola.', 'Continuiamo ad aspettare che ci cerchino.', 'Aspettiamo ancora un po’.'),
];
