/* Lotto 10 — ancora dipendenti: le cose che si rompono, il tempo, i soldi. */
import { r } from './schema.js';

export default [
  r('m036', 'STRUMENTO_ROTTO', 'realistica', 1, 'La chiave del magazzino',
    'Si è piegata e adesso apre solo a chi sa il trucco. Il trucco lo sappiamo in tre, e quando non ci siamo nessuno entra.',
    'Una chiave nuova. Elementare.', 'Insegnate il trucco agli altri.', 'Il trucco resta un trucco.'),
  r('m037', 'STRUMENTO_ROTTO', 'sarcastica', 2, 'La stadera del carico',
    'Pesa sempre due libbre in più. L’abbiamo scoperto perché un cliente pesava anche lui. Adesso togliamo due libbre a mente, tutti, ogni volta.',
    'Basta aritmetica mentale. Ripariamola.', 'Continuiamo a togliere due libbre.', 'Due libbre a mente, ancora.'),
  r('m038', 'STRUMENTO_ROTTO', 'realistica', 2, 'Il pozzo del cortile',
    'La corda si sta sfilacciando e il secchio è caduto due volte. Ripescarlo costa mezz’ora. La corda costa meno di mezz’ora.',
    'La corda costa meno. Cambiamola.', 'Ripescheremo il secchio.', 'Ripeschiamo ancora un po’.'),
  r('m039', 'STRUMENTO_ROTTO', 'realistica', 3, 'L’alambicco grande',
    'La serpentina è ostruita e rende metà. È il pezzo su cui gira metà della produzione. Ripararlo ferma tutto per un giorno; non ripararlo ci ferma a metà tutti i giorni.',
    'Un giorno fermo contro tutti i giorni a metà. Ripariamo.', 'Andiamo avanti a metà.', 'A metà ancora un po’.'),
  r('m040', 'BENEFIT_MATERIALE_PICCOLO', 'realistica', 1, 'Una cassetta con la chiave',
    'Non ho dove lasciare le mie cose e me le porto dietro tutto il giorno. Una cassetta con la chiave costa poco e mi libera le mani.',
    'Una cassetta. Fatto.', 'Portati dietro le tue cose.', 'Continuo a portarmele dietro.'),
  r('m041', 'BENEFIT_MATERIALE_PICCOLO', 'realistica', 1, 'Un attaccapanni',
    'I mantelli bagnati stanno sulle casse e le casse si bagnano. Un attaccapanni costa meno di una cassa rovinata.',
    'Meno di una cassa rovinata. Giusto.', 'Le casse regggeranno.', 'Le casse si bagnano ancora un po’.'),
  r('m042', 'BENEFIT_MATERIALE_PICCOLO', 'demenziale', 2, 'Un tappeto per l’ingresso',
    'Entra tutto il fango del cortile e finisce nelle pozioni. Non è una questione di eleganza: è che le pozioni al fango non le vuole nessuno.',
    'Le pozioni al fango non si vendono. Giusto.', 'Pulitevi le scarpe.', 'Ci puliamo le scarpe, intanto.'),
  r('m043', 'BENEFIT_MATERIALE_GRANDE', 'realistica', 2, 'Il banco per gli acidi',
    'Li lavoriamo sullo stesso banco di tutto il resto e prima o poi qualcosa si contamina. Un banco separato costa, ma è l’unica soluzione vera.',
    'Un banco separato. Facciamolo.', 'Staremo attenti.', 'Staremo attenti ancora un po’.'),
  r('m044', 'BENEFIT_MATERIALE_GRANDE', 'sarcastica', 3, 'La stufa nel reparto',
    'D’inverno qui dentro si vede il fiato. Non chiedo il caldo: chiedo che l’acqua nei catini non ghiacci, perché quando ghiaccia non si lavora.',
    'Se ghiaccia non si lavora. Stufa.', 'Vestitevi pesante.', 'Ci vestiamo pesante, per ora.'),
  r('s033', 'AUMENTO_STIPENDIO', 'realistica', 2, 'Il confronto col mercato',
    'Ho chiesto in giro cosa si prende per il mio mestiere. La forbice è quella, e io sto sotto al minimo. Non chiedo il massimo: chiedo di entrare nella forbice.',
    'Entrare nella forbice è il minimo. Fatto.', 'La forbice è larga. Stai dentro anche così.', 'La forbice resta dov’è.'),
  r('s034', 'AUMENTO_STIPENDIO', 'demenziale', 3, 'L’adeguamento astrologico',
    'Sono entrato sotto un segno sfavorevole e questo ha condizionato la trattativa iniziale. Chiedo un adeguamento che tenga conto della congiuntura celeste di allora.',
    'La congiuntura celeste. Va bene, una volta.', 'Il cielo non entra in busta paga.', 'Il cielo aspetta insieme a te.'),
  r('s035', 'AUMENTO_MERITATO', 'realistica', 3, 'La commessa l’ho salvata io',
    'Quando il fornitore è saltato ho trovato le radici in due giorni, di mia iniziativa, chiamando gente che conosco. Nessuno me l’aveva chiesto.',
    'Nessuno te l’aveva chiesto. Vale doppio.', 'Hai fatto il tuo dovere.', 'Ci penso. La commessa è già consegnata.'),
  r('s036', 'AUMENTO_MERITATO', 'realistica', 2, 'Il turno che nessuno vuole',
    'Faccio il turno della domenica da otto mesi perché nessun altro lo prende. Lo faccio volentieri. Vorrei che si vedesse.',
    'Otto mesi di domeniche. Si vede da oggi.', 'Se lo fai volentieri, va bene così.', 'Le domeniche continuano.'),
  r('a023', 'ANTICIPO_STIPENDIO', 'realistica', 1, 'La caparra per il carro',
    'Ho trovato un carro usato che mi serve per venire a lavorare. Chiedono la caparra domani. Restituisco in quattro mesi.',
    'Quattro mesi. Va bene.', 'Continuerai a piedi.', 'Il carro se lo prende un altro, intanto.'),
  r('a024', 'ANTICIPO_STIPENDIO', 'sarcastica', 2, 'Il regalo di nozze',
    'Si sposa mia sorella e la tradizione vuole un regalo che non posso permettermi. La tradizione non l’ho scritta io.',
    'La tradizione non l’hai scritta tu. Prendi.', 'Le tradizioni si possono anche cambiare.', 'La tradizione aspetta.'),
  r('a025', 'RIMBORSO_DISCUTIBILE', 'realistica', 2, 'Il fabbro chiamato di notte',
    'Si è rotto il forno a mezzanotte e ho chiamato il fabbro pagandolo di tasca mia. Di notte costa il doppio. La mattina si lavorava.',
    'La mattina si lavorava. Rimborsato.', 'Potevi aspettare la mattina.', 'Il fabbro è già stato pagato, però.'),
  r('a026', 'RIMBORSO_DISCUTIBILE', 'demenziale', 3, 'Il cappello da lavoro',
    'Ho comprato un cappello che mi fa sembrare più autorevole quando tratto coi fornitori. Ha funzionato: ho spuntato uno sconto. Chiedo il rimborso del cappello.',
    'Il cappello ha spuntato lo sconto. Rimborsato.', 'L’autorevolezza non è un costo aziendale.', 'Il cappello resta tuo, per ora.'),
  r('t033', 'PERMESSO_PERSONALE', 'realistica', 1, 'La casa allagata',
    'È piovuto dentro e devo esserci quando arriva chi ripara. Mezza giornata, e non posso spostarla perché non la sposto io.',
    'Vai. La casa prima.', 'Manda qualcuno di famiglia.', 'L’acqua non aspetta, però.'),
  r('t034', 'PERMESSO_PERSONALE', 'sarcastica', 2, 'Il ritiro del premio',
    'Ho vinto il concorso di poesia del quartiere. La premiazione è di mercoledì mattina. Non è importante, ma è la prima cosa che vinco in vita mia.',
    'La prima cosa che vinci. Vai.', 'La poesia si legge anche dopo.', 'La premiazione è mercoledì, comunque.'),
  r('t035', 'FLESSIBILITA_ORARIA', 'realistica', 2, 'Il turno della moglie',
    'Mia moglie ha cambiato orario e adesso i nostri turni si accavallano. Se sposto il mio di due ore, qualcuno resta coi bambini.',
    'Due ore. Sposta.', 'L’orario è quello.', 'Vediamo. I bambini intanto ci sono.'),
  r('t036', 'LAVORO_DA_CASA', 'realistica', 2, 'Le traduzioni',
    'Tradurre le lettere dei fornitori del nord richiede silenzio e un dizionario. Il dizionario ce l’ho a casa, il silenzio pure.',
    'Silenzio e dizionario. Vai a casa.', 'Traduci qui.', 'Traduco qui, con fatica.'),
  r('t037', 'LAVORO_DA_CASA', 'sarcastica', 3, 'La prova dei tre giorni',
    'Propongo tre giorni da casa e poi guardiamo i numeri. Se rendo meno, torno e non ne parliamo più. Se rendo di più, ne riparliamo.',
    'Tre giorni e i numeri. Ci sta.', 'I numeri li facciamo qui.', 'La prova aspetta.'),
  r('t038', 'FERIE_LUNGHE', 'realistica', 2, 'Le due settimane d’estate',
    'Chiedo le due settimane di agosto, come tutti gli anni, ma stavolta lo chiedo a marzo perché l’anno scorso me le avete date spezzate all’ultimo.',
    'A marzo, e intere. Bene.', 'Vedremo ad agosto.', 'Ne riparliamo. Ad agosto, immagino.'),
  r('c032', 'FORMAZIONE', 'realistica', 2, 'La scuola serale di alchimia',
    'Tre sere a settimana per quattro mesi. La pago io, chiedo solo di uscire un’ora prima in quei giorni. Alla fine ho un attestato che vale anche per l’officina.',
    'La paghi tu, esci un’ora prima. Vai.', 'L’orario non si tocca.', 'La scuola comincia comunque.'),
  r('c033', 'PROMOZIONE', 'realistica', 3, 'Il secondo del reparto',
    'Quando il responsabile non c’è decido io, ma senza titolo nessuno mi ascolta davvero. O mi dai il ruolo, o dai a lui l’obbligo di esserci sempre.',
    'Il ruolo è tuo. Così si decide.', 'Continua a decidere senza titolo.', 'Il titolo aspetta, e nessuno ti ascolta.'),
  r('c034', 'CAMBIO_MANSIONE', 'realistica', 2, 'Voglio imparare i conti',
    'Faccio il lavoro di braccia da sei anni e vorrei passare ai registri. Non so farlo: chiedo di affiancare chi lo fa per due mesi, senza smettere il mio.',
    'Affianca, e poi vediamo. Bene.', 'Ognuno al suo mestiere.', 'Ci penso. Intanto continuo di braccia.'),
  r('c035', 'RICONOSCIMENTO', 'sarcastica', 2, 'Il muro dei ringraziamenti',
    'Ho notato che i clienti mandano lettere di ringraziamento e finiscono in un cassetto. Propongo di appenderle. Costa quattro chiodi e ci fa vedere che serviamo a qualcosa.',
    'Quattro chiodi. Appendiamole.', 'Restano nel cassetto.', 'Restano nel cassetto, per ora.'),
  r('p035', 'CONFLITTO_TRA_COLLEGHI', 'realistica', 2, 'La colpa girata',
    'Un lotto è andato male e la colpa è finita su di me davanti a tutti. Non era mia e chi l’ha detto lo sa. Non voglio punizioni, voglio che si corregga.',
    'Si corregge oggi, davanti a tutti.', 'Non entro nelle beghe.', 'La colpa resta dov’è, per ora.'),
  r('p036', 'LAMENTELA_SU_COLLEGA', 'realistica', 2, 'Fa il mio lavoro',
    'C’è chi rifà quello che ho già fatto perché non si fida. Perdiamo tempo in due e io perdo anche la voglia.',
    'Uno fa, l’altro si fida. Lo dico io.', 'Meglio due controlli che nessuno.', 'Continuiamo a rifarlo in due.'),
  r('p037', 'RICATTO_IMPLICITO', 'sarcastica', 3, 'La cortesia di avvisare',
    'Non è un ultimatum, è una cortesia: ti avviso che sto guardando altrove. Avrei potuto non dirtelo e sparire un lunedì.',
    'Grazie della cortesia. Restiamo.', 'Grazie dell’avviso. Buona fortuna.', 'Continuo a guardare altrove, intanto.'),
  r('p038', 'RICHIESTA_ASSURDA_BASSO_COSTO', 'demenziale', 2, 'La finestra sul cortile',
    'Vorrei che qualcuno lavasse il vetro della finestra. È l’unica che ho e da tre anni guardo fuori attraverso una specie di nebbia. Costa un secchio d’acqua.',
    'Un secchio d’acqua. Approvato.', 'La nebbia resta.', 'La nebbia resta, per ora.'),
  r('p039', 'RICHIESTA_ASSURDA_ALTO_COSTO', 'sarcastica', 4, 'La biblioteca del mestiere',
    'Vorrei che l’officina comprasse i trattati importanti di alchimia. Sono dodici volumi e costano come un mese di lavoro. Nessuno li leggerebbe, tranne me.',
    'Nessuno tranne te. Va bene lo stesso.', 'Dodici volumi per un lettore, no.', 'I dodici volumi restano dal libraio.'),
];
