/* Lotto 12 — l'ultima mano, per arrivare oltre i trecentocinquanta. */
import { r } from './schema.js';

export default [
  r('z001', 'STRUMENTO_ROTTO', 'realistica', 2, 'Il tavolo che balla',
    'Ha una gamba corta e sotto c’è una pila di fogli piegati. Quando qualcuno passa, il tavolo balla e quello che sta sopra si versa.',
    'Una gamba giusta. Non un capolavoro di ingegneria.', 'Aggiungi un foglio.', 'Aggiungo un foglio, per ora.'),
  r('z002', 'BENEFIT_MATERIALE_PICCOLO', 'realistica', 1, 'Uno straccio pulito',
    'Usiamo lo stesso da settimane e ormai sporca invece di pulire. Chiedo che ce ne sia una scorta, non uno.',
    'Una scorta di stracci. Fatto.', 'Lavatelo.', 'Lo laviamo ancora un po’.'),
  r('z003', 'BENEFIT_MATERIALE_GRANDE', 'realistica', 2, 'Una seconda porta',
    'Entra ed esce tutto dalla stessa porta: la merce, la gente, i clienti. Nelle ore di punta ci si scontra, e prima o poi ci si scontra con qualcosa di fragile in mano.',
    'Una seconda porta. Prima dello scontro.', 'Fate a turno.', 'Facciamo a turno, per ora.'),
  r('z004', 'AUMENTO_STIPENDIO', 'realistica', 1, 'La prima volta che chiedo',
    'Non ho mai chiesto niente e non so nemmeno come si fa. Vorrei una paga più giusta. Ecco, l’ho detto.',
    'L’hai detto bene. È giusta da oggi.', 'Hai fatto bene a chiedere. La risposta è no.', 'L’hai detto. Ci penso.'),
  r('z005', 'AUMENTO_MERITATO', 'realistica', 3, 'Il conto di quattro anni',
    'In quattro anni ho preso lo stesso, e in quattro anni ho imparato tre mestieri. Uno dei due numeri è sbagliato, e non è quello dei mestieri.',
    'Uno dei due numeri è sbagliato. Corretto.', 'Il numero è quello che possiamo permetterci.', 'I numeri restano lì.'),
  r('z006', 'ANTICIPO_STIPENDIO', 'realistica', 2, 'Il dente',
    'Ho un dente che va tolto e il cavadenti vuole essere pagato prima. Non è una cosa che si può rimandare, per quanto io ci abbia provato.',
    'Non si rimanda. Prendi.', 'Prova a rimandare ancora.', 'Rimando ancora un po’, allora.'),
  r('z007', 'RIMBORSO_DISCUTIBILE', 'sarcastica', 3, 'La trasferta lunga',
    'Sono stato tre giorni dal fornitore del nord. Le spese sono quelle di tre giorni, comprese due cene che definirei di rappresentanza.',
    'Definiamole di rappresentanza. Va bene.', 'Le cene le paghi tu.', 'Le cene sono già state mangiate, però.'),
  r('z008', 'PERMESSO_PERSONALE', 'realistica', 1, 'Il figlio da ritirare',
    'La scuola chiude prima per un giorno e non c’è nessuno che possa andare. Sono due ore, una volta sola, e lo so con due settimane di anticipo.',
    'Due ore con due settimane di anticipo. Perfetto.', 'Trova un’alternativa.', 'Cerco un’alternativa. Non credo ci sia.'),
  r('z009', 'FLESSIBILITA_ORARIA', 'realistica', 1, 'La pausa spostata',
    'Faccio la pausa quando la fanno tutti e la mensa è piena. Se la faccio mezz’ora dopo mangio in dieci minuti invece che in quaranta.',
    'Dieci minuti invece di quaranta. Sposta.', 'La pausa è quella comune.', 'Resto nella coda, allora.'),
  r('z010', 'LAVORO_DA_CASA', 'realistica', 2, 'Il giorno dei conti',
    'Il giorno in cui chiudo i registri devo contare senza essere interrotto. Qui vengo interrotto. È l’unica cosa che chiedo, un giorno al mese.',
    'Un giorno al mese senza interruzioni. Va bene.', 'Conta qui, come sempre.', 'Conto qui, con le interruzioni.'),
  r('z011', 'FERIE_LUNGHE', 'sarcastica', 3, 'Le ferie di cui nessuno parla',
    'In quarantotto anni di officina nessuno ha mai preso più di cinque giorni di fila. Vorrei essere il primo, e vorrei che non diventasse una leggenda.',
    'Sii il primo. E non diventerà una leggenda.', 'La tradizione dice cinque giorni.', 'La tradizione resiste, per ora.'),
  r('z012', 'FORMAZIONE', 'realistica', 2, 'Il libro che serve a tutti',
    'C’è un manuale nuovo sulle rese di distillazione. Costa poco, lo leggo io e poi lo lascio in officina. Non chiedo tempo, chiedo il libro.',
    'Non chiedi tempo, chiedi un libro. Sì.', 'Il libro no.', 'Il libro resta dal libraio.'),
  r('z013', 'PROMOZIONE', 'realistica', 2, 'Quello che faccio già',
    'Formo i nuovi, decido i turni, rispondo ai clienti quando manca qualcuno. Sono tre cose che non stanno nel mio ruolo, e le faccio da un anno.',
    'Tre cose fuori ruolo per un anno. Il ruolo cambia.', 'Continuerai a farle. Grazie.', 'Le farò ancora un po’, immagino.'),
  r('z014', 'PROMOZIONE_IMMERITATA', 'demenziale', 4, 'Il titolo di anziano',
    'Nella mia specie l’anzianità si misura diversamente, e in anni di scarabeo io sono praticamente il fondatore. Chiedo il rispetto che ne consegue, e un titolo.',
    'In anni di scarabeo. Va bene, praticamente fondatore.', 'Misuriamo gli anni come tutti.', 'Gli anni di scarabeo continuano a passare.'),
  r('z015', 'CAMBIO_MANSIONE', 'realistica', 2, 'Fuori dal magazzino',
    'Sto tutto il giorno al freddo e al buio e ho chiesto tre volte di essere spostato. Non ho fatto storie nessuna delle tre volte. È la quarta.',
    'La quarta è quella buona. Ti sposto.', 'Il magazzino ha bisogno di te.', 'Ci sarà una quinta, immagino.'),
  r('z016', 'RICONOSCIMENTO', 'realistica', 1, 'Ho tenuto io la baracca',
    'Nella settimana in cui eravate tutti alla fiera, qui dentro ho deciso io. Non è successo niente di male, e questo è esattamente il punto.',
    'Non è successo niente. È merito tuo.', 'Era il tuo lavoro.', 'Il merito resta lì, per ora.'),
  r('z017', 'CONFLITTO_TRA_COLLEGHI', 'realistica', 1, 'Il turno rubato',
    'Uno si prende sempre i turni migliori perché arriva prima al tabellone. Non è cattiveria, è che il tabellone funziona così. Cambiamo il tabellone.',
    'Cambiamo il tabellone. Non la persona.', 'Arriva prima anche tu.', 'Arriverò prima, immagino.'),
  r('z018', 'LAMENTELA_SU_COLLEGA', 'realistica', 1, 'Non risponde mai',
    'Gli scrivo e non risponde. Poi si lamenta di non essere stato informato. Ho tutte le note, ma non voglio arrivare a mostrarle.',
    'Non serve mostrarle. Gli parlo io.', 'Mostragliele.', 'Le tengo da parte, allora.'),
  r('z019', 'RICATTO_IMPLICITO', 'realistica', 3, 'Il mestiere ce l’ho io',
    'Sono l’unico che sa fare quella lavorazione. Non l’ho mai usato come argomento e non voglio cominciare adesso, ma è vero e va detto una volta.',
    'È vero, e adesso è stato detto. Ne teniamo conto.', 'Allora insegnala a qualcun altro.', 'L’ho detto. Adesso lo sappiamo in due.'),
  r('z020', 'RICHIESTA_ASSURDA_BASSO_COSTO', 'demenziale', 2, 'Il quaderno delle idee',
    'Vorrei un quaderno, uno vero, dove chiunque possa scrivere idee sciocche. Le idee sciocche a volte diventano buone, e comunque il quaderno costa due monete.',
    'Due monete di idee sciocche. Va bene.', 'Le idee si dicono a voce.', 'Il quaderno resta bianco.'),
  r('z021', 'RICHIESTA_ASSURDA_ALTO_COSTO', 'demenziale', 4, 'La statua del fondatore',
    'Il fondatore si è ritirato in campagna senza che nessuno gli dicesse grazie. Propongo una statua, piccola, nel cortile. Uno scultore costa, ma la riconoscenza non ha prezzo.',
    'La riconoscenza non ha prezzo. Lo scultore sì, ma va bene.', 'Gli manderemo una lettera.', 'La statua resta un’idea nel cortile.'),
  r('z022', 'SICUREZZA_SUL_LAVORO', 'realistica', 2, 'Nessuno sa curare un’ustione',
    'Qui ci si scotta, ed è normale. Quello che non è normale è che nessuno sappia cosa fare nei primi due minuti, che sono quelli che contano.',
    'I primi due minuti. Impariamoli tutti.', 'Chiameremo il guaritore.', 'Chiameremo qualcuno, quando succede.'),
  r('z023', 'PROPOSTA_TAGLIO_COSTI', 'realistica', 3, 'Il contratto dell’acqua',
    'Paghiamo l’acqua a forfait da dodici anni e ne usiamo molta meno di quella che paghiamo. Rinegoziare costa una lettera e due settimane di attesa.',
    'Una lettera e due settimane. Scriviamola.', 'Lasciamo com’è.', 'La lettera resta da scrivere.'),
  r('z024', 'PROPOSTA_INVESTIMENTO', 'realistica', 2, 'Le pentole di rame',
    'Le nostre sono di ferro e cedono sapore. Il rame costa il triplo e dura il triplo, ma il vero vantaggio è che il prodotto viene meglio e si vende meglio.',
    'Viene meglio e si vende meglio. Compriamo.', 'Il ferro va bene.', 'Il ferro resta, per ora.'),
  r('z025', 'PROPOSTA_RIORGANIZZAZIONE', 'realistica', 2, 'Chi risponde ai clienti',
    'Adesso risponde chi è più vicino alla porta. Il risultato è che a domande difficili rispondono le persone sbagliate, e a volte rispondono male.',
    'Uno solo risponde. Fine dell’improvvisazione.', 'Chi c’è, risponde.', 'Continua a rispondere chi capita.'),
  r('z026', 'PROPOSTA_OUTSOURCING', 'realistica', 2, 'La pulizia',
    'La facciamo a turno fra noi e ci portiamo via un’ora a testa a settimana. Una persona che venga la sera costa meno di quelle ore.',
    'Costa meno delle nostre ore. Va bene.', 'Continuiamo a turno.', 'Continuiamo a turno, per ora.'),
  r('z027', 'PROPOSTA_CONSULENZA', 'sarcastica', 4, 'Il valutatore d’azienda',
    'Uno che ci dica quanto valiamo, se un giorno volessimo vendere. Non stiamo vendendo, per carità. Ma saperlo è comunque un dato.',
    'Non stiamo vendendo, per carità. Ma sappiamolo.', 'Non ci serve saperlo.', 'Il valutatore aspetta.'),
  r('z028', 'PROPOSTA_ASSUNZIONE', 'sarcastica', 2, 'Il nipote di qualcuno',
    'Mi hanno segnalato un ragazzo volenteroso. È il nipote di un cliente importante. Volenteroso lo dico per sentito dire; nipote lo so per certo.',
    'Nipote per certo, volenteroso per sentito dire. Prendiamolo.', 'Non assumiamo per parentela.', 'Il nipote resta disoccupato, per ora.'),
  r('z029', 'PROPOSTA_AUMENTO_RITMI', 'realistica', 2, 'Il mese della commessa',
    'Per un mese serve un quinto in più di produzione, poi si torna normali. È scritto nel contratto che abbiamo firmato, e adesso va fatto.',
    'L’abbiamo firmato. Si fa.', 'Rinegoziamo la consegna.', 'Il contratto ha una data, però.'),
  r('z030', 'PROPOSTA_MARKETING', 'realistica', 2, 'Il listino stampato',
    'Non abbiamo un listino: diciamo i prezzi a voce e ognuno se li ricorda diversi. Stamparne cento copie costa poco e ci fa sembrare seri.',
    'Cento copie di serietà. Facciamole.', 'I prezzi si dicono a voce.', 'A voce ancora un po’.'),
];
