/* Lotto 02 — sicurezza e soldi: SICUREZZA_SUL_LAVORO, AUMENTO_STIPENDIO, AUMENTO_MERITATO. */
import { r } from './schema.js';

export default [
  r('s001', 'SICUREZZA_SUL_LAVORO', 'realistica', 1, 'Il pavimento davanti al forno',
    'È unto e nessuno lo lava perché non è compito di nessuno. Ci passiamo davanti venti volte al giorno con le mani piene. Prima o poi qualcuno cade, e cade con qualcosa in mano. Basta che lavarlo diventi il compito di qualcuno: lo metti a ruolo?',
    'Bene. Che sia compito di qualcuno, allora.', 'Va bene. Staremo attenti, come sempre.', 'Stiamo attenti ancora un po’.'),
  r('s002', 'SICUREZZA_SUL_LAVORO', 'realistica', 1, 'Le maschere sono finite',
    'Lavoriamo con i vapori di zolfo senza. Per un giorno non succede niente, per un mese non lo so, e nessuno di noi vuole scoprirlo. Ordino una cassa di maschere nuove?',
    'Grazie. Le ordiniamo oggi.', 'Continuiamo senza. Speriamo bene.', 'Senza, ancora un po’. Speriamo.'),
  r('s003', 'SICUREZZA_SUL_LAVORO', 'realistica', 2, 'La scala del magazzino',
    'Il terzo gradino si muove. L’ho segnato col gesso e tutti lo saltano, ma il gesso si consuma e i nuovi non lo sanno. Il gradino si sistema in un’ora: la faccio riparare?',
    'Bene. Prima che il gesso sparisca.', 'Rifaccio il segno col gesso, allora.', 'Rifaccio il gesso intanto.'),
  r('s004', 'SICUREZZA_SUL_LAVORO', 'realistica', 2, 'Gli acidi stanno in alto',
    'Le damigiane di acido stanno sul ripiano più alto e per prenderle bisogna salire con le braccia tese. Se una scivola, scivola sopra la testa di chi sale. Basterebbe spostarle sul ripiano basso: do l’ordine?',
    'Giusto. Le spostiamo in basso.', 'Restano in alto. Saliremo piano.', 'Saliamo piano intanto.'),
  r('s005', 'SICUREZZA_SUL_LAVORO', 'sarcastica', 2, 'L’estintore magico',
    'Ne abbiamo uno, scade da nove anni, e c’è scritto sopra "in caso di incendio agitare". Ho provato ad agitarlo: fa rumore. Non credo che il rumore spenga il fuoco.',
    'Ne prendiamo uno che spenga il fuoco. Buona idea.', 'Terremo quello che fa rumore.', 'Il rumore ci farà compagnia ancora un po’.'),
  r('s006', 'SICUREZZA_SUL_LAVORO', 'realistica', 1, 'Nessuno sa cosa fare se brucia',
    'Non c’è un’uscita segnata, non c’è un punto di ritrovo, e metà di noi non sa dove sta la seconda porta. Serve un pomeriggio, una volta.',
    'Un pomeriggio. Bene.', 'Ce la caveremo. Immagino.', 'Ce la caveremo ancora un po’.'),
  r('s007', 'SICUREZZA_SUL_LAVORO', 'demenziale', 2, 'Il gatto del magazzino',
    'Non è un gatto. Ha sei zampe e mangia i topi, quindi lo teniamo, ma da quando ha imparato ad aprire le casse c’è il rischio che apra quella sbagliata. Serve un lucchetto.',
    'Un lucchetto contro il gatto a sei zampe. Va bene.', 'Niente lucchetto. Auguri a tutti.', 'Il gatto attende il lucchetto.'),
  r('s008', 'SICUREZZA_SUL_LAVORO', 'realistica', 3, 'I turni di notte da soli',
    'Chi fa la notte è solo nell’edificio. Se gli succede qualcosa nessuno se ne accorge fino alla mattina. Basterebbe essere in due, o una campana che si sente dalla strada.',
    'Una campana costa poco. Facciamola.', 'Continuiamo da soli, allora.', 'Da soli ancora un po’.'),
  r('s009', 'SICUREZZA_SUL_LAVORO', 'realistica', 2, 'I vapori del banco sette',
    'Da quando abbiamo cambiato fornitore di solvente, chi sta al sette esce con la voce roca. Non è successo niente di grave. "Ancora" è la parola che mi preoccupa.',
    'Cambiamo solvente. Grazie di averlo detto.', 'Continuiamo con questo. Vedremo.', 'Vediamo ancora un po’.'),
  r('s010', 'SICUREZZA_SUL_LAVORO', 'sarcastica', 3, 'Il tetto sopra il banco tre',
    'Gocciola. Sotto il gocciolio abbiamo messo un secchio. Sopra il secchio c’è il banco dove si lavora con le polveri che non devono bagnarsi. Il secchio è la nostra unica difesa.',
    'Ripariamo il tetto. Il secchio andrà in pensione.', 'Il secchio resta in servizio.', 'Il secchio continua a lavorare.'),

  r('s011', 'AUMENTO_STIPENDIO', 'realistica', 1, 'Un ritocco',
    'Non chiedo il doppio. Chiedo quello che prende chi fa il mio stesso lavoro dall’altra parte della strada, che è un quinto in più. Lo so perché me l’hanno detto loro.',
    'Bene. Almeno smetto di fare i conti alla sera.', 'Va bene. Continuerò a fare i conti.', 'Continuo a fare i conti intanto.'),
  r('s012', 'AUMENTO_STIPENDIO', 'realistica', 2, 'È cambiato il costo del pane',
    'Prendo quello che prendevo tre anni fa e il pane costa un terzo in più. Non è che voglio guadagnare di più: è che guadagno di meno senza aver cambiato niente.',
    'Giusto. Il conto lo fa il fornaio, mica tu.', 'Capisco. Comprerò meno pane.', 'Il fornaio non rimanda, però.'),
  r('s013', 'AUMENTO_STIPENDIO', 'sarcastica', 2, 'Ho fatto un progetto',
    'Ho gestito il riordino delle scorte del secondo trimestre. Era un elenco, sì, ma era un elenco lungo. Direi che vale un riconoscimento economico.',
    'Un elenco lungo. Va bene.', 'L’elenco resterà un elenco, allora.', 'L’elenco aspetta insieme a me.'),
  r('s014', 'AUMENTO_STIPENDIO', 'realistica', 2, 'Faccio due mestieri',
    'Da quando è andato via quello dell’imballaggio faccio anche il suo. Non me ne lamento: mi lamento del fatto che prendo per uno.',
    'Due mestieri, due paghe. Ci sta.', 'Continuo a farne due per uno.', 'Ne faccio due per uno ancora un po’.'),
  r('s015', 'AUMENTO_STIPENDIO', 'demenziale', 3, 'Il badge dorato',
    'Sono qui da otto mesi, che in anni di scarabeo sono parecchi. Nella Gilda si usa dare un distintivo d’oro per l’anzianità, e otto mesi di me valgono un anno di chiunque.',
    'Un distintivo d’oro. Otto mesi. Va bene.', 'Niente distintivo. Torno al lavoro.', 'Il distintivo aspetta con me.'),
  r('s016', 'AUMENTO_STIPENDIO', 'realistica', 3, 'La proposta di fuori',
    'Mi hanno offerto un quarto in più. Non voglio andarmene: qui mi trovo bene e il lavoro mi piace. Ma un quarto in più è un quarto in più, e devo dirlo a qualcuno.',
    'Restare conviene a tutti e due. Bene.', 'Allora devo pensarci sul serio.', 'Ci penso mentre aspetto.'),
  r('s017', 'AUMENTO_STIPENDIO', 'realistica', 2, 'Sono passati due anni',
    'Due anni esatti dall’ultima volta che si è parlato della mia paga. Non chiedo una cifra, chiedo che se ne parli. È diverso.',
    'Parliamone. E poi diciamolo con dei numeri.', 'Ne riparliamo tra due anni, allora.', 'Ne riparleremo, immagino.'),
  r('s018', 'AUMENTO_STIPENDIO', 'sarcastica', 3, 'Il mercato è cambiato',
    'Ho fatto un’indagine di mercato sui compensi del settore. Il campione è di due persone e le conosco tutte e due, ma il risultato è chiaro: sono sottopagato.',
    'Un campione di due. Ma il punto resta.', 'Amplia il campione e ne riparliamo.', 'Amplio il campione nel frattempo.'),
  r('s019', 'AUMENTO_STIPENDIO', 'realistica', 1, 'Il turno di notte vale di più',
    'Faccio la notte da sette mesi e prendo come chi fa il giorno. In tutte le officine del regno la notte si paga di più. Qui no, e nessuno mi ha mai spiegato perché.',
    'Perché nessuno ci aveva pensato. Adesso sì.', 'Va bene. Continuo a fare la notte come il giorno.', 'La notte continua a valere come il giorno.'),
  r('s020', 'AUMENTO_STIPENDIO', 'demenziale', 4, 'La partecipazione agli utili',
    'Ho pensato a una cosa: siccome le pozioni le faccio io, e siccome i soldi vengono dalle pozioni, una piccola quota su ogni fiala venduta sarebbe soltanto matematica.',
    'Matematica. Va bene, vediamo dove ci porta.', 'La matematica dice che la fabbrica non è tua.', 'La matematica aspetta.'),

  r('s021', 'AUMENTO_MERITATO', 'realistica', 1, 'Tre anni allo stesso prezzo',
    'Da quando sono entrato la produzione del mio reparto è cresciuta di un terzo, e sono lo stesso io a farla. La mia paga invece è quella del primo giorno.',
    'Hai ragione, e mi vergogno che l’abbia dovuto dire tu.', 'Va bene. Sarà il quarto anno uguale.', 'Il quarto anno uguale, allora.'),
  r('s022', 'AUMENTO_MERITATO', 'realistica', 2, 'Prendo meno di chi ho formato',
    'Ho insegnato il mestiere a due persone. Adesso prendono più di me perché sono entrate dopo, quando gli stipendi erano già più alti. Non ce l’ho con loro.',
    'È una storpiatura e la sistemiamo. Grazie.', 'Allora continuerò a formare gente che mi supera.', 'Continuo a formarli intanto.'),
  r('s023', 'AUMENTO_MERITATO', 'realistica', 2, 'Non sbaglio mai',
    'Non è vanto: è che il mio lavoro si vede solo quando va storto, e non va mai storto. Da quattro anni. Vorrei che valesse qualcosa, prima che valga soltanto quando smetto.',
    'Vale. E adesso si vede anche sulla paga.', 'Continuerò a non sbagliare, gratis.', 'Non sbaglio ancora un po’, gratis.'),
  r('s024', 'AUMENTO_MERITATO', 'realistica', 1, 'La differenza col banco accanto',
    'Faccio lo stesso lavoro di chi sta al banco accanto, con le stesse ore e la stessa resa, e prendo un sesto in meno. È l’unica cosa che vorrei capire.',
    'Non c’è niente da capire: è uno sbaglio. Corretto.', 'Allora resta una differenza che non si spiega.', 'La differenza resta lì, per ora.'),
  r('s025', 'AUMENTO_MERITATO', 'realistica', 3, 'Il reparto lo tengo su io',
    'Se domani non vengo, il reparto si ferma. Lo dico senza minacciare: lo dico perché è vero, e perché una cosa vera dovrebbe pesare quando si parla di soldi.',
    'È vero, e adesso pesa. Bene.', 'Allora è vero e non pesa. Ho capito.', 'Vero e in attesa. Ho capito.'),
  r('s026', 'AUMENTO_MERITATO', 'sarcastica', 2, 'La promozione senza aumento',
    'L’anno scorso mi avete dato un titolo nuovo. Sono grato: il titolo è bello. Purtroppo il fornaio non accetta titoli.',
    'Il fornaio ha ragione. Ci mettiamo anche i soldi.', 'Terrò il titolo. Bello, comunque.', 'Il titolo aspetta con me.'),
  r('s027', 'AUMENTO_MERITATO', 'realistica', 2, 'Il conto degli straordinari',
    'Ho contato le ore in più dell’ultimo anno: sono sei settimane di lavoro. Non le ho mai messe a nota perché mi sembrava piccolo, una alla volta.',
    'Sei settimane. Le mettiamo a posto.', 'Allora restano sei settimane regalate.', 'Restano lì, in attesa.'),
  r('s028', 'AUMENTO_MERITATO', 'realistica', 3, 'Ho rinunciato due volte',
    'Le altre due volte che ho chiesto avete detto che non era il momento. Ho accettato, e ho aspettato. Adesso vorrei sapere quando è il momento, o se non lo è mai.',
    'È adesso. Avevi ragione tutte e tre le volte.', 'Allora non è mai il momento. Almeno lo so.', 'Un’altra attesa. Comincio a capire.'),
  r('s029', 'AUMENTO_MERITATO', 'realistica', 1, 'Il cliente ha chiesto di me',
    'Quello della capitale ha rinnovato la commessa a una condizione: che la faccia io. L’avete letto anche voi nella lettera. Vorrei che si vedesse in busta.',
    'Se ti chiedono per nome, vali di più. Fatto.', 'Allora mi chiederanno per nome e basta.', 'Mi chiedono per nome, intanto.'),
  r('s030', 'AUMENTO_MERITATO', 'realistica', 2, 'Non ho mai chiesto niente',
    'In cinque anni non ho chiesto un permesso, un anticipo, un giorno. Non lo dico per farne una virtù. Lo dico perché è l’unica cosa che ho da mettere sul tavolo.',
    'È abbastanza. Anzi, è troppo aver aspettato.', 'Va bene. Continuerò a non chiedere niente.', 'Continuo a non chiedere, allora.'),
];
