/* Lotto 08 — il rinforzo agli archetipi che escono piu' spesso, e le voci di riserva.
   Le voci `riserva-*` sono l'ultima rete: se il filtro non trova candidati validi il
   gioco pesca da qui invece di restare senza contenuto. Sono scritte apposta senza
   riferimenti a mestieri o situazioni particolari, cosi' stanno bene in bocca a
   chiunque e in qualunque momento della partita. */
import { r } from './schema.js';

export default [
  r('m031', 'STRUMENTO_ROTTO', 'realistica', 2, 'Il registro si sta sfasciando',
    'La rilegatura ha ceduto e le pagine escono. Ne ho già perse due e non so quali. Rilegarlo costa poco; ricostruire i conti persi costa parecchio.',
    'Rileghiamolo, prima di perdere il resto.', 'Terrò insieme le pagine con lo spago.', 'Lo spago regge ancora un po’.'),
  r('m032', 'STRUMENTO_ROTTO', 'realistica', 1, 'Il filtro è intasato',
    'Passa metà del liquido di prima e l’altra metà resta sopra a decantare da sola. Pulirlo o cambiarlo: l’una o l’altra, ma qualcosa va fatto.',
    'Cambiamolo. Meglio subito.', 'Aspetterò che passi da solo.', 'Decanta ancora un po’.'),
  r('m033', 'BENEFIT_MATERIALE_PICCOLO', 'realistica', 1, 'Un imbuto in più',
    'Ne abbiamo due per sei persone e mezza giornata la passiamo a passarceli. Costano meno di una fiala e ce ne servono altri quattro.',
    'Quattro imbuti. Fatto.', 'Continuate a passarveli.', 'Ce li passiamo ancora un po’.'),
  r('m034', 'BENEFIT_MATERIALE_PICCOLO', 'sarcastica', 2, 'Un orologio in officina',
    'Non ce n’è nessuno. Sappiamo che ora è chiedendo a chi passa dalla strada. È un sistema che funziona, ma non benissimo.',
    'Un orologio. Sembrava impossibile.', 'Chiedete a chi passa. Funziona.', 'Chi passa continuerà a dircelo.'),
  r('m035', 'BENEFIT_MATERIALE_GRANDE', 'realistica', 3, 'Il pavimento nuovo',
    'Quello di adesso è pietra crepata e le crepe trattengono i residui. Ogni ispezione ce lo dicono e ogni volta rispondiamo che lo faremo.',
    'Facciamolo davvero, per una volta.', 'Continueremo a dire che lo faremo.', 'Lo diremo ancora, immagino.'),
  r('s031', 'AUMENTO_STIPENDIO', 'realistica', 2, 'La cifra esatta',
    'Ho scritto su un foglio la cifra che mi serve per non fare più i conti la sera. È più bassa di quella che vi aspettate, e non la cambio.',
    'È più bassa di quella che mi aspettavo. Va bene.', 'Anche quella cifra è troppo, adesso.', 'Il foglio resta sul tavolo.'),
  r('s032', 'AUMENTO_MERITATO', 'realistica', 2, 'La differenza col nuovo',
    'È arrivato uno che fa metà del mio lavoro e prende più di me perché ha contrattato all’ingresso. Io non ho contrattato: mi fidavo.',
    'Ti fidavi, e avevi ragione. Sistemato.', 'Chi contratta ottiene. È così ovunque.', 'La differenza resta lì, per adesso.'),
  r('t031', 'PERMESSO_PERSONALE', 'realistica', 1, 'Un’ora per la posta',
    'Devo ritirare un documento all’ufficio del regno e chiudono quando chiudiamo noi. Un’ora, e non c’è modo di farlo in altro momento.',
    'Un’ora. Vai.', 'Manda qualcuno per te.', 'L’ufficio chiude comunque all’ora sua.'),
  r('t032', 'FLESSIBILITA_ORARIA', 'realistica', 1, 'Mezz’ora prima',
    'Se entro mezz’ora prima prendo il carro dei corrieri invece di camminare, e alla sera arrivo a casa un’ora prima. Faccio le stesse ore, semplicemente spostate.',
    'Stesse ore. Sposta pure.', 'L’orario è quello di tutti.', 'L’orario resta quello, per ora.'),
  r('c030', 'FORMAZIONE', 'realistica', 2, 'Imparare la lingua del nord',
    'Metà dei nostri fornitori parla quella lingua e trattiamo tramite un interprete che paghiamo a giornata. In sei mesi la imparo e l’interprete non serve più.',
    'Sei mesi e via l’interprete. Buon affare.', 'Continuiamo con l’interprete.', 'L’interprete resta a giornata.'),
  r('c031', 'RICONOSCIMENTO', 'realistica', 1, 'Non mi avete mai chiesto niente',
    'In tre anni nessuno mi ha chiesto come va il lavoro, se ho bisogno di qualcosa, se cambierei qualcosa. Non chiedo un premio. Chiedo dieci minuti.',
    'Dieci minuti adesso. E poi ogni mese.', 'Il lavoro va, si vede.', 'Dieci minuti, prima o poi.'),
  r('p033', 'CONFLITTO_TRA_COLLEGHI', 'realistica', 2, 'Il posto assegnato',
    'Due di noi vogliono lo stesso banco, quello vicino alla finestra. Se ne parla da mesi e adesso non se ne parla più: si sposta la roba dell’altro quando l’altro non c’è.',
    'Assegno io il banco. Fine della storia.', 'Se la vedano loro.', 'La roba continuerà a spostarsi.'),
  r('p034', 'LAMENTELA_SU_COLLEGA', 'realistica', 1, 'Prende le cose e non le rimette',
    'Gli strumenti comuni finiscono nel suo cassetto e ci restano. Ogni mattina faccio il giro dei cassetti prima di cominciare.',
    'Gli strumenti tornano al loro posto. Lo dico io.', 'Continua il giro dei cassetti.', 'Il giro dei cassetti continua.'),

  /* ── Le voci di riserva: buone per chiunque, in qualunque momento ── */
  r('riserva-01', 'BENEFIT_MATERIALE_PICCOLO', 'realistica', 1, 'Una cosa piccola',
    'È una richiesta piccola e mi vergogno quasi a farla. Ma sono di quelle che se non le chiedi non arrivano mai, e sono tre anni che non la chiedo.',
    'Le cose piccole contano. Fatto.', 'Le cose piccole aspettano.', 'Aspetta ancora un po’, allora.'),
  r('riserva-02', 'AUMENTO_STIPENDIO', 'realistica', 1, 'Vorrei parlare di soldi',
    'Non ho un discorso preparato e non voglio farne una questione. Vorrei solo che si parlasse della mia paga, e che dopo ci fosse una risposta.',
    'Parliamone. E la risposta è sì.', 'Ne abbiamo parlato. La risposta è no.', 'Ne parleremo. Prometto.'),
  r('riserva-03', 'PERMESSO_PERSONALE', 'realistica', 1, 'Mi serve del tempo',
    'Ho una cosa da sbrigare che non riguarda il lavoro e che non posso spostare. Non voglio raccontarla, e spero che vada bene lo stesso.',
    'Non serve raccontarla. Vai.', 'Senza sapere cosa, non posso.', 'Ci penso. La cosa però ha una data.'),
  r('riserva-04', 'RICONOSCIMENTO', 'realistica', 1, 'Volevo solo dirlo',
    'Ho finito un lavoro difficile e non l’ha notato nessuno. Non chiedo niente. Volevo solo che qualcuno lo sapesse, e voi siete qualcuno.',
    'Adesso lo so. E lo sapranno anche gli altri.', 'Bene. Al prossimo lavoro.', 'Lo saprò meglio più avanti.'),
  r('riserva-05', 'STRUMENTO_ROTTO', 'realistica', 1, 'Qualcosa non funziona',
    'C’è un attrezzo che non fa più il suo mestiere. Funziona a metà, e a metà vuol dire che ogni volta ci metto il doppio senza che si veda.',
    'Sistemiamolo. Il doppio del tempo si vede eccome.', 'Vai avanti col doppio, allora.', 'Col doppio ancora un po’.'),
  r('riserva-06', 'CONFLITTO_TRA_COLLEGHI', 'realistica', 1, 'C’è aria pesante',
    'Nel reparto è successa una cosa fra due persone e adesso non si parlano. Il lavoro passa da tutti e due, quindi il lavoro ne risente. Non è compito mio sistemarla.',
    'Non è compito tuo. Me ne occupo io.', 'Che se la sbrighino fra loro.', 'Se la sbrighino. Per ora.'),
  r('riserva-07', 'FLESSIBILITA_ORARIA', 'realistica', 1, 'Uno spostamento di orario',
    'Le stesse ore, in un momento diverso della giornata. Non cambia niente per il lavoro e cambia molto per me.',
    'Non cambia niente per il lavoro. Vai.', 'L’orario resta quello.', 'L’orario resta, per ora.'),
  r('riserva-08', 'PROPOSTA_TAGLIO_COSTI', 'realistica', 1, 'Una voce di spesa',
    'C’è una voce di spesa che si può ridurre senza toccare la produzione. Non è grande, ma è tutti i mesi, e tutti i mesi fanno un anno.',
    'Tutti i mesi fanno un anno. Tagliamo.', 'Lasciamola dov’è.', 'Ci penso. La voce resta.'),
  r('riserva-09', 'PROPOSTA_INVESTIMENTO', 'realistica', 1, 'Una spesa che rende',
    'C’è una cosa da comprare che si ripaga da sola, se le cose restano come sono. Il rischio è tutto lì: se le cose non restano come sono.',
    'Se le cose restano come sono. Rischiamo.', 'Troppo rischio adesso.', 'Ci penso. Il prezzo può cambiare.'),
  r('riserva-10', 'RICHIESTA_ASSURDA_BASSO_COSTO', 'demenziale', 2, 'Una cosa che non serve a niente',
    'So che non serve a niente. Lo so io e lo sapete voi. Ma costa pochissimo, e ogni tanto una cosa che non serve a niente tiene su il morale più di una che serve.',
    'Non serve a niente. Facciamola.', 'Se non serve a niente, no.', 'La cosa inutile aspetta.'),
];
