/* Lotto 05 — crescita e riconoscimento: FORMAZIONE, PROMOZIONE, PROMOZIONE_IMMERITATA,
   CAMBIO_MANSIONE, RICONOSCIMENTO. */
import { r } from './schema.js';

export default [
  r('c001', 'FORMAZIONE', 'realistica', 1, 'Il corso di distillazione a freddo',
    'Lo tiene un maestro della capitale, dura sei giorni. È la tecnica che useranno tutti fra due anni e qui non la sa fare nessuno.',
    'Vai. Meglio impararla prima degli altri.', 'La impareremo quando la sapranno tutti.', 'La impareremo più avanti, forse.'),
  r('c002', 'FORMAZIONE', 'realistica', 1, 'Imparare a leggere i conti',
    'Non so leggere un registro e me ne accorgo ogni volta che devo firmarne uno. Ci sono lezioni serali due volte a settimana.',
    'Bene. Chi firma deve capire cosa firma.', 'Continuerai a firmare senza leggere.', 'Firmo senza leggere ancora un po’.'),
  r('c003', 'FORMAZIONE', 'sarcastica', 2, 'Il seminario sulle sinergie',
    'Due giorni sulle sinergie di reparto. Non ho capito bene cosa siano le sinergie, ed è esattamente per questo che vorrei andarci.',
    'Vacci e poi spiegamele.', 'Le sinergie resteranno un mistero.', 'Il mistero resta, per ora.'),
  r('c004', 'FORMAZIONE', 'realistica', 2, 'Il corso di sicurezza',
    'La Gilda tiene un corso su come si maneggiano gli acidi. Dura un giorno e alla fine danno un attestato che gli ispettori chiedono sempre.',
    'Un giorno e un attestato. Facile.', 'Ce la caveremo senza attestato.', 'Senza attestato ancora un po’.'),
  r('c005', 'FORMAZIONE', 'realistica', 2, 'Insegnare agli altri',
    'Vorrei prendermi due pomeriggi per insegnare quello che so a chi è arrivato dopo. Perdiamo quattro ore adesso e ne guadagniamo molte dopo.',
    'Quattro ore ben spese. Fallo.', 'Ognuno impari per conto suo.', 'Impareranno da soli, per ora.'),
  r('c006', 'FORMAZIONE', 'demenziale', 3, 'Il corso di comunicazione empatica',
    'Insegna a dire "no" in modo che sembri "sì". Costa parecchio ma immagino che in un posto come questo possa tornare utile a più di una persona.',
    'Utile a più di una persona, hai ragione.', 'No. Detto in modo che sembri no.', 'Ci penso, in modo empatico.'),
  r('c007', 'FORMAZIONE', 'realistica', 3, 'Il maestro erborista',
    'C’è un vecchio che conosce le radici come nessuno. Prende un allievo all’anno, per tre mesi. Se ci vado torno con una competenza che qui non ha nessuno.',
    'Tre mesi per una cosa che non ha nessuno. Vai.', 'Prenderà un altro allievo, allora.', 'Prenderà qualcun altro, temo.'),
  r('c008', 'FORMAZIONE', 'realistica', 1, 'Le lezioni di scrittura',
    'Scrivo male e le mie relazioni le deve riscrivere qualcun altro. Sono due mesi di lezioni serali e le pago a metà io.',
    'A metà per uno. Giusto.', 'Continuerà a riscriverle qualcun altro.', 'Le riscrive qualcun altro, intanto.'),

  r('c009', 'PROMOZIONE', 'realistica', 2, 'Il capo del reparto non c’è più',
    'Da quattro mesi faccio io quello che faceva lui: i turni, gli ordini, le rogne. Non ho il titolo e non ho la paga. Ho solo le rogne.',
    'Titolo e paga. Le rogne le avevi già.', 'Continuerai con le rogne, allora.', 'Le rogne restano mie, intanto.'),
  r('c010', 'PROMOZIONE', 'realistica', 2, 'Sono pronto',
    'Ho imparato tutto quello che c’era da imparare in questo posto. O mi date qualcosa di più difficile, o comincio ad annoiarmi, e annoiato lavoro peggio.',
    'Qualcosa di più difficile, allora.', 'Continua con quello che sai fare.', 'Ci penso. Intanto mi annoio.'),
  r('c011', 'PROMOZIONE', 'realistica', 3, 'Il posto di responsabile',
    'So che state cercando qualcuno per il reparto. Vorrei essere considerato, e vorrei una risposta anche se è no, invece di scoprirlo quando arriva un altro.',
    'Sei considerato. E il posto è tuo.', 'Sarà un altro. Almeno te lo dico in faccia.', 'La risposta arriva più avanti.'),
  r('c012', 'PROMOZIONE', 'sarcastica', 3, 'La scala di carriera',
    'Sono al primo gradino da quattro anni. Ho guardato la scala e sopra di me non c’è nessuno: è una scala con un gradino solo. Vorrei che ne aggiungessimo un secondo.',
    'Aggiungiamo un gradino. Hai ragione.', 'La scala resta di un gradino.', 'La scala aspetta di crescere.'),
  r('c013', 'PROMOZIONE', 'realistica', 2, 'Ho formato tre persone',
    'Tre persone che adesso lavorano da sole. Nessuna di loro ha sbagliato niente di grave. Se so insegnare, forse so anche guidare.',
    'Chi sa insegnare sa guidare. Proviamo.', 'Insegnare e guidare sono cose diverse.', 'Ne riparliamo, e intanto insegno.'),

  r('c014', 'PROMOZIONE_IMMERITATA', 'sarcastica', 2, 'Il coordinamento',
    'Ho notato che manca una figura di coordinamento fra i reparti. Ci ho pensato molto e credo di essere la persona adatta. Il titolo potrebbe essere Coordinatore.',
    'Coordinatore. Speriamo che coordini.', 'La figura mancante resterà mancante.', 'La figura aspetta di esistere.'),
  r('c015', 'PROMOZIONE_IMMERITATA', 'sarcastica', 3, 'Ho un’idea di me stesso',
    'Non è che io faccia più degli altri. È che vedo le cose dall’alto, per carattere, e chi vede dall’alto dovrebbe stare in alto anche sull’organigramma.',
    'Dall’alto, allora. Vediamo cosa vedi.', 'Continua a vedere dall’alto da dove sei.', 'Vedo dall’alto, in attesa.'),
  r('c016', 'PROMOZIONE_IMMERITATA', 'demenziale', 3, 'Il vice di me stesso',
    'Il mio lavoro è cresciuto e mi servirebbe un vice. Il vice sarei sempre io, con un titolo diverso per la parte più importante. Sono due ruoli, quindi due paghe.',
    'Due ruoli, due paghe, una persona. Va bene.', 'Un ruolo, una paga, una persona.', 'Il vice attende la nomina.'),
  r('c017', 'PROMOZIONE_IMMERITATA', 'sarcastica', 2, 'Sono qui da più tempo',
    'Non dico di essere il migliore. Dico che sono qui da più tempo di quello che avete promosso l’anno scorso, e da qualche parte l’anzianità dovrà pur contare.',
    'Conta. Ma non è l’unica cosa che conta.', 'L’anzianità conta poco, in effetti.', 'L’anzianità aspetta di contare.'),
  r('c018', 'PROMOZIONE_IMMERITATA', 'demenziale', 4, 'Il consiglio ristretto',
    'Propongo di creare un consiglio ristretto per le decisioni importanti. Composto da voi e da me. Non serve dirlo agli altri, altrimenti non è ristretto.',
    'Un consiglio di due. Va bene, per ora.', 'Il consiglio ristretto resta di uno.', 'Il consiglio è convocato, prima o poi.'),

  r('c019', 'CAMBIO_MANSIONE', 'realistica', 1, 'Vorrei stare al banco',
    'Sto in magazzino ma quello che mi piace è distillare. L’ho imparato guardando. Datemi un mese di prova e se non funziona torno a spostare casse.',
    'Un mese di prova. Ci sta.', 'Le casse ti aspettano.', 'Le casse aspettano ancora.'),
  r('c020', 'CAMBIO_MANSIONE', 'realistica', 2, 'Non sono fatto per la gente',
    'Mi hanno messo a ricevere i clienti e ogni giorno mi costa fatica. Sono bravo con le cose, non con le persone. C’è un posto libero al confezionamento.',
    'Meglio dove sei bravo. Cambiamo.', 'Resta dove sei. Impararai.', 'Resta lì per ora, e vediamo.'),
  r('c021', 'CAMBIO_MANSIONE', 'realistica', 2, 'Il turno di notte mi sta uccidendo',
    'Faccio la notte da un anno e non dormo più nemmeno di giorno. Non chiedo di lavorare meno: chiedo di lavorare quando è chiaro.',
    'Passi al giorno. Dormi.', 'Serve qualcuno di notte, e sei tu.', 'La notte resta tua, per ora.'),
  r('c022', 'CAMBIO_MANSIONE', 'sarcastica', 2, 'Lo scambio',
    'Io voglio andare in magazzino, quello del magazzino vuole venire qui. Ci siamo già messi d’accordo. Manca solo che qualcuno dica di sì.',
    'Vi siete già messi d’accordo. Sì.', 'Non funziona così. Ognuno al suo posto.', 'Vi siete accordati per niente, per ora.'),
  r('c023', 'CAMBIO_MANSIONE', 'realistica', 1, 'La schiena',
    'Carico casse da sei anni e la schiena ha smesso di reggere. C’è del lavoro seduto che nessuno vuole fare e che io farei volentieri.',
    'Meglio te seduto che tu a casa. Cambiamo.', 'Continua a caricare, con giudizio.', 'Carico ancora un po’, con giudizio.'),

  r('c024', 'RICONOSCIMENTO', 'realistica', 1, 'Nessuno ha detto niente',
    'La commessa della capitale l’abbiamo consegnata in tempo e senza un errore. Ci sono volute tre settimane di corsa. Nessuno ha detto niente a nessuno.',
    'Hai ragione. Lo dico adesso, e lo dico a tutti.', 'Il lavoro fatto bene è il lavoro fatto.', 'Lo dirò. Prima o poi.'),
  r('c025', 'RICONOSCIMENTO', 'realistica', 2, 'Il mio nome sull’etichetta',
    'Le pozioni migliori le faccio io e sull’etichetta c’è solo il nome dell’officina. Non chiedo soldi: chiedo che ci sia scritto chi l’ha fatta.',
    'Ci mettiamo il nome. È giusto.', 'L’etichetta resta quella dell’officina.', 'L’etichetta resta così, per ora.'),
  r('c026', 'RICONOSCIMENTO', 'sarcastica', 2, 'La lettera di merito',
    'Nella Gilda si usa dare una lettera di merito a chi ha fatto qualcosa di notevole. Costa carta e inchiostro. Mi rendo conto che la carta qui è preziosa.',
    'Carta e inchiostro li troviamo.', 'La carta serve per altro.', 'La carta aspetta di essere trovata.'),
  r('c027', 'RICONOSCIMENTO', 'realistica', 2, 'Un grazie davanti agli altri',
    'Non voglio niente di materiale. Vorrei che quello che ho fatto lo sapessero anche gli altri, perché adesso lo sa solo chi era lì.',
    'Lo dirò davanti a tutti. Domani.', 'Lo sanno quelli che c’erano. Basta.', 'Lo dirò, quando capita.'),
  r('c028', 'RICONOSCIMENTO', 'demenziale', 3, 'La targa',
    'Una targa di ottone col mio nome, all’ingresso del reparto. Piccola. Non deve costare: deve solo esserci quando entra qualcuno.',
    'Una targa piccola. Va bene.', 'Niente targa. Sei nel reparto, si vede.', 'La targa resta un’idea.'),
  r('c029', 'RICONOSCIMENTO', 'realistica', 1, 'Il cliente ha scritto una lettera',
    'Ha scritto per ringraziare del lavoro e ha fatto il mio nome. La lettera è arrivata a voi. Vorrei solo sapere che l’avete letta.',
    'L’ho letta. E adesso la leggono tutti.', 'L’ho letta. Bene così.', 'La leggerò con calma.'),
];
