/* Lotto 01 — cose che si rompono, cose che servono, cose che costano.
   Materiale: STRUMENTO_ROTTO, BENEFIT_MATERIALE_PICCOLO, BENEFIT_MATERIALE_GRANDE. */
import { r } from './schema.js';

export default [
  r('m001', 'STRUMENTO_ROTTO', 'realistica', 1, 'Il calderone tre perde',
    'Perde da tre settimane. Ogni volta che lo riempio devo restare lì a guardarlo, e intanto non faccio altro. Saldarlo costa mezza giornata. Non saldarlo costa mezza giornata al giorno.',
    'Lo saldano domani. Buono a sapersi che qualcuno ascolta.', 'Va bene. Continuo a guardarlo io, allora.', 'Fra una settimana perde uguale, però.'),
  r('m002', 'STRUMENTO_ROTTO', 'realistica', 1, 'La bilancia è tarata male',
    'Di dodici grani in eccesso. Su una pozione non si vede, su seicento sì. O la ritariamo, o prima o poi qualcuno si accorge che le nostre fiale pesano più di quello che c’è scritto.',
    'Grazie. Preferivo dirlo io che sentirmelo dire da un ispettore.', 'Allora scrivo da qualche parte che l’avevo detto.', 'Sì, ma prima o poi qualcuno la pesa.'),
  r('m003', 'STRUMENTO_ROTTO', 'realistica', 1, 'Il mantice si è crepato',
    'Tira ancora, ma metà dell’aria se ne va dalla fessura. Il fuoco non arriva alla temperatura giusta e le distillazioni vengono lunghe il doppio. Il fabbro lo ricuce in mezza giornata: glielo porto?',
    'Perfetto. Domani si torna ai tempi normali.', 'Continuo col mantice crepato. Ci vorrà il doppio.', 'Intanto ci mettiamo il doppio.'),
  r('m004', 'STRUMENTO_ROTTO', 'realistica', 2, 'Gli scaffali del magazzino cedono',
    'Il ripiano in fondo si è imbarcato. Regge, ma se ci metto sopra le casse pesanti non lo reggerà. Le sposto a terra e mi ci vuole il doppio del tempo, oppure lo rifacciamo.',
    'Bene. Così smetto di camminare in punta di piedi.', 'Le lascio a terra. Un giorno cadrà comunque.', 'Sposto tutto a terra intanto.'),
  r('m005', 'STRUMENTO_ROTTO', 'sarcastica', 1, 'La porta del laboratorio',
    'Non chiude. Da otto mesi. Ho imparato a spingerla con l’anca tenendo il vassoio con le mani, e adesso ho anche imparato a raccogliere quello che cade quando sbaglio l’anca. Un cardine nuovo costa poco: lo faccio mettere?',
    'Otto mesi. Ma va bene, meglio tardi.', 'Continuo con l’anca. Ormai è un mestiere.', 'Segno sul calendario: mese nono.'),
  r('m006', 'STRUMENTO_ROTTO', 'realistica', 1, 'Gli alambicchi sono da pulire',
    'Il residuo delle vecchie distillazioni sporca le nuove. Il risultato è più torbido e i clienti se ne accorgono. Serve mezza giornata e una cassa di sabbia fine.',
    'Bene. Le prossime escono limpide.', 'Continuiamo a vendere pozioni torbide, allora.', 'Torbide ancora un po’, va bene.'),
  r('m007', 'STRUMENTO_ROTTO', 'demenziale', 1, 'Il termometro è ubriaco',
    'Segna quarantadue gradi quando è spento e cento quando lo tengo in mano. Ho chiesto a quello della forgia: dice che è "una fase". Non credo che i termometri abbiano fasi. Ne compriamo uno che dica la verità?',
    'Grazie. Andrò a lume di naso solo per scelta, non per necessità.', 'Vado a naso. Sono bravo, ma non sono un termometro.', 'Intanto continuo a naso.'),
  r('m008', 'STRUMENTO_ROTTO', 'realistica', 2, 'Il carro delle consegne',
    'Una ruota è ovale. Non rotonda con un difetto: ovale. A ogni giro il carro salta, e a ogni salto qualcosa si rompe dentro le casse. Ho contato nove fiale la settimana scorsa. Il carraio la rifà in un giorno: gliela mando?',
    'Nove fiale a settimana risparmiate. Ci conviene.', 'Allora continuo a caricare meno per volta, e faccio più viaggi.', 'Nel frattempo carico meno.'),
  r('m009', 'STRUMENTO_ROTTO', 'realistica', 1, 'Le lanterne del turno di notte',
    'Ne funzionano tre su sette. Nel buio si lavora piano e si sbaglia, e sbagliare qui vuol dire versarsi addosso qualcosa. Quattro lanterne nuove e il turno torna un turno: le prendo?',
    'Grazie. Vedere quello che si fa aiuta parecchio.', 'Va bene, lavoriamo a memoria.', 'A memoria per un altro po’, allora.'),
  r('m010', 'STRUMENTO_ROTTO', 'sarcastica', 2, 'La cappa aspirante',
    'Aspira verso l’interno. Non so come sia possibile e nemmeno il fabbro lo sa, ma i vapori tornano tutti in faccia a chi sta al banco. È l’unico strumento che peggiora attivamente la situazione. O la si gira o la si smonta: chiamo qualcuno che ci guardi?',
    'Finalmente. Respirare è una gran cosa.', 'Continuo a respirare quello che distillo, allora.', 'Continuo a respirarli, per ora.'),

  r('m011', 'BENEFIT_MATERIALE_PICCOLO', 'realistica', 1, 'Un secondo paio di guanti',
    'Quelli che ho si sono bruciati sul dorso. Ne uso un paio solo e quando è bagnato aspetto che asciughi. Un secondo paio costa poco e mi fa lavorare mentre il primo asciuga.',
    'Ottimo. Da domani lavoro anche il pomeriggio.', 'Aspetto che asciughino, allora.', 'Aspetto. Come sempre.'),
  r('m012', 'BENEFIT_MATERIALE_PICCOLO', 'realistica', 1, 'Uno sgabello più alto',
    'Il banco è alto e io no. Sto in punta di piedi otto ore e la sera non sento più i polpacci. Uno sgabello costa quanto due fiale.',
    'Grazie. Sembra poco e non lo è.', 'Va bene, resto in punta di piedi.', 'In punta di piedi ancora un po’.'),
  r('m013', 'BENEFIT_MATERIALE_PICCOLO', 'realistica', 1, 'Un grembiule nuovo',
    'Il mio ha tre buchi da acido e uno da fuoco. Finché i buchi erano sul grembiule andava bene; adesso cominciano a essere sulla camicia. Me ne dai uno nuovo prima che tocchino la pelle?',
    'Bene. La camicia ringrazia.', 'Terrò la camicia vecchia, allora.', 'Metto la camicia vecchia intanto.'),
  r('m014', 'BENEFIT_MATERIALE_PICCOLO', 'sarcastica', 2, 'Una sedia che non sia quella',
    'La mia sedia ha tre gambe e mezza. La mezza è un mattone. Non chiedo una sedia bella: chiedo una sedia che sia una sedia.',
    'Una sedia. Chi l’avrebbe detto.', 'Tengo il mattone. Gli sono affezionato ormai.', 'Il mattone e io aspettiamo insieme.'),
  r('m015', 'BENEFIT_MATERIALE_PICCOLO', 'realistica', 1, 'Un secondo mortaio',
    'Ne abbiamo uno per tutto il reparto. Passiamo metà del tempo ad aspettare che si liberi, e quando si libera va lavato perché l’ha usato un altro per altro.',
    'Due mortai. Sembra una sciocchezza e ci cambia la giornata.', 'Continuiamo a fare la fila, allora.', 'Continuiamo la fila, per ora.'),
  r('m016', 'BENEFIT_MATERIALE_PICCOLO', 'demenziale', 2, 'Un cuscino per lo sgabello',
    'Non per me: per lo sgabello. Ha un chiodo che sporge e che ormai conosco per nome. Si chiama Bartolomeo e mi aspetta ogni mattina. Un cuscino da due soldi e Bartolomeo smette di esistere: me lo compri?',
    'Grazie. Saluterò Bartolomeo da parte tua.', 'Bartolomeo resta. Ci siamo abituati.', 'Bartolomeo aspetta con me.'),
  r('m017', 'BENEFIT_MATERIALE_PICCOLO', 'realistica', 1, 'Una lampada da banco',
    'Quella comune sta in mezzo alla stanza e io lavoro all’angolo. Faccio ombra su quello che faccio, e quello che faccio è pieno di dettagli piccoli. Una lampada da banco costa poco: me la fai avere?',
    'Bene, adesso vedo quello che dosifico.', 'Continuo a lavorare in ombra.', 'In ombra ancora un po’.'),
  r('m018', 'BENEFIT_MATERIALE_PICCOLO', 'realistica', 1, 'Etichette già stampate',
    'Le scrivo a mano una per una. Sono seicento al mese e la mia calligrafia peggiora dalla duecentesima in poi. Farle stampare costa poco e mi restituisce due giorni.',
    'Due giorni al mese. Buon affare.', 'Continuo a scriverle. Peggiorando.', 'Continuo a scrivere, per adesso.'),
  r('m019', 'BENEFIT_MATERIALE_PICCOLO', 'sarcastica', 1, 'Un secchio che non perde',
    'Il nostro perde. Quando lo porto dal pozzo al banco arriva mezzo. Ho fatto il conto: cammino il doppio per lo stesso lavoro, da due anni. Un secchio nuovo costa meno di una giornata persa: lo compriamo?',
    'Un secchio. Due anni. Ma va bene.', 'Continuo a fare il doppio dei viaggi.', 'Continuo i viaggi doppi.'),
  r('m020', 'BENEFIT_MATERIALE_PICCOLO', 'realistica', 2, 'Un ricambio per la macina',
    'La pietra è consumata al centro. Macina ancora ma lascia i pezzi grossi, e i pezzi grossi non si sciolgono. Una pietra nuova costa poco e vale per anni.',
    'Bene. Le polveri tornano fini.', 'Macino grosso, allora. Si vedrà nel prodotto.', 'Grosso per un altro po’.'),

  r('m021', 'BENEFIT_MATERIALE_GRANDE', 'realistica', 2, 'Un banco tutto mio',
    'Divido il banco con altri due. Ogni volta che ne arriva uno devo spostare tutto quello che ho in corso, e spostare una distillazione a metà vuol dire ricominciare. Se mi assegni il banco d’angolo smetto di ricominciare: me lo dai?',
    'Grazie. Non ricomincio più da capo tre volte al giorno.', 'Continuo a spostare. E a ricominciare.', 'Sposto ancora. Va bene.'),
  r('m022', 'BENEFIT_MATERIALE_GRANDE', 'realistica', 3, 'Un forno secondo',
    'Con uno solo lavoriamo a turni intorno a lui. Con due si lavora in parallelo e si finisce prima. Costa, lo so. Ma il collo di bottiglia è quello e lo sappiamo tutti. Lo mettiamo, il secondo forno?',
    'Due forni. Adesso si ragiona.', 'Restiamo in fila davanti al forno, allora.', 'In fila davanti al forno, ancora.'),
  r('m023', 'BENEFIT_MATERIALE_GRANDE', 'sarcastica', 3, 'Una scrivania in piedi',
    'Ho letto sul bollettino della Gilda che stare seduti accorcia la vita. Non voglio morire per colpa di una scrivania. Ne esistono di quelle alte, e ne ho già visto una che mi piace.',
    'Va bene. Vivrò più a lungo, e lo devo a te.', 'Allora morirò seduto. Che tu lo sappia.', 'Muoio seduto ancora un po’.'),
  r('m024', 'BENEFIT_MATERIALE_GRANDE', 'realistica', 2, 'Una cella fredda',
    'Metà degli ingredienti freschi ci marcisce in mano prima di essere usata. Una cella fredda costa una volta sola; quello che buttiamo lo buttiamo ogni settimana.',
    'Giusto. Smettiamo di buttare.', 'Continuiamo a buttare, allora.', 'Buttiamo ancora un po’.'),
  r('m025', 'BENEFIT_MATERIALE_GRANDE', 'demenziale', 3, 'Un acquario in reception',
    'Ho letto che guardare i pesci abbassa la tensione. Qui la tensione è alta e i pesci costano meno di un medico. Ne bastano sei, e me ne occupo io.',
    'Va bene. Che siano sei, e che li guardi tu.', 'Niente pesci. La tensione resta.', 'I pesci aspettano. Anche la tensione.'),
  r('m026', 'BENEFIT_MATERIALE_GRANDE', 'realistica', 2, 'Un secondo carro',
    'Con uno solo, le consegne a nord e a sud non si possono fare lo stesso giorno. Perdiamo ordini per questo, e li perdiamo sempre a favore degli stessi concorrenti. Con un secondo carro le facciamo tutte e due: lo compriamo?',
    'Bene. Da domani copriamo tutte e due le direzioni.', 'Continuiamo a perdere il nord. O il sud.', 'Perdiamo una direzione ancora un po’.'),
  r('m027', 'BENEFIT_MATERIALE_GRANDE', 'sarcastica', 4, 'Un ufficio con la porta',
    'Lavoro in mezzo al passaggio. Ogni persona che attraversa la stanza mi fa perdere il filo, e in questa stanza si passa molto. Non chiedo un palazzo: chiedo quattro pareti e una porta.',
    'Quattro pareti. Speriamo servano.', 'Resto nel passaggio, allora.', 'Nel passaggio ancora un po’.'),
  r('m028', 'BENEFIT_MATERIALE_GRANDE', 'realistica', 3, 'Un impianto di aerazione',
    'I vapori restano nella stanza tutto il giorno. La sera usciamo con il mal di testa e la mattina rientriamo che c’è ancora l’odore di ieri. Non è un capriccio, è aria. Un impianto si monta in una settimana: lo facciamo?',
    'Grazie. Respirare non dovrebbe essere un privilegio.', 'Continuiamo col mal di testa, allora.', 'Mal di testa ancora un po’.'),
  r('m029', 'BENEFIT_MATERIALE_GRANDE', 'demenziale', 4, 'Una fontana nel cortile',
    'Il rumore dell’acqua concilia la concentrazione: lo dice un trattato che ho letto. Ne esiste una a tre piani con le rane di bronzo che sarebbe perfetta per il cortile. Costa come tre mesi di stipendio, lo so. Te la chiedo lo stesso: la prendiamo?',
    'Le rane di bronzo. Speriamo concilino.', 'Niente rane. Ci concentriamo lo stesso.', 'Le rane aspettano in cortile. Idealmente.'),
  r('m030', 'BENEFIT_MATERIALE_GRANDE', 'realistica', 3, 'Strumenti nuovi per il reparto',
    'I nostri hanno vent’anni e si vede nel prodotto. Non chiedo il meglio: chiedo quello che usano tutti gli altri. Continuare così vuol dire lavorare il doppio per un risultato peggiore.',
    'Bene. Basta lavorare il doppio per fare peggio.', 'Continuiamo col ferro vecchio, allora.', 'Ferro vecchio ancora un po’.'),
];
